# Generated by Django 5.1.4 on 2025-12-17 15:07
"""
StandardDepartment initial migration for `app_modules.core_modules`.

Wrapped in SeparateDatabaseAndState — physical table is owned by
core_modules but was already created by apps.core_apps.0001_initial in
the legacy half of the migration history. State-only operation; the
database is left intact. See chore sprint PR #7 (chore/fix-pre-existing-
migration-drifts) for the full rationale.

Migration architecture in short
-------------------------------
Two apps both declare a model whose `db_table` is 'standard_departments':
  * apps.core_apps.StandardDepartment (legacy, deleted from Python in
    the same chore sprint by removing the model file and unexporting it
    — the migration files remain in the historical chain).
  * app_modules.core_modules.StandardDepartment (canonical, used by
    every live FK in the codebase).

When the full migration graph is replayed on a fresh database, two
physical `CREATE TABLE standard_departments` statements would normally
fire and the second one would crash. The intended sequence is:

  apps.core_apps.0001_initial              (CREATE TABLE — table exists)
  legacy FK creations target core_apps.standarddepartment
  app_modules.core_modules.0001_initial    (STATE ONLY — no CREATE TABLE)
  AlterField repoints                       (FKs move to core_modules.standarddepartment)
  apps.core_apps.0002_delete_standarddepartment  (STATE ONLY — no DROP TABLE)

This migration is the third step. We register `core_modules.StandardDepartment`
in the migration state, pointing at the same `db_table` the legacy app
already created. No DDL fires; the physical table is shared.

Production safety
-----------------
Existing production databases have both core_apps.0001 and
core_modules.0001 already applied. Django never replays applied
migrations, so the SeparateDatabaseAndState wrapper has zero observable
effect on those databases. Only fresh databases (CI / new dev
environments / pytest with --create-db) replay the chain and benefit
from the wrapper.

Dependency on core_apps.0001_initial
------------------------------------
We pin core_apps.0001_initial as an explicit dependency so the
physical table exists by the time core_modules.StandardDepartment is
registered in the migration state. Without the dep, Django's
topological sort could place core_modules.0001 first; subsequent
migrations that look up the table via core_modules.standarddepartment
would have a state model pointing at a non-existent physical table.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Required: the physical `standard_departments` table is created
        # by the legacy core_apps app. We need it to exist before any
        # later migration repoints a FK toward core_modules.StandardDepartment
        # (the repoints alter constraints on the physical table, which
        # must already be there). See module docstring.
        ('core_apps', '0001_initial'),
    ]

    operations = [
        # State-only: register the model in the migration state, but do
        # NOT issue CREATE TABLE — the table was already created by
        # apps.core_apps.0001_initial. SeparateDatabaseAndState lets us
        # keep the canonical Python definition co-located with this app
        # without colliding with the legacy half of the history.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='StandardDepartment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(choices=[('General Management', 'General Management'), ('HR', 'Human Resources (HR)'), ('Finance', 'Finance & Accounting'), ('IT', 'Information Technology (IT)'), ('Marketing', 'Marketing & Communications'), ('Sales', 'Sales & Business Development'), ('Customer Support', 'Customer Support & Success'), ('Operations', 'Operations & Supply Chain'), ('Legal', 'Legal & Compliance'), ('Procurement', 'Procurement & Vendor Management'), ('Engineering', 'Engineering & R&D'), ('Product Management', 'Product Management'), ('Data & Analytics', 'Data & Analytics'), ('Security & Risk Management', 'Security & Risk Management'), ('Healthcare Administration', 'Healthcare Administration'), ('Clinical & Medical Staff', 'Clinical & Medical Staff'), ('Retail Operations', 'Retail & Store Operations'), ('Manufacturing', 'Manufacturing & Production'), ('Logistics', 'Logistics & Transportation'), ('Construction', 'Construction & Engineering'), ('Education & Training', 'Education & Training'), ('Government', 'Government & Public Services'), ('Media', 'Media & Content Creation')], max_length=50, unique=True, verbose_name='Standard Department Name')),
                    ],
                    options={
                        'verbose_name': 'Standard Department',
                        'verbose_name_plural': 'Standard Departments',
                        'db_table': 'standard_departments',
                        'ordering': ['name'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
