# Generated by Django 5.1.4 on 2025-12-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('General Management', 'General Management'), ('HR', 'Human Resources (HR)'), ('Finance', 'Finance & Accounting'), ('IT', 'Information Technology (IT)'), ('Marketing', 'Marketing & Communications'), ('Sales', 'Sales & Business Development'), ('Customer Support', 'Customer Support & Success'), ('Operations', 'Operations & Supply Chain'), ('Legal', 'Legal & Compliance'), ('Procurement', 'Procurement & Vendor Management'), ('Engineering', 'Engineering & R&D'), ('Product Management', 'Product Management'), ('Data & Analytics', 'Data & Analytics'), ('Security & Risk Management', 'Security & Risk Management'), ('Healthcare Administration', 'Healthcare Administration'), ('Clinical & Medical Staff', 'Clinical & Medical Staff'), ('Retail Operations', 'Retail & Store Operations'), ('Manufacturing', 'Manufacturing & Production'), ('Logistics', 'Logistics & Transportation'), ('Construction', 'Construction & Engineering'), ('Education & Training', 'Education & Training'), ('Government', 'Government & Public Services'), ('Media', 'Media & Content Creation')], max_length=50, unique=True, verbose_name='Standard Department Name')),
            ],
            options={
                'verbose_name': 'Standard Department',
                'verbose_name_plural': 'Standard Departments',
                'db_table': 'standard_departments',
                'ordering': ['name'],
            },
        ),
    ]
