# Generated by Django 5.1.4 on 2025-01-14 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_time_connected', models.DateTimeField(blank=True, help_text='Last time the entity was accessed or connected.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the company', max_length=255, unique=True)),
                ('is_b2b', models.BooleanField(default=True, help_text='True if the client is B2B; False for B2C.')),
                ('max_users', models.PositiveIntegerField(default=10, help_text='Maximum number of users allowed for this client.')),
            ],
            options={
                'verbose_name': 'client_account',
                'verbose_name_plural': 'client_accounts',
                'db_table': 'client_accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_time_connected', models.DateTimeField(blank=True, help_text='Last time the entity was accessed or connected.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the organization (e.g., Sales, Management).', max_length=100)),
                ('client_account', models.ForeignKey(help_text='Client this organization belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='end_users.clientaccount')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_time_connected', models.DateTimeField(blank=True, help_text='Last time the entity was accessed or connected.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the team', max_length=100)),
                ('organization', models.ForeignKey(help_text='Organization this team belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='end_users.organization')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_time_connected', models.DateTimeField(blank=True, help_text='Last time the entity was accessed or connected.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('client_account', models.ForeignKey(help_text='The client this user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='end_users.clientaccount')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='end_users_user_set', to='auth.group', verbose_name='groups')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization the user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='end_users.organization')),
                ('team', models.ForeignKey(blank=True, help_text='Team the user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='end_users.team')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='end_users_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(help_text='Manager of the team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to='end_users.user'),
        ),
        migrations.AddField(
            model_name='organization',
            name='manager',
            field=models.ForeignKey(help_text='Director or main manager of the organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_organizations', to='end_users.user'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_time_connected', models.DateTimeField(blank=True, help_text='Last time the entity was accessed or connected.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Role name', max_length=50)),
                ('read', models.BooleanField(default=True)),
                ('write', models.BooleanField(default=False)),
                ('modify', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('client_account', models.ForeignKey(help_text='Client this role belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='end_users.clientaccount')),
            ],
            options={
                'verbose_name': 'user_role',
                'verbose_name_plural': 'users_roles',
                'db_table': 'users_roles',
                'ordering': ['name'],
                'unique_together': {('name', 'client_account')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(help_text='Role assigned to the user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='end_users.userrole'),
        ),
    ]
