# Generated by Django 5.1.4 on 2025-01-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaccount',
            name='last_time_connected',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='last_time_connected',
        ),
        migrations.RemoveField(
            model_name='team',
            name='last_time_connected',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_time_connected',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='last_time_connected',
        ),
    ]
