# Generated by Django 5.1.4 on 2025-08-04 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('end_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('name', models.CharField(help_text='Descriptive name for this quota (e.g., "Q1 2024 Revenue Target")', max_length=100, verbose_name='Quota Name')),
                ('target_type', models.CharField(choices=[('closed_won', 'Closed Won Revenue'), ('pipeline', 'Pipeline Value'), ('meetings', 'Number of Meetings'), ('leads_accepted', 'Leads Accepted'), ('opportunities', 'Number of Opportunities'), ('conversion_rate', 'Conversion Rate %')], help_text='Type of metric this quota tracks', max_length=20, verbose_name='Target Type')),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Target value to achieve (e.g., revenue amount, number of meetings)', max_digits=12, verbose_name='Target Value')),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (e.g., "€", "meetings", "%")', max_length=20, null=True, verbose_name='Unit')),
                ('recurrence_type', models.CharField(choices=[('annual', 'Annual (Yearly)'), ('quarterly', 'Quarterly (Every 3 months)'), ('monthly', 'Monthly')], help_text='How often this quota repeats (Annual/Quarterly/Monthly)', max_length=20, verbose_name='Recurrence Type')),
                ('fiscal_year', models.IntegerField(help_text='Fiscal year this quota belongs to (e.g., 2024)', verbose_name='Fiscal Year')),
                ('period_number', models.IntegerField(default=1, help_text='Period within fiscal year (Q1=1, Q2=2 for quarterly; Month=1-12 for monthly)', verbose_name='Period Number')),
                ('period_start', models.DateField(help_text='Start date of the quota period (auto-calculated from recurrence)', verbose_name='Period Start')),
                ('period_end', models.DateField(help_text='End date of the quota period (auto-calculated from recurrence)', verbose_name='Period End')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', help_text='Current status of this quota', max_length=20, verbose_name='Status')),
                ('is_team_quota', models.BooleanField(default=False, help_text='Whether this is a team-wide quota (vs individual)', verbose_name='Is Team Quota')),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about this quota', null=True, verbose_name='Description')),
                ('activation_date', models.DateTimeField(blank=True, help_text='When this quota was activated', null=True, verbose_name='Activation Date')),
            ],
            options={
                'verbose_name': 'Sales Quota',
                'verbose_name_plural': 'Sales Quotas',
                'db_table': 'sales_quotas',
                'ordering': ['-fiscal_year', '-period_number', 'user__first_name', 'user__last_name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='default_quota_currency',
            field=models.CharField(choices=[('USD', 'DOLLAR'), ('EUR', 'EURO'), ('GBP', 'GREAT BRITAIN POUND')], default='EUR', help_text='Default currency for quotas (EUR, USD, GBP, etc.)', max_length=3, verbose_name='Default Quota Currency'),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='fiscal_year_start_day',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], default=1, help_text='Day when fiscal year starts', verbose_name='Fiscal Year Start Day'),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='fiscal_year_start_month',
            field=models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], default=1, help_text='Month when fiscal year starts (1=January, 2=February, etc.)', verbose_name='Fiscal Year Start Month'),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='timezone',
            field=models.CharField(default='Europe/Paris', help_text="Client's business timezone (e.g., 'Europe/Paris', 'America/New_York')", max_length=50, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Director or main manager of the organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Manager of the team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='client_account',
            field=models.ForeignKey(help_text='The client this user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='end_users.clientaccount', verbose_name='Client Account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Unique email address for authentication', max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active', verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into admin site', verbose_name='Staff Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization the user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='end_users.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role assigned to the user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='end_users.userrole', verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_name',
            field=models.CharField(blank=True, help_text='Cached name of the role for performance.', max_length=50, null=True, verbose_name='Role Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team the user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='end_users.team', verbose_name='Team'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('name', 'client_account')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['client_account', 'is_active'], name='users_client_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['client_account', 'team', 'is_active'], name='users_team_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['client_account', 'organization', 'is_active'], name='users_org_active_idx'),
        ),
        migrations.AddField(
            model_name='salesquota',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Manager who assigned this quota', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotas', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AddField(
            model_name='salesquota',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='salesquota',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='salesquota',
            name='user',
            field=models.ForeignKey(help_text='User this quota is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='sales_quotas', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='salesquota',
            index=models.Index(fields=['user', 'fiscal_year', 'recurrence_type', 'status', 'target_type', 'client_id'], name='sales_quota_user_id_266ec9_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesquota',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'active'])), fields=('user', 'recurrence_type', 'fiscal_year', 'period_number', 'client_id'), name='unique_quota_per_user_period'),
        ),
        migrations.AddConstraint(
            model_name='salesquota',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='valid_period_dates'),
        ),
        migrations.AddConstraint(
            model_name='salesquota',
            constraint=models.CheckConstraint(condition=models.Q(('target_value__gt', 0)), name='positive_target_value'),
        ),
        migrations.AddConstraint(
            model_name='salesquota',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('period_number', 1), ('recurrence_type', 'annual')), models.Q(('period_number__in', [1, 2, 3, 4]), ('recurrence_type', 'quarterly')), models.Q(('period_number__in', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]), ('recurrence_type', 'monthly')), _connector='OR'), name='valid_period_number'),
        ),
        migrations.AlterUniqueTogether(
            name='salesquota',
            unique_together={('user', 'recurrence_type', 'fiscal_year', 'period_number', 'client_id')},
        ),
    ]
