# Generated by Django 5.1.4 on 2025-01-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_users', '0002_remove_clientaccount_last_time_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_name',
            field=models.CharField(blank=True, help_text='The name of the role assigned to the user.', max_length=50, null=True),
        ),
    ]
