# Generated by Django 5.1.4 on 2025-08-06 08:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_alter_campaign_sequence_type'),
        ('end_users', '0002_salesquota_clientaccount_default_quota_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('name', models.CharField(help_text='Descriptive name for this sales plan', max_length=200, verbose_name='Plan Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the plan strategy', null=True, verbose_name='Description')),
                ('period_start', models.DateField(help_text='Start date of the plan period', verbose_name='Period Start')),
                ('period_end', models.DateField(help_text='End date of the plan period', verbose_name='Period End')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('last_progress_update', models.DateTimeField(blank=True, help_text='When progress was last calculated', null=True, verbose_name='Last Progress Update')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('linked_campaigns', models.ManyToManyField(blank=True, help_text='Campaigns associated with this sales plan', related_name='sales_plans', to='campaign.campaign', verbose_name='Linked Campaigns')),
                ('quota', models.ForeignKey(help_text='The quota this plan is designed to achieve', on_delete=django.db.models.deletion.CASCADE, related_name='sales_plans', to='end_users.salesquota', verbose_name='Sales Quota')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_plans', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sales Plan',
                'verbose_name_plural': 'Sales Plans',
                'db_table': 'sales_plans',
                'ordering': ['-period_start', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('name', models.CharField(help_text='Descriptive name for this milestone', max_length=200, verbose_name='Milestone Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of what needs to be achieved', null=True, verbose_name='Description')),
                ('milestone_type', models.CharField(choices=[('LEADS_GENERATED', 'Leads Generated'), ('MEETINGS_SECURED', 'Meetings Secured'), ('OPPORTUNITIES_CREATED', 'Opportunities Created'), ('PIPELINE_VALUE', 'Pipeline Value'), ('CLOSED_WON', 'Closed Won'), ('CUSTOM', 'Custom Milestone')], help_text='Type of metric to track for this milestone', max_length=30, verbose_name='Milestone Type')),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Numeric target to achieve (count or monetary value)', max_digits=15, verbose_name='Target Value')),
                ('target_date', models.DateField(help_text='Date by which this milestone should be achieved', verbose_name='Target Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('ACHIEVED', 'Achieved'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current achievement level (updated automatically)', max_digits=15, verbose_name='Current Value')),
                ('achievement_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of target achieved (updated automatically)', max_digits=5, verbose_name='Achievement Rate %')),
                ('last_progress_update', models.DateTimeField(blank=True, help_text='When progress was last calculated', null=True, verbose_name='Last Progress Update')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('linked_campaigns', models.ManyToManyField(blank=True, help_text='Campaigns contributing to this milestone', related_name='milestones', to='campaign.campaign', verbose_name='Linked Campaigns')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('sales_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='end_users.salesplan', verbose_name='Sales Plan')),
            ],
            options={
                'verbose_name': 'Sales Milestone',
                'verbose_name_plural': 'Sales Milestones',
                'db_table': 'sales_milestones',
                'ordering': ['target_date', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='salesplan',
            index=models.Index(fields=['user', 'status'], name='sales_plans_user_id_16c2e9_idx'),
        ),
        migrations.AddIndex(
            model_name='salesplan',
            index=models.Index(fields=['quota', 'status'], name='sales_plans_quota_i_e19ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='salesplan',
            index=models.Index(fields=['period_start', 'period_end'], name='sales_plans_period__6c76b4_idx'),
        ),
        migrations.AddIndex(
            model_name='salesplan',
            index=models.Index(fields=['last_progress_update'], name='sales_plans_last_pr_1a52e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user', 'quota'), name='unique_active_plan_per_user_quota'),
        ),
        migrations.AddConstraint(
            model_name='salesplan',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='sales_plan_period_coherent'),
        ),
        migrations.AlterUniqueTogether(
            name='salesplan',
            unique_together={('user', 'quota', 'name', 'client_id')},
        ),
        migrations.AddIndex(
            model_name='salesmilestone',
            index=models.Index(fields=['sales_plan', 'status'], name='sales_miles_sales_p_e905ac_idx'),
        ),
        migrations.AddIndex(
            model_name='salesmilestone',
            index=models.Index(fields=['milestone_type', 'target_date'], name='sales_miles_milesto_53be2e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesmilestone',
            index=models.Index(fields=['target_date', 'status'], name='sales_miles_target__97abc5_idx'),
        ),
        migrations.AddIndex(
            model_name='salesmilestone',
            index=models.Index(fields=['achievement_rate'], name='sales_miles_achieve_2d398f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesmilestone',
            index=models.Index(fields=['last_progress_update'], name='sales_miles_last_pr_ec33d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('target_value__gt', 0)), name='milestone_target_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('achievement_rate__gte', 0), ('achievement_rate__lte', 999.99)), name='milestone_achievement_rate_bounds'),
        ),
        migrations.AlterUniqueTogether(
            name='salesmilestone',
            unique_together={('sales_plan', 'name', 'client_id')},
        ),
    ]
