# Generated by Django 5.1.4 on 2025-09-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_users', '0003_salesplan_salesmilestone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Administrator tier - full client access'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_individual',
            field=models.BooleanField(default=True, help_text='Individual tier - personal access'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Manager tier - team access'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_admin', True), ('is_individual', False), ('is_manager', False)), models.Q(('is_admin', False), ('is_individual', False), ('is_manager', True)), models.Q(('is_admin', False), ('is_individual', True), ('is_manager', False)), _connector='OR'), name='exactly_one_tier_active'),
        ),
    ]
