# Generated by Django 5.1.4 on 2025-09-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_users', '0004_add_tier_flag_to_userrole'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='userrole',
        #     name='exactly_one_tier_active',
        # ),
        # migrations.AddConstraint(
        #     model_name='userrole',
        #     constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_admin', True), ('is_individual', False), ('is_manager', False)), models.Q(('is_admin', False), ('is_individual', False), ('is_manager', True)), models.Q(('is_admin', False), ('is_individual', False), ('is_manager', False)), _connector='OR'), name='exactly_one_tier_active'),
        # ),
    ]
