# Generated by Django 5.1.4 on 2025-09-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_users', '0006_remove_userrole_exactly_one_tier_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='is_individual',
            field=models.BooleanField(default=True, help_text='Individual tier - personal access'),
        ),
    ]
