# Generated by Django 5.1.4 on 2025-09-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_users', '0007_alter_userrole_is_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='is_individual',
            field=models.BooleanField(default=False, help_text='Individual tier - personal access'),
        ),
    ]
