# Generated by Django 5.1.4 on 2025-11-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_users', '0008_alter_userrole_is_individual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='delete',
            new_name='can_delete',
        ),
    ]
