# Generated by Django 5.1.4 on 2025-11-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_users', '0009_rename_delete_userrole_can_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='System role - cannot be modified or deleted'),
        ),
    ]
