# Generated by Django 5.1.4 on 2025-11-13 12:36

from django.db import migrations

def mark_admin_roles_as_locked(apps, schema_editor):
    """
    Mark all existing Admin roles as locked (system role).
    This prevents modification or deletion of the default admin role.
    """
    UserRole = apps.get_model('end_users', 'UserRole')
    
    # Update all roles named 'Admin' to be locked
    updated_count = UserRole.objects.filter(name='Admin').update(is_locked=True)
    
    print(f"[DATA MIGRATION] Marked {updated_count} Admin role(s) as locked")


def reverse_mark_admin_roles_as_locked(apps, schema_editor):
    """
    Reverse operation: unlock Admin roles.
    """
    UserRole = apps.get_model('end_users', 'UserRole')
    
    # Unlock all Admin roles (for rollback purposes)
    updated_count = UserRole.objects.filter(name='Admin').update(is_locked=False)
    
    print(f"[DATA MIGRATION REVERSE] Unlocked {updated_count} Admin role(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('end_users', '0010_userrole_is_locked'),
    ]

    operations = [
        migrations.RunPython(
            mark_admin_roles_as_locked,
            reverse_code=reverse_mark_admin_roles_as_locked
        ),
    ]

