# Generated by Django 5.2.15 on 2026-06-11 08:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCatalog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(
                        db_index=True,
                        editable=False,
                        help_text="ID of the client company this record belongs to",
                        verbose_name="Client ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Name of the product (e.g. "Enterprise License", "Professional Services"). Required.',
                        max_length=255,
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of the product.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "value_proposition",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Benefits and value for the sales pitch.",
                        verbose_name="Value Proposition",
                    ),
                ),
                (
                    "default_unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default unit price; can be overridden per deal.",
                        max_digits=14,
                        null=True,
                        verbose_name="Default Unit Price",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Catalog Entry",
                "verbose_name_plural": "Product Catalog Entries",
                "db_table": "product_catalog",
                "ordering": ["name"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["name", "client_id"], name="product_cat_name_d0611d_idx"
                    )
                ],
                "unique_together": {("name", "client_id")},
            },
        ),
    ]
