# Generated by Django 5.1.4 on 2026-05-18 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_activities', '0017_activity_source_decision_cycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('pipeline_type', models.CharField(choices=[('TRANSCRIPT_SIGNALS', 'Transcript signal extraction')], help_text='Identifies which business case produced this run (e.g. TRANSCRIPT_SIGNALS).', max_length=50, verbose_name='Pipeline Type')),
                ('prompt_versions', models.JSONField(blank=True, default=dict, help_text='Mapping prompt-name -> version tag for every prompt used in this run (e.g. {"pain": "v1", "objective": "v1", "techstack": "v1"}). Enables prompt-revision audit when debugging extraction quality drift.', verbose_name='Prompt Versions')),
                ('provider', models.CharField(help_text='Active LLM provider key at run time ("openai", "claude", ...). Captured even when AIPipelineType implies a default - this column reflects what actually executed.', max_length=50, verbose_name='Provider')),
                ('model_name', models.CharField(help_text='Exact model identifier passed to the SDK (e.g. "gpt-4o-mini", "claude-haiku-4-5-20251001"). Captured per run because pipeline-level overrides are possible.', max_length=100, verbose_name='Model')),
                ('temperature', models.FloatField(help_text='Temperature used for this run. Each pipeline declares its own TEMPERATURE constant - capturing here lets the audit trail verify it did not drift.', verbose_name='Temperature')),
                ('input_hash', models.CharField(help_text='sha256 hex of the input transcript (64-character lowercase). The transcript itself is NEVER stored - this hash lets support correlate "same input processed twice" without retaining content.', max_length=64, verbose_name='Input Hash (sha256)')),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial success'), ('PARSE_ERROR', 'Parse error'), ('LLM_ERROR', 'LLM provider error'), ('TIMEOUT', 'Timeout')], default='RUNNING', help_text='RUNNING at orchestrator entry; SUCCESS / PARTIAL / PARSE_ERROR / LLM_ERROR / TIMEOUT at finalisation.', max_length=20, verbose_name='Status')),
                ('sub_calls', models.JSONField(blank=True, default=list, help_text='List of per-call diagnostic dicts: stage, status, model, token counts, duration, error message. Surface for support review when a run lands in PARTIAL / PARSE_ERROR / LLM_ERROR / TIMEOUT.', verbose_name='Sub-call Diagnostics')),
                ('total_tokens_used', models.IntegerField(default=0, help_text='Sum of input + output tokens across all sub-calls. Drives cost monitoring and tenant quota tracking.', verbose_name='Total Tokens Used')),
                ('total_duration_ms', models.IntegerField(blank=True, help_text='Wall-clock duration of the orchestrator run.', null=True, verbose_name='Total Duration (ms)')),
                ('error_message', models.TextField(blank=True, help_text='Top-level orchestrator error when status is a terminal failure. MUST NOT contain user payload (transcript fragments, quotes) - only stack summary and provider message. Privacy-sensitive content sanitised by the orchestrator before persistence.', verbose_name='Error Message')),
                ('created_signals_count', models.IntegerField(default=0, help_text='Number of signals successfully persisted by the run\'s downstream extractor. Lets the API response surface "we extracted N signals" without re-querying.', verbose_name='Created Signals Count')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('source_activity', models.ForeignKey(blank=True, help_text='Activity whose transcript was processed. Nullable to support future pipelines that operate without one (semantic retrieval, batch reprocessing). SET_NULL on Activity deletion so the audit row survives.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_pipeline_runs', to='module_activities.activity', verbose_name='Source Activity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'AI Pipeline Run',
                'verbose_name_plural': 'AI Pipeline Runs',
                'db_table': 'module_ai_pipelines_run',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['client_id', 'created_by', '-created_at'], name='aipipe_client_user_date_idx'), models.Index(fields=['pipeline_type', 'status'], name='aipipe_type_status_idx'), models.Index(fields=['input_hash'], name='aipipe_input_hash_idx')],
            },
        ),
    ]
