# Generated by Django 5.1.14 on 2026-07-09 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(
                        db_index=True,
                        editable=False,
                        help_text="ID of the client company this record belongs to",
                        verbose_name="Client ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MANAGER_NOTE", "Manager note added"),
                            ("ACTIVITY_INVITATION", "Activity invitation"),
                            ("DECISION_CYCLE_CREATED", "Decision cycle created"),
                            ("UNKNOWN_TECH_DETECTED", "Unknown technology detected"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("body", models.TextField(blank=True, default="", verbose_name="Body")),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Type of the originating object, e.g. decision_cycle",
                        max_length=50,
                        verbose_name="Related Object Type",
                    ),
                ),
                (
                    "related_object_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Related Object ID"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra context for deep-linking and display",
                        verbose_name="Payload",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp the recipient read this notification; null = unread",
                        null=True,
                        verbose_name="Read At",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User who should see this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "module_notifications",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["client_id"], name="module_notif_client_idx"),
                    models.Index(
                        fields=["recipient_id", "client_id"],
                        name="module_notif_recip_cli_idx",
                    ),
                    models.Index(
                        fields=["recipient_id", "read_at"],
                        name="module_notif_recip_read_idx",
                    ),
                ],
            },
        ),
    ]
