# Generated by Django 5.1.14 on 2026-07-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="response_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                ],
                default=None,
                help_text="Response state for actionable notifications. null = informative (E1/E4, no action); PENDING/ACCEPTED/DECLINED = actionable (E2/E3)",
                max_length=10,
                null=True,
                verbose_name="Response Status",
            ),
        ),
    ]
