# Generated by Django 5.1.14 on 2026-07-14 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_notifications", "0002_notification_response_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient_id", "response_status", "related_object_id"],
                name="module_notif_todo_exists_idx",
            ),
        ),
    ]
