# Generated by Django 5.1.14 on 2026-08-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_notifications", "0003_notification_module_notif_todo_exists_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("MANAGER_NOTE", "Manager note added"),
                    ("ACTIVITY_INVITATION", "Activity invitation"),
                    ("DECISION_CYCLE_CREATED", "Decision cycle created"),
                ],
                max_length=50,
                verbose_name="Category",
            ),
        ),
    ]
