# Generated by Django 5.1.4 on 2025-12-09 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('ACCOUNT', 'Account-based'), ('CONTACT', 'Contact-based')], default='ACCOUNT', help_text='Whether this territory segments accounts or contacts', max_length=20, verbose_name='Territory Type')),
                ('is_system', models.BooleanField(default=False, help_text='System territories cannot be deleted', verbose_name='System Territory')),
                ('is_default', models.BooleanField(default=False, help_text='Default territory shown when user opens the page', verbose_name='Default Territory')),
                ('filter_definition', models.JSONField(blank=True, default=dict, help_text='JSON object defining filter rules', verbose_name='Filter Definition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_territories', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Territory',
                'verbose_name_plural': 'Territories',
                'db_table': 'module_territories',
                'ordering': ['-is_system', 'name'],
                'abstract': False,
                'indexes': [models.Index(fields=['owner'], name='mod_terr_owner_idx'), models.Index(fields=['type'], name='mod_terr_type_idx'), models.Index(fields=['is_system'], name='mod_terr_system_idx')],
                'unique_together': {('name', 'client_id')},
            },
        ),
    ]
