# Generated by Django 5.1.4 on 2025-12-12 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_territories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='owner',
            field=models.ForeignKey(default='edb4be95-e0cc-4b7e-a0d3-b352da286714', help_text='User who owns this territory', on_delete=django.db.models.deletion.CASCADE, related_name='owned_territories', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
            preserve_default=False,
        ),
    ]
