# Generated by Django 5.1.14 on 2026-07-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_territories", "0002_alter_territory_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="territory",
            name="coverage_computed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the snapshot was last refreshed; null = never (stale)",
                null=True,
                verbose_name="Coverage computed at (snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="territory",
            name="coverage_denominator",
            field=models.IntegerField(
                blank=True,
                help_text="Total accounts in the territory — snapshot, not live",
                null=True,
                verbose_name="Coverage denominator (snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="territory",
            name="coverage_numerator",
            field=models.IntegerField(
                blank=True,
                help_text="Accounts touched with a response in the period — snapshot, not live",
                null=True,
                verbose_name="Coverage numerator (snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="territory",
            name="coverage_period_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The period the snapshot was computed for; a mismatch forces a recompute",
                max_length=64,
                verbose_name="Coverage period key (snapshot)",
            ),
        ),
    ]
