# Generated by Django 5.1.4 on 2025-04-10 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_account_implications_remove_account_metrics_and_more'),
        ('core_apps', '0001_initial'),
        ('end_users', '0001_initial'),
        ('products', '0002_remove_product_potential_cons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('category', models.CharField(choices=[('PROFILE', 'Profile Data'), ('PROCESS', 'Process'), ('TECH_STACK', 'Technology Stack'), ('QUALIFICATION', 'Qualification'), ('PROJECT', 'Project')], max_length=20, verbose_name='Signal Category')),
                ('entity_type', models.CharField(choices=[('ACCOUNT', 'Account'), ('ACCOUNT_PRODUCT', 'Account Product Detail')], max_length=20, verbose_name='Entity Type')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('value', models.JSONField(verbose_name='Signal Value')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied'), ('MERGED', 'Merged')], default='PENDING', max_length=20, verbose_name='Signal Status')),
                ('confirmation_count', models.PositiveIntegerField(default=1, verbose_name='Confirmation Count')),
                ('last_confirmed_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Confirmed At')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Source')),
                ('revisit_date', models.DateTimeField(blank=True, null=True, verbose_name='Revisit Date')),
                ('applied_date', models.DateTimeField(blank=True, null=True, verbose_name='Applied Date')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata for validations, history, and context', null=True, verbose_name='Metadata')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set_new', to='accounts.account', verbose_name='Account')),
                ('account_product_relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='accounts.accountproductrelationship', verbose_name='Account Product relationship')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_signals', to='end_users.user', verbose_name='Approved By')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='accounts.contact', verbose_name='Contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from_signals', to='signals.signal', verbose_name='Merged Into Signal')),
                ('parent_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_signals', to='signals.signal', verbose_name='Parent Signal')),
                ('product_alignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aligned_signals', to='products.product', verbose_name='Aligned Products')),
                ('source_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_signals', to='accounts.contact', verbose_name='Source Contact')),
                ('source_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_signals', to='core_apps.standarddepartment', verbose_name='Source Department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
