# Generated by Django 5.1.4 on 2025-04-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_implications_remove_account_metrics_and_more'),
        ('core_apps', '0001_initial'),
        ('end_users', '0001_initial'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('value', models.JSONField(verbose_name='Signal Value')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied'), ('MERGED', 'Merged')], default='PENDING', max_length=20, verbose_name='Signal Status')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Source')),
                ('confirmation_count', models.PositiveIntegerField(default=1, verbose_name='Confirmation Count')),
                ('last_confirmed_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Confirmed At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata for validations, history, and context', null=True, verbose_name='Metadata')),
                ('field_name', models.CharField(choices=[('company_size', 'Company Size'), ('annual_revenue', 'Annual Revenue')], max_length=50, verbose_name='Profile Field')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set_new', to='accounts.account', verbose_name='Account')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to='end_users.user', verbose_name='Approved By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from_signals', to='signals.profilesignal', verbose_name='Merged Into Signal')),
                ('source_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_provided', to='accounts.contact', verbose_name='Source Contact')),
                ('source_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_department', to='core_apps.standarddepartment', verbose_name='Source Department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Profile Signal',
                'verbose_name_plural': 'Profile Signals',
                'indexes': [models.Index(fields=['account', 'field_name'], name='signals_pro_account_47ed0f_idx'), models.Index(fields=['status'], name='signals_pro_status_ead124_idx')],
            },
        ),
        migrations.CreateModel(
            name='QualificationSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('value', models.JSONField(verbose_name='Signal Value')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied'), ('MERGED', 'Merged')], default='PENDING', max_length=20, verbose_name='Signal Status')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Source')),
                ('confirmation_count', models.PositiveIntegerField(default=1, verbose_name='Confirmation Count')),
                ('last_confirmed_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Confirmed At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata for validations, history, and context', null=True, verbose_name='Metadata')),
                ('field_name', models.CharField(choices=[('objectives', 'Objectives'), ('motivations', 'Motivations'), ('metrics', 'Metrics'), ('pain_points', 'Pain Points'), ('implications', 'Implications')], max_length=50, verbose_name='Qualification Field')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set_new', to='accounts.account', verbose_name='Account')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to='end_users.user', verbose_name='Approved By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from_signals', to='signals.qualificationsignal', verbose_name='Merged Into Signal')),
                ('source_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_provided', to='accounts.contact', verbose_name='Source Contact')),
                ('source_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_department', to='core_apps.standarddepartment', verbose_name='Source Department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Qualification Signal',
                'verbose_name_plural': 'Qualification Signals',
                'indexes': [models.Index(fields=['account', 'field_name'], name='signals_qua_account_4a946b_idx'), models.Index(fields=['status'], name='signals_qua_status_6a74ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='TechStackSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('value', models.JSONField(verbose_name='Signal Value')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied'), ('MERGED', 'Merged')], default='PENDING', max_length=20, verbose_name='Signal Status')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Source')),
                ('confirmation_count', models.PositiveIntegerField(default=1, verbose_name='Confirmation Count')),
                ('last_confirmed_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Confirmed At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata for validations, history, and context', null=True, verbose_name='Metadata')),
                ('field_name', models.CharField(choices=[('purpose', 'Purpose'), ('pros', 'Pros'), ('cons', 'Cons'), ('costs', 'Costs'), ('renewal_date', 'Renewal Date'), ('start_year_of_usage', 'Start year of Usage')], max_length=50, verbose_name='Tech Stack Field')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set_new', to='accounts.account', verbose_name='Account')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to='end_users.user', verbose_name='Approved By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from_signals', to='signals.techstacksignal', verbose_name='Merged Into Signal')),
                ('source_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_provided', to='accounts.contact', verbose_name='Source Contact')),
                ('source_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_department', to='core_apps.standarddepartment', verbose_name='Source Department')),
                ('tech_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='accounts.techstack', verbose_name='Technology')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Tech Stack Signal',
                'verbose_name_plural': 'Tech Stack Signals',
                'indexes': [models.Index(fields=['account', 'tech_stack'], name='signals_tec_account_a4671a_idx'), models.Index(fields=['field_name'], name='signals_tec_field_n_2dc599_idx')],
            },
        ),
    ]
