# Generated by Django 5.1.4 on 2025-04-16 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_account_historical_data_and_more'),
        ('signals', '0002_profilesignal_qualificationsignal_techstacksignal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstacksignal',
            name='tech_stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='accounts.techstack', verbose_name='Technology'),
        ),
        migrations.DeleteModel(
            name='Signal',
        ),
    ]
