# Generated by Django 5.1.4 on 2025-12-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_modules', '0001_initial'),
        ('signals', '0003_alter_techstacksignal_tech_stack_delete_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesignal',
            name='source_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_department', to='core_modules.standarddepartment', verbose_name='Source Department'),
        ),
        migrations.AlterField(
            model_name='qualificationsignal',
            name='source_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_department', to='core_modules.standarddepartment', verbose_name='Source Department'),
        ),
        migrations.AlterField(
            model_name='techstacksignal',
            name='source_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_department', to='core_modules.standarddepartment', verbose_name='Source Department'),
        ),
    ]
