# Generated by Django 5.1.4 on 2025-12-17 15:07

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_modules', '0001_initial'),
        ('module_accounts', '0003_alter_companyaccount_industry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('post_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Post Code')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State/Region')),
                ('country', models.CharField(choices=[('AD', 'Andorra'), ('AE', 'United Arab Emirates'), ('AF', 'Afghanistan'), ('AG', 'Antigua and Barbuda'), ('AI', 'Anguilla'), ('AL', 'Albania'), ('AM', 'Armenia'), ('AO', 'Angola'), ('AR', 'Argentina'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BA', 'Bosnia and Herzegovina'), ('BB', 'Barbados'), ('BD', 'Bangladesh'), ('BE', 'Belgium'), ('BF', 'Burkina Faso'), ('BG', 'Bulgaria'), ('BH', 'Bahrain'), ('BI', 'Burundi'), ('BJ', 'Benin'), ('BR', 'Brazil'), ('CA', 'Canada'), ('CN', 'China'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('DE', 'Germany'), ('DK', 'Denmark'), ('DO', 'Dominican Republic'), ('DZ', 'Algeria'), ('EC', 'Ecuador'), ('EE', 'Estonia'), ('EG', 'Egypt'), ('ES', 'Spain'), ('FI', 'Finland'), ('FR', 'France'), ('GB', 'United Kingdom'), ('GR', 'Greece'), ('HU', 'Hungary'), ('ID', 'Indonesia'), ('IE', 'Ireland'), ('IN', 'India'), ('IT', 'Italy'), ('JP', 'Japan'), ('KE', 'Kenya'), ('KR', 'South Korea'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MX', 'Mexico'), ('NG', 'Nigeria'), ('NL', 'Netherlands'), ('NO', 'Norway'), ('NZ', 'New Zealand'), ('PK', 'Pakistan'), ('PL', 'Poland'), ('PT', 'Portugal'), ('RU', 'Russia'), ('SA', 'Saudi Arabia'), ('SE', 'Sweden'), ('SG', 'Singapore'), ('TH', 'Thailand'), ('TR', 'Turkey'), ('UA', 'Ukraine'), ('US', 'United States'), ('VN', 'Vietnam'), ('ZA', 'South Africa'), ('ZW', 'Zimbabwe')], default='US', max_length=2, verbose_name='Country')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Invalid phone number format'}, max_length=20, null=True, region=None, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, error_messages={'invalid': 'Invalid URL format'}, null=True, verbose_name='Website')),
                ('linkedin', models.URLField(blank=True, error_messages={'invalid': 'Invalid URL format'}, null=True, verbose_name='LinkedIn Profile')),
                ('email_is_valid', models.BooleanField(default=True, help_text='Whether the email address is valid and not bouncing', verbose_name='Email is Valid')),
                ('phone_is_valid', models.BooleanField(default=True, help_text='Whether the phone number is valid and reachable', verbose_name='Phone is Valid')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('job_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Job Title')),
                ('department', models.CharField(blank=True, max_length=200, null=True, verbose_name='Department')),
                ('influence_level', models.CharField(choices=[('DECISION_MAKER', 'Decision Maker'), ('INFLUENCER', 'Influencer'), ('CHAMPION', 'Champion'), ('USER', 'User'), ('GATEKEEPER', 'Gatekeeper'), ('BLOCKER', 'Blocker'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50, verbose_name='Influence Level')),
                ('has_buying_authority', models.BooleanField(blank=True, null=True, verbose_name='Has Buying Authority')),
                ('opted_out', models.BooleanField(default=False, help_text='Whether the contact has opted out of communications', verbose_name='Opted Out')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('account', models.ForeignKey(help_text='The company account this contact belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='module_accounts.companyaccount', verbose_name='Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('standard_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_contacts', to='core_modules.standarddepartment', verbose_name='Standard Department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'module_contacts',
                'ordering': ['last_name', 'first_name'],
                'abstract': False,
                'indexes': [models.Index(fields=['first_name', 'last_name', 'client_id'], name='module_cont_first_n_da6ea2_idx')],
                'unique_together': {('account', 'email', 'client_id')},
            },
        ),
    ]
