# Generated by Django 5.1.4 on 2025-12-22 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_modules', '0001_initial'),
        ('module_accounts', '0003_alter_companyaccount_industry'),
        ('module_contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contact',
            name='module_cont_first_n_da6ea2_idx',
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['client_id'], name='module_cont_client_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['account_id'], name='module_cont_account_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['account_id', 'client_id'], name='module_cont_acc_client_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email', 'client_id'], name='module_cont_email_client_idx'),
        ),
    ]
