# Generated by Django 5.1.4 on 2025-02-26 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('end_users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('entity_type', models.CharField(choices=[('account', 'Account'), ('org_unit', 'Organization Unit'), ('contact', 'Contact')], max_length=20, verbose_name='Entity Type')),
                ('entity_id', models.UUIDField(verbose_name='Entity ID')),
                ('field_name', models.CharField(max_length=50, verbose_name='Field Name')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Old Value')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='New Value')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Source')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_qualification_changes', to='end_users.user', verbose_name='Approved By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Qualification Change',
                'verbose_name_plural': 'Qualification Changes',
                'db_table': 'qualification_changes',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
