# Generated by Django 5.1.4 on 2026-01-06 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_modules', '0001_initial'),
        ('module_accounts', '0003_alter_companyaccount_industry'),
        ('module_contacts', '0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Cycle Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the currently displayed cycle for the account', verbose_name='Is Active')),
                ('account', models.ForeignKey(help_text='The company account this decision cycle belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='decision_cycles', to='module_accounts.companyaccount', verbose_name='Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Decision Cycle',
                'verbose_name_plural': 'Decision Cycles',
                'db_table': 'decision_cycles',
                'ordering': ['-is_active', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecisionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text='Name of this decision step', max_length=255, verbose_name='Step Name')),
                ('stage', models.CharField(choices=[('EXPLORATION', 'Exploration'), ('CRITERIA_VALIDATION', 'Criteria Validation'), ('SOLUTION_CONFIRMATION', 'Solution Confirmation'), ('BUSINESS_VALIDATION', 'Business Validation'), ('FORMALIZATION', 'Formalization')], help_text='Fixed stage this step belongs to', max_length=30, verbose_name='Stage')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING_CLIENT', 'Pending Client'), ('IN_PROGRESS', 'In Progress'), ('IN_CHASING', 'In Chasing'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=20, verbose_name='Status')),
                ('stakeholder', models.CharField(blank=True, help_text='Role of the person responsible for this step', max_length=255, null=True, verbose_name='Stakeholder')),
                ('description', models.TextField(blank=True, help_text='What will be done in this step', null=True, verbose_name='Step Description')),
                ('goal', models.TextField(blank=True, help_text='What this step aims to achieve', null=True, verbose_name='Step Goal')),
                ('influence_score', models.PositiveSmallIntegerField(default=0, help_text='Score from 0-100 indicating importance level', verbose_name='Influence Score')),
                ('criterias', models.JSONField(blank=True, default=list, help_text='What they will be looking for', null=True, verbose_name='Criterias')),
                ('metrics', models.JSONField(blank=True, default=list, help_text='KPIs to measure success', null=True, verbose_name='Metrics')),
                ('expected_days', models.PositiveIntegerField(blank=True, help_text='Expected duration before moving to next step', null=True, verbose_name='Expected Days')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='decision_cycles.decisioncycle', verbose_name='Decision Cycle')),
                ('previous_step', models.ForeignKey(blank=True, help_text='The step that must be completed before this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_steps', to='decision_cycles.decisionstep', verbose_name='Previous Step')),
                ('standard_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_modules.standarddepartment', verbose_name='Department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Decision Step',
                'verbose_name_plural': 'Decision Steps',
                'db_table': 'decision_steps',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecisionStepContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_decision_steps', to='module_contacts.contact', verbose_name='Contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_contacts', to='decision_cycles.decisionstep', verbose_name='Step')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Decision Step Contact',
                'verbose_name_plural': 'Decision Step Contacts',
                'db_table': 'decision_step_contacts',
            },
        ),
        migrations.AddField(
            model_name='decisionstep',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='decision_steps', through='decision_cycles.DecisionStepContact', to='module_contacts.contact', verbose_name='Contacts'),
        ),
        migrations.AddIndex(
            model_name='decisioncycle',
            index=models.Index(fields=['account'], name='dc_account_idx'),
        ),
        migrations.AddIndex(
            model_name='decisioncycle',
            index=models.Index(fields=['is_active'], name='dc_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='decisioncycle',
            unique_together={('account', 'name', 'client_id')},
        ),
        migrations.AlterUniqueTogether(
            name='decisionstepcontact',
            unique_together={('step', 'contact')},
        ),
        migrations.AddIndex(
            model_name='decisionstep',
            index=models.Index(fields=['cycle'], name='ds_cycle_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionstep',
            index=models.Index(fields=['stage'], name='ds_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionstep',
            index=models.Index(fields=['status'], name='ds_status_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionstep',
            index=models.Index(fields=['previous_step'], name='ds_prev_step_idx'),
        ),
    ]
