# Generated by Django 5.1.4 on 2026-01-08 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_modules', '0001_initial'),
        ('decision_cycles', '0001_initial'),
        ('module_contacts', '0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionstep',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When this step was validated or rejected', null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='decisionstep',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Specific date if known (e.g., meeting date)', null=True, verbose_name='Scheduled Date'),
        ),
        migrations.AddField(
            model_name='decisionstep',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Specific time if applicable', null=True, verbose_name='Scheduled Time'),
        ),
        migrations.AddField(
            model_name='decisionstep',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When this step actually started', null=True, verbose_name='Started At'),
        ),
        migrations.AddField(
            model_name='decisionstep',
            name='step_type',
            field=models.CharField(choices=[('MEETING', 'Meeting'), ('CALL', 'Call'), ('EMAIL', 'Email'), ('TASK_SELLER', 'Task (Seller)'), ('TASK_BUYER', 'Task (Buyer)'), ('INTERNAL_VALIDATION', 'Internal Validation'), ('OTHER', 'Other')], default='OTHER', help_text='Type of step: meeting, call, task, etc.', max_length=30, verbose_name='Step Type'),
        ),
        migrations.CreateModel(
            name='DecisionStepDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_decision_steps', to='core_modules.standarddepartment', verbose_name='Department')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_departments', to='decision_cycles.decisionstep', verbose_name='Step')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Decision Step Department',
                'verbose_name_plural': 'Decision Step Departments',
                'db_table': 'decision_step_departments',
            },
        ),
        migrations.AddField(
            model_name='decisionstep',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='decision_steps', through='decision_cycles.DecisionStepDepartment', to='core_modules.standarddepartment', verbose_name='Departments'),
        ),
        migrations.AddIndex(
            model_name='decisionstep',
            index=models.Index(fields=['step_type'], name='ds_step_type_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionstep',
            index=models.Index(fields=['scheduled_date'], name='ds_scheduled_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='decisionstepdepartment',
            unique_together={('step', 'department')},
        ),
    ]
