# Generated by Django 5.1.4 on 2026-01-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_cycles', '0002_decisionstep_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisionstep',
            name='expected_days',
        ),
        migrations.AddField(
            model_name='decisionstep',
            name='expected_date',
            field=models.DateField(blank=True, help_text='Expected date for step validation/completion', null=True, verbose_name='Expected Date'),
        ),
        migrations.AddField(
            model_name='decisionstep',
            name='manager_notes',
            field=models.TextField(blank=True, help_text='Internal notes visible only to managers', null=True, verbose_name='Manager Notes'),
        ),
    ]
