# Generated by Django 5.1.4 on 2026-01-19 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_modules', '0001_initial'),
        ('decision_cycles', '0004_remove_execution_fields_rename_dates'),
        ('module_contacts', '0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionstep',
            name='expected_end',
            field=models.DateField(help_text='Expected date for step validation/completion - MANDATORY for timeline', verbose_name='Expected End'),
        ),
        migrations.AlterField(
            model_name='decisionstep',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='When this step actually started (inferred from first activity)', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='decisionstep',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING_CLIENT', 'Pending Client'), ('IN_PROGRESS', 'In Progress'), ('IN_CHASING', 'In Chasing'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold')], default='NOT_STARTED', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='decisionstep',
            index=models.Index(fields=['expected_end'], name='ds_expected_end_idx'),
        ),
    ]
