# Generated by Django 5.1.4 on 2026-01-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_cycles', '0005_alter_decisionstep_expected_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionstep',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order in pipeline (1-7), auto-set from PipelineStep config', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='decisionstep',
            name='stage',
            field=models.CharField(choices=[('QUALIFICATION', 'Qualification'), ('TECHNICAL_FIT', 'Technical Fit'), ('SOLUTION_VALIDATION', 'Solution Validation'), ('BUSINESS_CASE', 'Business Case'), ('CLOSING', 'Closing'), ('IMPLEMENTATION', 'Implementation'), ('GO_LIVE', 'Go Live')], help_text='Fixed pipeline step - auto-assigned, cannot be changed by user', max_length=30, verbose_name='Pipeline Step'),
        ),
        migrations.AlterField(
            model_name='decisionstep',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING_CLIENT', 'Pending Client'), ('IN_PROGRESS', 'In Progress'), ('IN_CHASING', 'In Chasing'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20, verbose_name='Status'),
        ),
    ]
