# Generated by Django 5.1.4 on 2026-01-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_cycles', '0006_decisionstep_order_alter_decisionstep_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionstep',
            name='expected_end',
            field=models.DateField(blank=True, help_text='Expected date for step completion - set by user after cycle creation', null=True, verbose_name='Expected End'),
        ),
    ]
