# Generated by Django 5.1.4 on 2026-02-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_cycles', '0007_alter_decisionstep_expected_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionstep',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('IN_CHASING', 'In Chasing'), ('OVERDUE', 'Overdue'), ('VALIDATED', 'Validated'), ('WON', 'Won'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=20, verbose_name='Status'),
        ),
    ]
