# Generated by Django 5.1.4 on 2026-02-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_cycles', '0008_alter_decisionstep_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisioncycle',
            name='hold_until',
            field=models.DateField(blank=True, help_text='Resume date when cycle is ON_HOLD. Required for ON_HOLD only.', null=True, verbose_name='Hold Until'),
        ),
        migrations.AddField(
            model_name='decisioncycle',
            name='outcome',
            field=models.CharField(blank=True, choices=[('WON', 'Won'), ('LOST', 'Lost'), ('ON_HOLD', 'On Hold'), ('NOT_QUALIFIED', 'Not Qualified')], help_text='Explicit cycle-level strategic decision. WON/LOST/NOT_QUALIFIED = terminal (PLANNED cancelled). ON_HOLD = paused (PLANNED kept). null = cycle still open, status derived from steps.', max_length=20, null=True, verbose_name='Outcome'),
        ),
        migrations.AddField(
            model_name='decisioncycle',
            name='outcome_date',
            field=models.DateField(blank=True, help_text='Date when the outcome decision was made (auto-set on close)', null=True, verbose_name='Outcome Date'),
        ),
        migrations.AddField(
            model_name='decisioncycle',
            name='outcome_notes',
            field=models.TextField(blank=True, help_text='Reason or context for the outcome. Required for ON_HOLD.', null=True, verbose_name='Outcome Notes'),
        ),
        migrations.AlterField(
            model_name='decisionstep',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('STALLED', 'Stalled'), ('IN_CHASING', 'In Chasing'), ('OVERDUE', 'Overdue'), ('VALIDATED', 'Validated')], default='NOT_STARTED', max_length=20, verbose_name='Status'),
        ),
    ]
