# Generated by Django 5.1.4 on 2026-03-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_cycles', '0010_decisioncycle_owner'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='decisioncycle',
            name='dc_owner_idx',
        ),
        migrations.AddField(
            model_name='decisioncycle',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated deal value for pipeline/revenue tracking in campaigns', max_digits=14, null=True, verbose_name='Estimated Value'),
        ),
    ]
