# Generated by Django 5.1.4 on 2026-03-24 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_cycles', '0011_remove_decisioncycle_dc_owner_idx_and_more'),
        ('module_campaigns', '0013_delete_campaignmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisioncycle',
            name='source_campaign',
            field=models.ForeignKey(blank=True, help_text='Campaign that triggered the creation of this decision cycle. Set during campaign-to-cycle conversion flow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cycles', to='module_campaigns.campaign', verbose_name='Source Campaign'),
        ),
    ]
