# Generated by Django 5.2.15 on 2026-06-11 08:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decision_cycles", "0012_decisioncycle_source_campaign"),
        ("module_ai_pipelines", "0002_alter_aipipelinerun_pipeline_type"),
        ("product_catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DealHealthSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(
                        db_index=True,
                        editable=False,
                        help_text="ID of the client company this record belongs to",
                        verbose_name="Client ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "diagnostic",
                    models.JSONField(
                        help_text="Structured JSON output: dimensions, gaps, levers, themes.",
                        verbose_name="Diagnostic",
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Snapshot Date"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "decision_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_snapshots",
                        to="decision_cycles.decisioncycle",
                        verbose_name="Decision Cycle",
                    ),
                ),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deal_health_snapshots",
                        to="module_ai_pipelines.aipipelinerun",
                        verbose_name="Pipeline Run",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal Health Snapshot",
                "verbose_name_plural": "Deal Health Snapshots",
                "db_table": "deal_health_snapshots",
                "ordering": ["-snapshot_date"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["decision_cycle", "-snapshot_date"],
                        name="dhs_cycle_date_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DealProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(
                        db_index=True,
                        editable=False,
                        help_text="ID of the client company this record belongs to",
                        verbose_name="Client ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Quantity")),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overrides the catalog default_unit_price when set.",
                        max_digits=14,
                        null=True,
                        verbose_name="Unit Price Override",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "decision_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_products",
                        to="decision_cycles.decisioncycle",
                        verbose_name="Decision Cycle",
                    ),
                ),
                (
                    "product_catalog_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deal_products",
                        to="product_catalog.productcatalog",
                        verbose_name="Product Catalog Entry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal Product",
                "verbose_name_plural": "Deal Products",
                "db_table": "deal_products",
                "abstract": False,
                "unique_together": {
                    ("decision_cycle", "product_catalog_entry", "client_id")
                },
            },
        ),
    ]
