# Generated by Django 5.2.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decision_cycles", "0013_dealhealthsnapshot_dealproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisioncycle",
            name="readiness_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=None,
                help_text="Auto-computed score (0-100) from validated signals and deal evidence.",
                null=True,
                verbose_name="Readiness Score",
            ),
        ),
    ]
