# Generated by Django 5.1.14 on 2026-07-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decision_cycles", "0016_alter_managernote_client_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealproduct",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentage discount applied to this line (0–100).",
                max_digits=5,
                verbose_name="Discount %",
            ),
        ),
    ]
