# Generated by Django 5.1.14 on 2026-07-14 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decision_cycles", "0017_dealproduct_discount_percent"),
        ("module_accounts", "0003_alter_companyaccount_industry"),
        ("module_campaigns", "0014_campaign_channel_override"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="decisioncycle",
            index=models.Index(
                fields=["outcome", "outcome_date"], name="dc_outcome_date_idx"
            ),
        ),
    ]
