# Generated by Django 5.1.14 on 2026-07-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decision_cycles", "0018_decisioncycle_dc_outcome_date_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="decisionstep",
            name="ds_status_idx",
        ),
        migrations.RemoveField(
            model_name="decisionstep",
            name="status",
        ),
    ]
