# Generated by Django 5.1.14 on 2026-08-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decision_cycles", "0022_remove_decisioncycle_closed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisioncycle",
            name="expected_close_date",
            field=models.DateField(
                blank=True,
                help_text="When the rep expects this deal to close. MANUAL and optional: it is the FIRST level of the effective close date (services/close_date_sql.py) — when set it wins, otherwise the date is derived from the CLOSING step's last activity. That effective date is what windows a personal PIPELINE objective, so setting it here is how a rep puts a deal in a given period.",
                null=True,
                verbose_name="Expected Close Date",
            ),
        ),
    ]
