# Generated by Django 5.1.4 on 2025-01-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('product_admin', '0002_alter_productadmin_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadmin',
            name='last_time_connected',
            field=models.DateTimeField(blank=True, help_text='Last time the entity was accessed or connected.', null=True),
        ),
        migrations.AlterField(
            model_name='productadmin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this admin belongs to.', related_name='product_admin_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='productadmin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this admin.', related_name='product_admin_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
