# Generated by Django 5.1.4 on 2025-01-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_admin', '0003_productadmin_last_time_connected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productadmin',
            name='last_time_connected',
        ),
    ]
