# Generated by Django 5.1.4 on 2025-05-12 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('end_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sequence Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('total_steps', models.IntegerField(default=10, verbose_name='Total Steps')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Sequence Template',
                'verbose_name_plural': 'Sequence Templates',
                'indexes': [models.Index(fields=['is_active'], name='sequence_se_is_acti_450d4c_idx')],
            },
        ),
    ]
