# Generated by Django 5.1.4 on 2025-05-12 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_users', '0001_initial'),
        ('sequence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('step_number', models.IntegerField(verbose_name='Step Number')),
                ('activity_type', models.CharField(choices=[('EMAIL', 'Email'), ('CALL', 'Call'), ('LINKEDIN', 'LinkedIn Message'), ('TASK', 'Manual Task')], max_length=20, verbose_name='Activity Type')),
                ('title', models.CharField(max_length=200, verbose_name='Step Title')),
                ('delay_days', models.IntegerField(default=1, help_text='Days after previous step')),
                ('is_first', models.BooleanField(default=False)),
                ('is_last', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('next_step', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_step', to='sequence.sequencestep', verbose_name='Next Step')),
                ('sequence_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='sequence.sequencetemplate', verbose_name='Sequence Template')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Sequence Step',
                'verbose_name_plural': 'Sequence Steps',
                'ordering': ['step_number'],
                'unique_together': {('sequence_template', 'step_number')},
            },
        ),
    ]
