# Generated by Django 5.1.4 on 2025-11-28 13:05

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('end_users', '0012_transition_to_client_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('post_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Post Code')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State/Region')),
                ('country', models.CharField(choices=[('AD', 'Andorra'), ('AE', 'United Arab Emirates'), ('AF', 'Afghanistan'), ('AG', 'Antigua and Barbuda'), ('AI', 'Anguilla'), ('AL', 'Albania'), ('AM', 'Armenia'), ('AO', 'Angola'), ('AR', 'Argentina'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BA', 'Bosnia and Herzegovina'), ('BB', 'Barbados'), ('BD', 'Bangladesh'), ('BE', 'Belgium'), ('BF', 'Burkina Faso'), ('BG', 'Bulgaria'), ('BH', 'Bahrain'), ('BI', 'Burundi'), ('BJ', 'Benin'), ('BR', 'Brazil'), ('CA', 'Canada'), ('CN', 'China'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('DE', 'Germany'), ('DK', 'Denmark'), ('DO', 'Dominican Republic'), ('DZ', 'Algeria'), ('EC', 'Ecuador'), ('EE', 'Estonia'), ('EG', 'Egypt'), ('ES', 'Spain'), ('FI', 'Finland'), ('FR', 'France'), ('GB', 'United Kingdom'), ('GR', 'Greece'), ('HU', 'Hungary'), ('ID', 'Indonesia'), ('IE', 'Ireland'), ('IN', 'India'), ('IT', 'Italy'), ('JP', 'Japan'), ('KE', 'Kenya'), ('KR', 'South Korea'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MX', 'Mexico'), ('NG', 'Nigeria'), ('NL', 'Netherlands'), ('NO', 'Norway'), ('NZ', 'New Zealand'), ('PK', 'Pakistan'), ('PL', 'Poland'), ('PT', 'Portugal'), ('RU', 'Russia'), ('SA', 'Saudi Arabia'), ('SE', 'Sweden'), ('SG', 'Singapore'), ('TH', 'Thailand'), ('TR', 'Turkey'), ('UA', 'Ukraine'), ('US', 'United States'), ('VN', 'Vietnam'), ('ZA', 'South Africa'), ('ZW', 'Zimbabwe')], default='US', max_length=2, verbose_name='Country')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Invalid phone number format'}, max_length=20, null=True, region=None, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, error_messages={'invalid': 'Invalid URL format'}, null=True, verbose_name='Website')),
                ('linkedin', models.URLField(blank=True, error_messages={'invalid': 'Invalid URL format'}, null=True, verbose_name='LinkedIn Profile')),
                ('email_is_valid', models.BooleanField(default=True, help_text='Whether the email address is valid and not bouncing', verbose_name='Email is Valid')),
                ('phone_is_valid', models.BooleanField(default=True, help_text='Whether the phone number is valid and reachable', verbose_name='Phone is Valid')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry')),
                ('type', models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('PROSPECT', 'Prospect'), ('PARTNER', 'Partner'), ('VENDOR', 'Vendor'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Account Type')),
                ('classification', models.CharField(blank=True, choices=[('SMB', 'Small and Medium Business'), ('MIDMARKET', 'Mid-Market'), ('ENTERPRISE', 'Enterprise'), ('STARTUP', 'Startup'), ('NONPROFIT', 'Non-Profit')], max_length=50, null=True, verbose_name='Account Classification')),
                ('company_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Number of Employees')),
                ('annual_revenue', models.CharField(blank=True, max_length=100, null=True, verbose_name='Annual Revenue')),
                ('has_buying_decision', models.BooleanField(default=True, help_text='Indicates if this account has authority to make buying decisions', verbose_name='Has Buying Decision')),
                ('account_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_company_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Account Owner')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_child_companies', to='module_accounts.companyaccount', verbose_name='Parent Company')),
                ('partners', models.ManyToManyField(blank=True, related_name='partnered_with', to='module_accounts.companyaccount', verbose_name='Partners')),
                ('team_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_company_accounts', to='end_users.team', verbose_name='Team Owner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Company Account',
                'verbose_name_plural': 'Company Accounts',
                'db_table': 'module_company_accounts',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['account_owner'], name='mod_acc_owner_idx'), models.Index(fields=['team_owner'], name='mod_acc_team_idx'), models.Index(fields=['type'], name='mod_acc_type_idx')],
                'unique_together': {('company_name', 'city', 'country', 'client_id')},
            },
        ),
    ]
