# Generated by Django 5.1.4 on 2025-12-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companyaccount',
            name='mod_acc_team_idx',
        ),
        migrations.RemoveField(
            model_name='companyaccount',
            name='team_owner',
        ),
    ]
