# Generated by Django 5.1.4 on 2025-12-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_accounts', '0002_remove_companyaccount_mod_acc_team_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='industry',
            field=models.CharField(blank=True, choices=[('AGRICULTURE', 'Agriculture'), ('FISHING', 'Fishing & Aquaculture'), ('FORESTRY', 'Forestry & Logging'), ('MINING', 'Mining & Quarrying'), ('OIL_GAS', 'Oil & Gas'), ('UTILITIES', 'Utilities (Water, Electricity, Gas)'), ('CONSTRUCTION', 'Construction'), ('REAL_ESTATE', 'Real Estate & Property Management'), ('ARCHITECTURE', 'Architecture & Planning'), ('ENGINEERING', 'Engineering & Design Services'), ('MANUFACTURING', 'Manufacturing'), ('AUTOMOTIVE', 'Automotive Manufacturing'), ('AEROSPACE', 'Aerospace & Defense'), ('CHEMICALS', 'Chemicals'), ('PHARMACEUTICALS', 'Pharmaceuticals'), ('BIOTECHNOLOGY', 'Biotechnology'), ('FOOD_BEVERAGE', 'Food & Beverage Manufacturing'), ('TEXTILES', 'Textiles & Apparel'), ('ELECTRONICS', 'Electronics & Semiconductors'), ('WHOLESALE', 'Wholesale Trade'), ('RETAIL', 'Retail'), ('ECOMMERCE', 'E-commerce'), ('TRANSPORTATION', 'Transportation & Logistics'), ('WAREHOUSING', 'Warehousing'), ('SHIPPING', 'Shipping & Maritime'), ('AVIATION', 'Aviation'), ('INFORMATION_TECHNOLOGY', 'Information Technology'), ('SOFTWARE', 'Software Development'), ('SAAS', 'Software as a Service'), ('HARDWARE', 'Hardware & Devices'), ('CYBERSECURITY', 'Cybersecurity'), ('IT_SERVICES', 'IT Services & Consulting'), ('TELECOMMUNICATIONS', 'Telecommunications'), ('MEDIA', 'Media & Broadcasting'), ('ENTERTAINMENT', 'Entertainment'), ('GAMING', 'Gaming'), ('FINANCIAL_SERVICES', 'Financial Services'), ('BANKING', 'Banking'), ('INSURANCE', 'Insurance'), ('INVESTMENT', 'Investment Management'), ('FINTECH', 'Fintech'), ('HEALTHCARE', 'Healthcare Services'), ('HOSPITALS', 'Hospitals'), ('MEDICAL_DEVICES', 'Medical Devices'), ('WELLNESS', 'Wellness & Fitness'), ('EDUCATION', 'Education'), ('EDTECH', 'EdTech'), ('RESEARCH', 'Research & Development'), ('PUBLIC_SECTOR', 'Public Sector'), ('GOVERNMENT', 'Government'), ('DEFENSE', 'Defense & Security'), ('NONPROFIT', 'Nonprofit & NGOs'), ('RELIGIOUS', 'Religious Organizations'), ('HOSPITALITY', 'Hospitality'), ('TRAVEL_TOURISM', 'Travel & Tourism'), ('RESTAURANTS', 'Restaurants & Food Services'), ('ARTS_CULTURE', 'Arts & Culture'), ('SPORTS', 'Sports & Recreation'), ('EVENTS', 'Events & Exhibitions'), ('PROFESSIONAL_SERVICES', 'Professional Services'), ('LEGAL', 'Legal Services'), ('ACCOUNTING', 'Accounting'), ('CONSULTING', 'Consulting'), ('MARKETING', 'Marketing & Advertising'), ('HR', 'Human Resources'), ('RECRUITING', 'Recruiting & Staffing'), ('ENVIRONMENT', 'Environmental Services'), ('WASTE_MANAGEMENT', 'Waste Management'), ('RENEWABLE_ENERGY', 'Renewable Energy'), ('OTHER', 'Other')], max_length=100, null=True, verbose_name='Industry'),
        ),
    ]
