# Generated by Django 5.1.14 on 2026-07-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_accounts", "0003_alter_companyaccount_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyaccount",
            name="became_client_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp of the PROSPECT -> CLIENT conversion, set by the system on the first won decision cycle. Never set for accounts imported as CLIENT (they are not new logos). System-managed: not editable.",
                null=True,
                verbose_name="Became Client At",
            ),
        ),
    ]
