# Generated by Django 5.1.4 on 2025-06-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_account_email_is_valid_account_phone_is_valid_and_more'),
        ('end_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('name', models.CharField(max_length=100, verbose_name='Campaign Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('campaign_type', models.CharField(choices=[('HUNTING', 'New Account Hunting'), ('UPSELL', 'Existing Account Upsell'), ('FOLLOW_UP', 'Opportunity Follow-up'), ('RENEWAL', 'Contract Renewal'), ('CHASING', 'Chasing'), ('CALL_LIST', 'Call List'), ('LEAD_NURTURE', 'Lead Nurturing'), ('CUSTOM', 'Custom Campaign')], max_length=20, verbose_name='Campaign Type')),
                ('sequence_type', models.CharField(blank=True, choices=[('CHASING', 'Chasing'), ('RENEWAL', 'Contract Renewal'), ('FOLLOW_UP', 'Opportunity Follow-up')], default=None, help_text='Leave empty for campaigns without automated sequences (e.g., call lists)', max_length=30, null=True, verbose_name='Sequence Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_campaigns', to='end_users.user', verbose_name='Campaign Owner (Legacy)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='CampaignObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('name', models.CharField(max_length=100, verbose_name='Objective Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('objective_type', models.CharField(choices=[('LEADS', 'Number of Leads'), ('MEETINGS', 'Number of Meetings'), ('OPPORTUNITIES', 'Number of Opportunities'), ('PIPELINE_VALUE', 'Pipeline Value'), ('CLOSED_DEALS', 'Closed Deals'), ('REVENUE', 'Revenue'), ('CUSTOM', 'Custom Objective')], max_length=30, verbose_name='Objective Type')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Target Value')),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Current Value')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit of Measurement')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is Primary Objective')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='campaign.campaign', verbose_name='Campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Campaign Objective',
                'verbose_name_plural': 'Campaign Objectives',
            },
        ),
        migrations.CreateModel(
            name='CampaignStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('role', models.CharField(choices=[('OWNER', 'Campaign Owner'), ('EXECUTOR', 'Executor'), ('RECEIVER', 'Receiver '), ('OBSERVER', 'Observer')], default='OBSERVER', max_length=20, verbose_name='Role')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='end_users.user', verbose_name='Added By')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_links', to='campaign.campaign', verbose_name='Campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_roles', to='end_users.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Campaign Stakeholder',
                'verbose_name_plural': 'Campaign Stakeholders',
                'ordering': ['campaign', 'role'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='stakeholders',
            field=models.ManyToManyField(related_name='participated_campaigns', through='campaign.CampaignStakeholder', to='end_users.user', verbose_name='Stakeholders'),
        ),
        migrations.CreateModel(
            name='CampaignTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('MEETING_SECURED', 'Meeting Secured'), ('OPPORTUNITY_CREATED', 'Opportunity Created'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=30, verbose_name='Status')),
                ('sequence_created', models.BooleanField(default=False, verbose_name='Sequence Created')),
                ('expected_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Expected Value')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_targets', to='accounts.account', verbose_name='Target Account')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='campaign.campaign', verbose_name='Campaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_targets', to='accounts.contact', verbose_name='Target Contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Campaign Target',
                'verbose_name_plural': 'Campaign Targets',
            },
        ),
    ]
