# Generated by Django 5.1.4 on 2025-05-26 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_account_email_is_valid_account_phone_is_valid_and_more'),
        ('end_users', '0001_initial'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('name', models.CharField(max_length=100, verbose_name='Campaign Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('campaign_type', models.CharField(choices=[('HUNTING', 'New Account Hunting'), ('UPSELL', 'Existing Account Upsell'), ('FOLLOW_UP', 'Opportunity Follow-up'), ('RENEWAL', 'Contract Renewal'), ('CHASING', 'Chasing'), ('CUSTOM', 'Custom Campaign')], max_length=20, verbose_name='Campaign Type')),
                ('sequence_type', models.CharField(choices=[('CHASING', 'Chasing'), ('RENEWAL', 'Contract Renewal'), ('FOLLOW_UP', 'Opportunity Follow-up')], default='CHASING', max_length=30, verbose_name='Sequence Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_campaigns', to='end_users.user', verbose_name='Campaign Owner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='CampaignObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('name', models.CharField(max_length=100, verbose_name='Objective Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('objective_type', models.CharField(choices=[('LEADS', 'Number of Leads'), ('MEETINGS', 'Number of Meetings'), ('OPPORTUNITIES', 'Number of Opportunities'), ('PIPELINE_VALUE', 'Pipeline Value'), ('CLOSED_DEALS', 'Closed Deals'), ('REVENUE', 'Revenue'), ('CUSTOM', 'Custom Objective')], max_length=30, verbose_name='Objective Type')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Target Value')),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Current Value')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit of Measurement')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is Primary Objective')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='campaign.campaign', verbose_name='Campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Campaign Objective',
                'verbose_name_plural': 'Campaign Objectives',
            },
        ),
        migrations.CreateModel(
            name='CampaignTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('MEETING_SECURED', 'Meeting Secured'), ('OPPORTUNITY_CREATED', 'Opportunity Created'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=30, verbose_name='Status')),
                ('sequence_created', models.BooleanField(default=False, verbose_name='Sequence Created')),
                ('expected_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Expected Value')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_targets', to='accounts.account', verbose_name='Target Account')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='campaign.campaign', verbose_name='Campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_targets', to='opportunities.opportunity', verbose_name='Linked Opportunity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Campaign Target',
                'verbose_name_plural': 'Campaign Targets',
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['owner', 'start_date'], name='campaign_ca_owner_i_e14d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type'], name='campaign_ca_campaig_8a9cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignobjective',
            index=models.Index(fields=['campaign', 'objective_type'], name='campaign_ca_campaig_8403af_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignobjective',
            index=models.Index(fields=['is_primary'], name='campaign_ca_is_prim_a3bc9f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['campaign', 'status'], name='campaign_ca_campaig_a1b4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['account', 'status'], name='campaign_ca_account_9da3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['sequence_created'], name='campaign_ca_sequenc_d876c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigntarget',
            unique_together={('campaign', 'account')},
        ),
    ]
