# Generated by Django 5.1.4 on 2025-05-07 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
        ('end_users', '0001_initial'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntarget',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_targets', to='opportunities.opportunity', verbose_name='Linked Opportunity'),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['owner', 'start_date'], name='campaign_ca_owner_i_e14d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type'], name='campaign_ca_campaig_8a9cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignobjective',
            index=models.Index(fields=['campaign', 'objective_type'], name='campaign_ca_campaig_8403af_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignobjective',
            index=models.Index(fields=['is_primary'], name='campaign_ca_is_prim_a3bc9f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['campaign', 'status'], name='campaign_ca_campaig_a1b4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['account', 'status'], name='campaign_ca_account_9da3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['sequence_created'], name='campaign_ca_sequenc_d876c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigntarget',
            unique_together={('campaign', 'account')},
        ),
    ]
