# Generated by Django 5.1.4 on 2025-06-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0002_initial'),
        ('end_users', '0001_initial'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntarget',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_targets', to='opportunities.opportunity', verbose_name='Linked Opportunity'),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By'),
        ),
        migrations.AddIndex(
            model_name='campaignobjective',
            index=models.Index(fields=['campaign', 'objective_type'], name='campaign_ca_campaig_8403af_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignobjective',
            index=models.Index(fields=['is_primary'], name='campaign_ca_is_prim_a3bc9f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignstakeholder',
            index=models.Index(fields=['campaign', 'role'], name='campaign_ca_campaig_e71aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignstakeholder',
            index=models.Index(fields=['user', 'role'], name='campaign_ca_user_id_0f0b47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignstakeholder',
            unique_together={('campaign', 'user', 'role', 'client_id')},
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['owner', 'start_date'], name='campaign_ca_owner_i_e14d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type'], name='campaign_ca_campaig_8a9cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['sequence_type'], name='campaign_ca_sequenc_da1713_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['campaign', 'status'], name='campaign_ca_campaig_a1b4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['account', 'status'], name='campaign_ca_account_9da3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['contact', 'status'], name='campaign_ca_contact_19270c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['lead', 'status'], name='campaign_ca_lead_id_86a88b_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['sequence_created'], name='campaign_ca_sequenc_d876c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaigntarget',
            constraint=models.UniqueConstraint(condition=models.Q(('contact__isnull', True), ('lead__isnull', True)), fields=('campaign', 'account'), name='unique_campaign_account_only'),
        ),
        migrations.AddConstraint(
            model_name='campaigntarget',
            constraint=models.UniqueConstraint(condition=models.Q(('contact__isnull', False)), fields=('campaign', 'contact'), name='unique_campaign_contact'),
        ),
        migrations.AddConstraint(
            model_name='campaigntarget',
            constraint=models.UniqueConstraint(condition=models.Q(('lead__isnull', False)), fields=('campaign', 'lead'), name='unique_campaign_lead'),
        ),
    ]
