# Generated by Django 5.1.4 on 2025-06-05 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_email_is_valid_account_phone_is_valid_and_more'),
        ('campaign', '0003_initial'),
        ('end_users', '0001_initial'),
        ('leads', '0002_initial'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='campaigntarget',
            name='unique_campaign_account_only',
        ),
        migrations.RemoveIndex(
            model_name='campaigntarget',
            name='campaign_ca_sequenc_d876c4_idx',
        ),
        migrations.RemoveField(
            model_name='campaigntarget',
            name='expected_value',
        ),
        migrations.RemoveField(
            model_name='campaigntarget',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='campaigntarget',
            name='sequence_created',
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='activities_generated',
            field=models.BooleanField(default=False, verbose_name='Activities Generated'),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='linked_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_campaign_targets', to='opportunities.opportunity', verbose_name='Linked Opportunity'),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='target_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_by_campaigns', to='opportunities.opportunity', verbose_name='Target Opportunity'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['target_opportunity', 'status'], name='campaign_ca_target__a22df2_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['activities_generated'], name='campaign_ca_activit_737e45_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaigntarget',
            constraint=models.UniqueConstraint(condition=models.Q(('contact__isnull', True), ('lead__isnull', True), ('target_opportunity__isnull', True)), fields=('campaign', 'account'), name='unique_campaign_account_only'),
        ),
        migrations.AddConstraint(
            model_name='campaigntarget',
            constraint=models.UniqueConstraint(condition=models.Q(('target_opportunity__isnull', False)), fields=('campaign', 'target_opportunity'), name='unique_campaign_opportunity'),
        ),
    ]
