# Generated by Django 5.1.4 on 2025-06-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_remove_campaigntarget_unique_campaign_account_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntarget',
            name='callback_date',
            field=models.DateField(blank=True, help_text='Date when contact requested to be called back', null=True, verbose_name='Callback Date'),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='no_answer_count',
            field=models.IntegerField(default=0, help_text='Number of times contact did not answer', verbose_name='No Answer Count'),
        ),
        migrations.AlterField(
            model_name='campaigntarget',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('CALLBACK_PENDING', 'Callback Pending'), ('MEETING_SECURED', 'Meeting Secured'), ('OPPORTUNITY_CREATED', 'Opportunity Created'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=30, verbose_name='Status'),
        ),
    ]
