# Generated by Django 5.1.4 on 2025-06-18 11:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_campaigntarget_callback_date_and_more'),
        ('end_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignResultTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('leads_created_count', models.IntegerField(default=0, help_text='Number of leads generated by this campaign', verbose_name='Leads Created Count')),
                ('meetings_secured_count', models.IntegerField(default=0, help_text='Number of meetings scheduled through this campaign', verbose_name='Meetings Secured Count')),
                ('opportunities_created_count', models.IntegerField(default=0, help_text='Number of opportunities created from this campaign', verbose_name='Opportunities Created Count')),
                ('deals_closed_count', models.IntegerField(default=0, help_text='Number of deals closed from this campaign', verbose_name='Deals Closed Count')),
                ('pipeline_value_created', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total pipeline value generated by this campaign', max_digits=15, verbose_name='Pipeline Value Created')),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue closed from this campaign', max_digits=15, verbose_name='Revenue Generated')),
                ('tracked_lead_ids', models.JSONField(default=list, help_text='List of lead IDs generated by this campaign for integrity checking', verbose_name='Tracked Lead IDs')),
                ('tracked_meeting_ids', models.JSONField(default=list, help_text='List of meeting activity IDs secured by this campaign', verbose_name='Tracked Meeting IDs')),
                ('tracked_opportunity_ids', models.JSONField(default=list, help_text='List of opportunity IDs created by this campaign', verbose_name='Tracked Opportunity IDs')),
                ('tracked_deal_ids', models.JSONField(default=list, help_text='List of opportunity IDs that closed as deals from this campaign', verbose_name='Tracked Deal IDs')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When these metrics were last updated', verbose_name='Last Updated')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_tracking', to='campaign.campaign', verbose_name='Campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Campaign Result Tracking',
                'verbose_name_plural': 'Campaign Result Trackings',
                'indexes': [models.Index(fields=['campaign'], name='campaign_ca_campaig_b6e7ba_idx'), models.Index(fields=['last_updated'], name='campaign_ca_last_up_afe5be_idx')],
            },
        ),
    ]
