# Generated by Django 5.1.4 on 2025-06-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_campaignresulttracking'),
        ('end_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaignobjective',
            name='campaign_ca_campaig_8403af_idx',
        ),
        migrations.RemoveIndex(
            model_name='campaignobjective',
            name='campaign_ca_is_prim_a3bc9f_idx',
        ),
        migrations.RemoveField(
            model_name='campaignobjective',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='campaignobjective',
            name='description',
        ),
        migrations.RemoveField(
            model_name='campaignobjective',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='campaignobjective',
            name='objective_type',
            field=models.CharField(choices=[('LEADS', 'Number of Leads'), ('MEETINGS', 'Number of Meetings'), ('OPPORTUNITIES', 'Number of Opportunities'), ('PIPELINE_VALUE', 'Pipeline Value'), ('CLOSED_DEALS', 'Closed Deals'), ('REVENUE', 'Revenue')], max_length=30, verbose_name='Objective Type'),
        ),
        migrations.AddIndex(
            model_name='campaignobjective',
            index=models.Index(fields=['campaign', 'is_primary'], name='campaign_ca_campaig_0fbc58_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignobjective',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('campaign',), name='unique_primary_objective_per_campaign'),
        ),
    ]
