# Generated by Django 5.1.4 on 2025-06-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_remove_campaignobjective_campaign_ca_campaig_8403af_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntarget',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('CALLBACK_PENDING', 'Callback Pending'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=30, verbose_name='Status'),
        ),
    ]
