# Generated by Django 5.1.4 on 2025-06-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_alter_campaigntarget_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaign_ca_campaig_8a9cbd_idx',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_type',
        ),
    ]
