# Generated by Django 5.1.4 on 2025-07-11 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_email_is_valid_account_phone_is_valid_and_more'),
        ('campaign', '0009_remove_campaign_campaign_ca_campaig_8a9cbd_idx_and_more'),
        ('leads', '0002_initial'),
        ('opportunities', '0003_substageactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntarget',
            name='substage',
            field=models.ForeignKey(blank=True, help_text='Pipeline substage that generated this campaign target', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_targets', to='opportunities.pipelinesubstage', verbose_name='Source SubStage'),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='substage_context',
            field=models.JSONField(blank=True, default=dict, help_text='Additional context from substage (stakeholders, criteria, etc.)', verbose_name='SubStage Context'),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='substage_objective',
            field=models.TextField(blank=True, help_text='Objective copied from substage metadata for quick access', null=True, verbose_name='SubStage Objective'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['substage', 'status'], name='campaign_ca_substag_d8f93a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntarget',
            index=models.Index(fields=['campaign', 'substage'], name='campaign_ca_campaig_661200_idx'),
        ),
    ]
