# Generated by Django 5.1.4 on 2025-07-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_campaigntarget_substage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='sequence_type',
            field=models.CharField(blank=True, choices=[('CHASING', 'Chasing'), ('RENEWAL', 'Contract Renewal'), ('FOLLOW_UP', 'Follow-up')], default=None, help_text='Leave empty for campaigns without automated sequences (e.g., call lists)', max_length=30, null=True, verbose_name='Sequence Type'),
        ),
    ]
