# Generated by Django 5.1.4 on 2026-04-06 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_modules', '0001_initial'),
        ('decision_cycles', '0012_decisioncycle_source_campaign'),
        ('module_accounts', '0003_alter_companyaccount_industry'),
        ('module_activities', '0017_activity_source_decision_cycle'),
        ('module_campaigns', '0014_campaign_channel_override'),
        ('module_contacts', '0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('value', models.JSONField(help_text='Structured signal data — format depends on field_name', verbose_name='Value')),
                ('source_quote', models.TextField(blank=True, help_text='Exact excerpt from the transcript that supports this signal, preserved in its original language', null=True, verbose_name='Source Quote')),
                ('confidence', models.FloatField(blank=True, help_text='LLM confidence score (0.0–1.0). Null for manually entered signals.', null=True, verbose_name='Confidence')),
                ('is_inferred', models.BooleanField(default=False, help_text='False = verbatim from transcript. True = deduced / inferred by LLM.', verbose_name='Is Inferred')),
                ('signal_category', models.CharField(blank=True, choices=[('ECONOMIC', 'Economic'), ('TIME', 'Time'), ('FRICTION', 'Friction'), ('RISK', 'Risk'), ('STRATEGIC', 'Strategic'), ('PEOPLE', 'People'), ('PROCESS', 'Process')], help_text='High-level commercial category of the signal', max_length=20, null=True, verbose_name='Signal Category')),
                ('metadata', models.JSONField(blank=True, help_text='Flexible storage for merge history, LLM context, etc.', null=True, verbose_name='Metadata')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual entry'), ('LLM_EXTRACTED', 'LLM extracted'), ('LLM_MODIFIED', 'LLM modified')], default='MANUAL', help_text='How the signal was created (manual entry vs. LLM)', max_length=20, verbose_name='Source')),
                ('language_original', models.CharField(blank=True, help_text='BCP-47 language tag of the source transcript (e.g. "fr", "en-US")', max_length=10, null=True, verbose_name='Original Language')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('MERGED', 'Merged')], default='PENDING', help_text='PENDING = awaiting rep validation (LLM signals). VALIDATED = approved (manual signals start here). REJECTED = dismissed. MERGED = absorbed into another signal.', max_length=20, verbose_name='Status')),
                ('validated_at', models.DateTimeField(blank=True, help_text='When the signal was validated (was approved_at in legacy)', null=True, verbose_name='Validated At')),
                ('confirmation_count', models.PositiveIntegerField(default=1, help_text='Number of times this signal has been independently confirmed', verbose_name='Confirmation Count')),
                ('last_confirmed_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Confirmed At')),
                ('is_superseded', models.BooleanField(default=False, help_text='True when a newer signal for the same field has replaced this one', verbose_name='Is Superseded')),
                ('last_modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Modified At')),
                ('original_value', models.JSONField(blank=True, help_text='Snapshot of value before the first manual edit. Null for signals that have never been edited.', null=True, verbose_name='Original Value')),
                ('field_name', models.CharField(choices=[('decision_maker', 'Decision Maker'), ('economic_buyer', 'Economic Buyer'), ('champion', 'Champion'), ('blocker', 'Blocker'), ('end_user', 'End User'), ('procurement_contact', 'Procurement Contact'), ('internal_dynamics', 'Internal Dynamics'), ('pain_point', 'Pain Point'), ('pain_origin', 'Pain Origin'), ('pain_impact', 'Pain Impact'), ('pain_consequence', 'Pain Consequence'), ('pain_measurement', 'Pain Measurement'), ('business_cost', 'Business Cost'), ('pain_maturity', 'Pain Maturity'), ('existing_initiative', 'Existing Initiative'), ('resolution_value', 'Resolution Value'), ('current_tool', 'Current Tool'), ('current_process', 'Current Process'), ('existing_integrations', 'Existing Integrations'), ('known_limitations', 'Known Limitations'), ('satisfaction_level', 'Satisfaction Level'), ('workaround', 'Workaround'), ('buying_stakeholders', 'Buying Stakeholders'), ('decision_criteria', 'Decision Criteria'), ('buying_process', 'Buying Process'), ('timeline', 'Timeline'), ('deal_risk', 'Deal Risk'), ('company_size', 'Company Size'), ('annual_revenue', 'Annual Revenue')], help_text='Identifies which qualification dimension this signal captures. Must be one of the QualificationField choices.', max_length=50, verbose_name='Qualification Field')),
                ('account', models.ForeignKey(help_text='Account this signal belongs to — required', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_signals', to='module_accounts.companyaccount', verbose_name='Account')),
                ('campaign', models.ForeignKey(blank=True, help_text='Campaign this signal is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_signals', to='module_campaigns.campaign', verbose_name='Campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('decision_cycle', models.ForeignKey(blank=True, help_text='Decision cycle this signal is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_signals', to='decision_cycles.decisioncycle', verbose_name='Decision Cycle')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last edited the signal value after creation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('merged_into', models.ForeignKey(blank=True, help_text='Surviving signal when this one was merged (status=MERGED)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='module_signals.qualificationsignal', verbose_name='Merged Into')),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who triggered the LLM extraction (null for manual signals)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_requested', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('source_activity', models.ForeignKey(blank=True, help_text='Activity (call/meeting) from which this signal was extracted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_signals', to='module_activities.activity', verbose_name='Source Activity')),
                ('source_contact', models.ForeignKey(blank=True, help_text='Contact who provided or confirmed this signal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_signals', to='module_contacts.contact', verbose_name='Source Contact')),
                ('source_department', models.ForeignKey(blank=True, help_text='Department this signal originates from. Auto-populated from source_contact.standard_department if not set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_signals', to='core_modules.standarddepartment', verbose_name='Source Department')),
                ('superseded_by', models.ForeignKey(blank=True, help_text='Signal that replaced this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='module_signals.qualificationsignal', verbose_name='Superseded By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('validated_by', models.ForeignKey(blank=True, help_text='Rep who validated this signal (was approved_by in legacy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validated By')),
            ],
            options={
                'verbose_name': 'Qualification Signal',
                'verbose_name_plural': 'Qualification Signals',
                'db_table': 'module_signals_qualification',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['account'], name='qsig_account_idx'), models.Index(fields=['status'], name='qsig_status_idx'), models.Index(fields=['signal_category'], name='qsig_category_idx'), models.Index(fields=['source_department'], name='qsig_department_idx'), models.Index(fields=['source'], name='qsig_source_idx')],
            },
        ),
        migrations.CreateModel(
            name='TechStackSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('value', models.JSONField(help_text='Structured signal data — format depends on field_name', verbose_name='Value')),
                ('source_quote', models.TextField(blank=True, help_text='Exact excerpt from the transcript that supports this signal, preserved in its original language', null=True, verbose_name='Source Quote')),
                ('confidence', models.FloatField(blank=True, help_text='LLM confidence score (0.0–1.0). Null for manually entered signals.', null=True, verbose_name='Confidence')),
                ('is_inferred', models.BooleanField(default=False, help_text='False = verbatim from transcript. True = deduced / inferred by LLM.', verbose_name='Is Inferred')),
                ('signal_category', models.CharField(blank=True, choices=[('ECONOMIC', 'Economic'), ('TIME', 'Time'), ('FRICTION', 'Friction'), ('RISK', 'Risk'), ('STRATEGIC', 'Strategic'), ('PEOPLE', 'People'), ('PROCESS', 'Process')], help_text='High-level commercial category of the signal', max_length=20, null=True, verbose_name='Signal Category')),
                ('metadata', models.JSONField(blank=True, help_text='Flexible storage for merge history, LLM context, etc.', null=True, verbose_name='Metadata')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual entry'), ('LLM_EXTRACTED', 'LLM extracted'), ('LLM_MODIFIED', 'LLM modified')], default='MANUAL', help_text='How the signal was created (manual entry vs. LLM)', max_length=20, verbose_name='Source')),
                ('language_original', models.CharField(blank=True, help_text='BCP-47 language tag of the source transcript (e.g. "fr", "en-US")', max_length=10, null=True, verbose_name='Original Language')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('MERGED', 'Merged')], default='PENDING', help_text='PENDING = awaiting rep validation (LLM signals). VALIDATED = approved (manual signals start here). REJECTED = dismissed. MERGED = absorbed into another signal.', max_length=20, verbose_name='Status')),
                ('validated_at', models.DateTimeField(blank=True, help_text='When the signal was validated (was approved_at in legacy)', null=True, verbose_name='Validated At')),
                ('confirmation_count', models.PositiveIntegerField(default=1, help_text='Number of times this signal has been independently confirmed', verbose_name='Confirmation Count')),
                ('last_confirmed_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Confirmed At')),
                ('is_superseded', models.BooleanField(default=False, help_text='True when a newer signal for the same field has replaced this one', verbose_name='Is Superseded')),
                ('last_modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Modified At')),
                ('original_value', models.JSONField(blank=True, help_text='Snapshot of value before the first manual edit. Null for signals that have never been edited.', null=True, verbose_name='Original Value')),
                ('field_name', models.CharField(choices=[('purpose', 'Purpose'), ('pros', 'Pros'), ('cons', 'Cons'), ('costs', 'Costs'), ('renewal_date', 'Renewal Date'), ('start_year_of_usage', 'Start Year of Usage')], help_text='Identifies which facet of the tool this signal captures (purpose, pros, cons, costs, renewal date, or start year).', max_length=50, verbose_name='Tech Stack Field')),
                ('tech_name', models.CharField(blank=True, help_text='Name of the tool as mentioned in the transcript. Free text — may not match a canonical entity. Empty when the tool name was not identifiable.', max_length=255, verbose_name='Tech Name')),
                ('account', models.ForeignKey(help_text='Account this signal belongs to — required', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_signals', to='module_accounts.companyaccount', verbose_name='Account')),
                ('campaign', models.ForeignKey(blank=True, help_text='Campaign this signal is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_signals', to='module_campaigns.campaign', verbose_name='Campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('decision_cycle', models.ForeignKey(blank=True, help_text='Decision cycle this signal is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_signals', to='decision_cycles.decisioncycle', verbose_name='Decision Cycle')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last edited the signal value after creation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('merged_into', models.ForeignKey(blank=True, help_text='Surviving signal when this one was merged (status=MERGED)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='module_signals.techstacksignal', verbose_name='Merged Into')),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who triggered the LLM extraction (null for manual signals)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_requested', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('source_activity', models.ForeignKey(blank=True, help_text='Activity (call/meeting) from which this signal was extracted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_signals', to='module_activities.activity', verbose_name='Source Activity')),
                ('source_contact', models.ForeignKey(blank=True, help_text='Contact who provided or confirmed this signal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_signals', to='module_contacts.contact', verbose_name='Source Contact')),
                ('source_department', models.ForeignKey(blank=True, help_text='Department this signal originates from. Auto-populated from source_contact.standard_department if not set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_signals', to='core_modules.standarddepartment', verbose_name='Source Department')),
                ('superseded_by', models.ForeignKey(blank=True, help_text='Signal that replaced this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='module_signals.techstacksignal', verbose_name='Superseded By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('validated_by', models.ForeignKey(blank=True, help_text='Rep who validated this signal (was approved_by in legacy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validated By')),
            ],
            options={
                'verbose_name': 'Tech Stack Signal',
                'verbose_name_plural': 'Tech Stack Signals',
                'db_table': 'module_signals_tech_stack',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['account'], name='tsig_account_idx'), models.Index(fields=['status'], name='tsig_status_idx'), models.Index(fields=['signal_category'], name='tsig_category_idx'), models.Index(fields=['source_department'], name='tsig_department_idx'), models.Index(fields=['source'], name='tsig_source_idx')],
            },
        ),
    ]
