# Generated by Django 5.1.4 on 2026-04-21 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_modules', '0001_initial'),
        ('decision_cycles', '0012_decisioncycle_source_campaign'),
        ('module_accounts', '0003_alter_companyaccount_industry'),
        ('module_activities', '0017_activity_source_decision_cycle'),
        ('module_campaigns', '0014_campaign_channel_override'),
        ('module_contacts', '0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more'),
        ('module_signals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='painsignal',
            name='painsig_category_idx',
        ),
        migrations.RemoveField(
            model_name='painsignal',
            name='category',
        ),
        migrations.AddField(
            model_name='painsignal',
            name='dimension',
            field=models.CharField(choices=[('TIME', 'Time / Speed'), ('COST', 'Cost / Budget'), ('QUALITY', 'Quality / Accuracy'), ('SCALE', 'Scale / Capacity'), ('RISK', 'Risk / Compliance')], default='TIME', help_text='Friction axis of the pain (second component of canonical_key)', max_length=20, verbose_name='Dimension'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painsignal',
            name='human_impact',
            field=models.CharField(blank=True, choices=[('FRUSTRATION', 'Frustration'), ('OVERLOAD', 'Overload'), ('STRESS', 'Stress / Anxiety'), ('DEMOTIVATION', 'Demotivation'), ('CONFLICT', 'Conflict')], help_text='Personal consequence on an individual contact. Independent from pain_level — a BUSINESS-level pain can still carry a human impact on one person. When set, impacted_contact is required.', max_length=20, null=True, verbose_name='Human Impact'),
        ),
        migrations.AddField(
            model_name='painsignal',
            name='impacted_contact',
            field=models.ForeignKey(blank=True, help_text='Contact personally affected by this pain. Required when pain_level = PERSONAL or when human_impact is set. May differ from source_contact (e.g. a VP reports a pain that impacts Marie).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impacted_pain_signals', to='module_contacts.contact', verbose_name='Impacted Contact'),
        ),
        migrations.AddField(
            model_name='painsignal',
            name='what',
            field=models.CharField(choices=[('OPS', 'Operations / Process'), ('TECH', 'Technology / System'), ('DATA', 'Data / Visibility'), ('PEOPLE', 'People / Org'), ('GROWTH', 'Growth / Revenue')], default='DATA', help_text='Domain axis of the pain (first component of canonical_key)', max_length=20, verbose_name='What'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='painsignal',
            name='business_cost',
            field=models.TextField(blank=True, help_text='Quantified metric of the pain mentioned during the conversation (e.g. "2h/day wasted", "$10k/year overspent"). Free text.', verbose_name='Metric / Measurement'),
        ),
        migrations.AlterField(
            model_name='painsignal',
            name='impacted_department',
            field=models.ForeignKey(blank=True, help_text='Department structurally affected by this pain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impacted_pain_signals', to='core_modules.standarddepartment', verbose_name='Impacted Department'),
        ),
        migrations.AddIndex(
            model_name='painsignal',
            index=models.Index(fields=['what'], name='painsig_what_idx'),
        ),
        migrations.AddIndex(
            model_name='painsignal',
            index=models.Index(fields=['dimension'], name='painsig_dimension_idx'),
        ),
        migrations.AddIndex(
            model_name='painsignal',
            index=models.Index(fields=['human_impact'], name='painsig_human_impact_idx'),
        ),
        migrations.AddIndex(
            model_name='painsignal',
            index=models.Index(fields=['account', 'canonical_key'], name='painsig_account_canon_idx'),
        ),
    ]
