# Generated by Django 5.1.4 on 2026-04-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_signals', '0002_remove_painsignal_painsig_category_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='painsignal',
            name='painsig_pain_level_idx',
        ),
        migrations.RemoveIndex(
            model_name='painsignal',
            name='painsig_human_impact_idx',
        ),
        migrations.RemoveField(
            model_name='painsignal',
            name='business_cost',
        ),
        migrations.RemoveField(
            model_name='painsignal',
            name='human_impact',
        ),
        migrations.RemoveField(
            model_name='painsignal',
            name='impact_summary',
        ),
        migrations.RemoveField(
            model_name='painsignal',
            name='impacted_contact',
        ),
        migrations.RemoveField(
            model_name='painsignal',
            name='impacted_department',
        ),
        migrations.RemoveField(
            model_name='painsignal',
            name='pain_level',
        ),
        migrations.AlterField(
            model_name='painsignal',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional qualitative context about this pain', verbose_name='Notes'),
        ),
    ]
