# Generated by Django 5.1.4 on 2026-04-21 13:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_modules', '0001_initial'),
        ('module_contacts', '0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more'),
        ('module_signals', '0003_remove_painsignal_painsig_pain_level_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PainImpact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('level', models.CharField(choices=[('BUSINESS', 'Business'), ('DEPARTMENT', 'Department'), ('PERSONAL', 'Personal')], help_text='The scope of this impact: BUSINESS (company-wide), DEPARTMENT (scoped to one department), or PERSONAL (scoped to one individual contact).', max_length=20, verbose_name='Impact Level')),
                ('human_impact', models.CharField(blank=True, choices=[('FRUSTRATION', 'Frustration'), ('OVERLOAD', 'Overload'), ('STRESS', 'Stress / Anxiety'), ('DEMOTIVATION', 'Demotivation'), ('CONFLICT', 'Conflict')], help_text='Personal consequence on the impacted contact — frustration, overload, stress, demotivation, conflict. Optional, and only meaningful on PERSONAL impacts.', max_length=20, null=True, verbose_name='Human Impact')),
                ('metric', models.TextField(blank=True, help_text='Quantified evidence of the impact as mentioned during the conversation. Free text — e.g. "120k$/year lost productivity", "15h/week wasted", "3h/week overtime". Optional.', verbose_name='Metric / Measurement')),
                ('notes', models.TextField(blank=True, help_text='Additional qualitative context about this impact.', verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('impacted_contact', models.ForeignKey(blank=True, help_text="Contact personally experiencing this impact. Required when level=PERSONAL; must be null for BUSINESS and DEPARTMENT impacts. Must belong to the parent Pain's account.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pain_impacts', to='module_contacts.contact', verbose_name='Impacted Contact')),
                ('impacted_department', models.ForeignKey(blank=True, help_text='Department bearing this impact. Required when level=DEPARTMENT; must be null for BUSINESS and PERSONAL impacts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pain_impacts', to='core_modules.standarddepartment', verbose_name='Impacted Department')),
                ('pain_signal', models.ForeignKey(help_text='The PainSignal this impact documents — required.', on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='module_signals.painsignal', verbose_name='Pain Signal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Pain Impact',
                'verbose_name_plural': 'Pain Impacts',
                'db_table': 'module_signals_pain_impact',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['pain_signal'], name='painimp_pain_idx'), models.Index(fields=['level'], name='painimp_level_idx'), models.Index(fields=['impacted_department'], name='painimp_dept_idx'), models.Index(fields=['impacted_contact'], name='painimp_contact_idx'), models.Index(fields=['human_impact'], name='painimp_human_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('impacted_contact__isnull', False)), fields=('pain_signal', 'impacted_contact'), name='painimp_unique_pain_contact')],
            },
        ),
    ]
