# Generated by Django 5.1.4 on 2026-04-22 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_accounts', '0003_alter_companyaccount_industry'),
        ('module_signals', '0004_painimpact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalClusterArchival',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('signal_type', models.CharField(choices=[('pain', 'Pain'), ('people', 'People'), ('objective', 'Objective'), ('tech_stack', 'Tech Stack')], help_text="Signal family the cluster belongs to (e.g. 'pain'). Matches the type identifiers used by SignalDataService and the cluster endpoints.", max_length=20, verbose_name='Signal Type')),
                ('canonical_key', models.CharField(help_text="Stable cluster identifier — same value as BaseSignal.canonical_key on every member signal (e.g. 'pain:OPS:TIME').", max_length=255, verbose_name='Canonical Key')),
                ('unarchived_at', models.DateTimeField(blank=True, help_text='Set when the cluster is unarchived. NULL means the cluster is currently archived. Kept for audit — never deleted.', null=True, verbose_name='Unarchived At')),
                ('account', models.ForeignKey(help_text='Account whose cluster is archived.', on_delete=django.db.models.deletion.CASCADE, related_name='signal_cluster_archivals', to='module_accounts.companyaccount', verbose_name='Account')),
                ('archived_by', models.ForeignKey(blank=True, help_text='User who archived the cluster.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_cluster_archivals', to=settings.AUTH_USER_MODEL, verbose_name='Archived By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('unarchived_by', models.ForeignKey(blank=True, help_text='User who unarchived the cluster (null while archived).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_cluster_unarchivals', to=settings.AUTH_USER_MODEL, verbose_name='Unarchived By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Signal Cluster Archival',
                'verbose_name_plural': 'Signal Cluster Archivals',
                'db_table': 'module_signals_cluster_archival',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['account', 'signal_type', 'canonical_key'], name='sigclusarch_account_key_idx'), models.Index(fields=['unarchived_at'], name='sigclusarch_unarchived_at_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('unarchived_at__isnull', True)), fields=('client_id', 'account', 'signal_type', 'canonical_key'), name='sigclusarch_unique_active')],
            },
        ),
    ]
