# Generated by Django 5.1.4 on 2026-04-24 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_modules', '0001_initial'),
        ('decision_cycles', '0012_decisioncycle_source_campaign'),
        ('module_accounts', '0003_alter_companyaccount_industry'),
        ('module_activities', '0017_activity_source_decision_cycle'),
        ('module_campaigns', '0014_campaign_channel_override'),
        ('module_contacts', '0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more'),
        ('module_signals', '0006_refactor_objective_signal_wave_b'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('canonical_key', models.CharField(blank=True, db_index=True, help_text='Stable identifier used to group multiple observations of the same fact for corroboration. Auto-computed by concrete model save() for PeopleSignal and TechStackSignal. Set manually or by LLM for PainSignal and ObjectiveSignal.', max_length=255, null=True, verbose_name='Canonical Key')),
                ('source_quote', models.TextField(blank=True, help_text='Exact excerpt from the transcript that supports this signal, preserved in its original language', null=True, verbose_name='Source Quote')),
                ('confidence', models.FloatField(blank=True, help_text='LLM confidence score (0.0–1.0). Null for manually entered signals.', null=True, verbose_name='Confidence')),
                ('is_inferred', models.BooleanField(default=False, help_text='False = verbatim from transcript. True = deduced / inferred by LLM.', verbose_name='Is Inferred')),
                ('metadata', models.JSONField(blank=True, help_text='Flexible storage for merge history, LLM context, etc.', null=True, verbose_name='Metadata')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual entry'), ('LLM_EXTRACTED', 'LLM extracted'), ('LLM_MODIFIED', 'LLM modified'), ('EXTERNAL_RESEARCH', 'External research')], default='MANUAL', help_text='How the signal was created (manual entry vs. LLM)', max_length=20, verbose_name='Source')),
                ('language_original', models.CharField(blank=True, help_text='BCP-47 language tag of the source transcript (e.g. "fr", "en-US")', max_length=10, null=True, verbose_name='Original Language')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected')], default='PENDING', help_text='PENDING = awaiting rep validation (LLM signals). VALIDATED = approved (manual signals start here). REJECTED = dismissed. MERGED = absorbed into another signal.', max_length=20, verbose_name='Status')),
                ('validated_at', models.DateTimeField(blank=True, help_text='When the signal was validated (was approved_at in legacy)', null=True, verbose_name='Validated At')),
                ('last_modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Modified At')),
                ('original_value', models.JSONField(blank=True, help_text='Snapshot of value before the first manual edit. Null for signals that have never been edited.', null=True, verbose_name='Original Value')),
                ('what', models.CharField(choices=[('OPS', 'Operations / Process'), ('TECH', 'Technology / System'), ('DATA', 'Data / Visibility'), ('PEOPLE', 'People / Org'), ('GROWTH', 'Growth / Revenue')], help_text='Domain axis of the objective (first component of canonical_key)', max_length=20, verbose_name='What')),
                ('dimension', models.CharField(choices=[('TIME', 'Time / Speed'), ('COST', 'Cost / Budget'), ('QUALITY', 'Quality / Accuracy'), ('SCALE', 'Scale / Capacity'), ('RISK', 'Risk / Compliance')], help_text='Outcome axis of the objective (second component of canonical_key)', max_length=20, verbose_name='Dimension')),
                ('scope_level', models.CharField(choices=[('BUSINESS', 'Business'), ('DEPARTMENT', 'Department'), ('PERSONAL', 'Personal')], help_text='Organisational scope of the objective (BUSINESS / DEPARTMENT / PERSONAL)', max_length=20, verbose_name='Scope Level')),
                ('summary', models.TextField(help_text='The objective described in plain language (e.g. "Reduce onboarding time by 30%")', verbose_name='Summary')),
                ('success_criteria', models.TextField(blank=True, help_text='How success is defined — KPIs, thresholds, measurement method', verbose_name='Success Criteria')),
                ('target_date', models.DateField(blank=True, help_text='When this objective should be achieved', null=True, verbose_name='Target Date')),
                ('notes', models.TextField(blank=True, help_text='Additional qualitative context (source quotes, caveats, etc.)', verbose_name='Notes')),
                ('account', models.ForeignKey(help_text='Account this signal belongs to — required', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_signals', to='module_accounts.companyaccount', verbose_name='Account')),
                ('campaign', models.ForeignKey(blank=True, help_text='Campaign this signal is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_signals', to='module_campaigns.campaign', verbose_name='Campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('decision_cycle', models.ForeignKey(blank=True, help_text='Decision cycle this signal is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_signals', to='decision_cycles.decisioncycle', verbose_name='Decision Cycle')),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last edited the signal value after creation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who triggered the LLM extraction (null for manual signals)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_requested', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('source_activity', models.ForeignKey(blank=True, help_text='Activity (call/meeting) from which this signal was extracted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_signals', to='module_activities.activity', verbose_name='Source Activity')),
                ('source_contact', models.ForeignKey(blank=True, help_text='Contact who provided or confirmed this signal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_signals', to='module_contacts.contact', verbose_name='Source Contact')),
                ('source_department', models.ForeignKey(blank=True, help_text='Department this signal originates from. Auto-populated from source_contact.standard_department if not set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_signals', to='core_modules.standarddepartment', verbose_name='Source Department')),
                ('target_contact', models.ForeignKey(blank=True, help_text='Contact driving this objective — required when scope_level=PERSONAL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective_signals', to='module_contacts.contact', verbose_name='Target Contact')),
                ('target_department', models.ForeignKey(blank=True, help_text='Department driving this objective — required when scope_level=DEPARTMENT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective_signals', to='core_modules.standarddepartment', verbose_name='Target Department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('validated_by', models.ForeignKey(blank=True, help_text='Rep who validated this signal (was approved_by in legacy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validated By')),
            ],
            options={
                'verbose_name': 'Objective Signal',
                'verbose_name_plural': 'Objective Signals',
                'db_table': 'module_signals_objective',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['account'], name='objsig_account_idx'), models.Index(fields=['what'], name='objsig_what_idx'), models.Index(fields=['dimension'], name='objsig_dimension_idx'), models.Index(fields=['scope_level'], name='objsig_scope_level_idx'), models.Index(fields=['status'], name='objsig_status_idx'), models.Index(fields=['account', 'canonical_key'], name='objsig_account_canon_idx')],
            },
        ),
    ]
