# Generated by Django 5.1.4 on 2026-04-29 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_modules', '0001_initial'),
        ('decision_cycles', '0012_decisioncycle_source_campaign'),
        ('module_accounts', '0003_alter_companyaccount_industry'),
        ('module_activities', '0017_activity_source_decision_cycle'),
        ('module_campaigns', '0014_campaign_channel_override'),
        ('module_contacts', '0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more'),
        ('module_signals', '0008_techstack_canonical_refactor'),
        ('tech_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='painsignal',
            name='related_techstack',
            field=models.ForeignKey(blank=True, help_text='Optional structured cross-reference to a tool involved in this pain. Set when the rep can identify the tool against the tenant tech catalog. SET_NULL on catalog deletion — the pain itself remains valid, only the enriched cross-ref is lost.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_pain_signals', to='tech_catalog.techcatalog', verbose_name='Related TechStack'),
        ),
        migrations.AddField(
            model_name='painsignal',
            name='related_techstack_mention',
            field=models.CharField(blank=True, help_text='Free-text mention of a tool that could not be matched against the catalog (or whose match was deferred). Allows progressive enrichment: a textual mention can later be promoted to a structured FK once the catalog includes the tool.', max_length=200, verbose_name='Related TechStack Mention'),
        ),
        migrations.AlterField(
            model_name='techstacksignal',
            name='account',
            field=models.ForeignKey(help_text='Account this signal belongs to — required', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_signals', to='module_accounts.companyaccount', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='techstacksignal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='techstacksignal',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last edited the signal value after creation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AlterField(
            model_name='techstacksignal',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered the LLM extraction (null for manual signals)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_requested', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AlterField(
            model_name='techstacksignal',
            name='source_activity',
            field=models.ForeignKey(blank=True, help_text='Activity (call/meeting) from which this signal was extracted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_signals', to='module_activities.activity', verbose_name='Source Activity'),
        ),
        migrations.AlterField(
            model_name='techstacksignal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='techstacksignal',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='Rep who validated this signal (was approved_by in legacy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validated By'),
        ),
        migrations.AddIndex(
            model_name='painsignal',
            index=models.Index(fields=['account', 'related_techstack'], name='painsig_account_techref_idx'),
        ),
    ]
