# Generated by Django 5.1.4 on 2026-05-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_signals', '0010_backfill_signal_dc_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalclusterarchival',
            name='signal_type',
            field=models.CharField(choices=[('pain', 'Pain'), ('objective', 'Objective'), ('tech_stack', 'Tech Stack')], help_text="Signal family the cluster belongs to (e.g. 'pain'). Matches the type identifiers used by SignalDataService and the cluster endpoints.", max_length=20, verbose_name='Signal Type'),
        ),
        migrations.DeleteModel(
            name='PeopleSignal',
        ),
    ]
