# Generated by Django 5.1.4 on 2026-05-18 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_signals', '0012_drop_obsolete_source_and_audit_fields'),
        ('tech_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstacksignal',
            name='tech_catalog_entry',
            field=models.ForeignKey(blank=True, help_text='Tenant-level master catalog entry identifying the tool. Drives canonical_key and cluster identity. Required for MANUAL signals and required to validate any signal. May be NULL on PENDING LLM-extracted signals when the LLM could not match the mentioned tool to the catalog — the rep must attach a catalog entry (or create one) before validating. PROTECT semantics apply only when the FK is set.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tech_stack_signals', to='tech_catalog.techcatalog', verbose_name='Tech Catalog Entry'),
        ),
    ]
