# Generated by Django 5.2.15 on 2026-06-11 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_modules", "0001_initial"),
        ("decision_cycles", "0012_decisioncycle_source_campaign"),
        ("module_accounts", "0003_alter_companyaccount_industry"),
        ("module_activities", "0018_activity_next_step_signal"),
        ("module_campaigns", "0014_campaign_channel_override"),
        (
            "module_contacts",
            "0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more",
        ),
        ("module_signals", "0017_nextstepsignal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="impactsignal",
            name="target_department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department concerned by this impact. Purely descriptive — no conditional enforcement. Source (who speaks) ≠ concerned (the subject).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="impact_signals",
                to="core_modules.standarddepartment",
                verbose_name="Target Department",
            ),
        ),
        migrations.AddField(
            model_name="painsignal",
            name="target_department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department concerned by this pain. Purely descriptive — no conditional enforcement (unlike ObjectiveSignal). Source (who speaks) ≠ concerned (the subject): the CTO may report a pain felt by Marketing.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pain_signals",
                to="core_modules.standarddepartment",
                verbose_name="Target Department",
            ),
        ),
        migrations.AddField(
            model_name="techstacksignal",
            name="decision_cycle",
            field=models.ForeignKey(
                blank=True,
                help_text="Decision cycle this signal is associated with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_signals",
                to="decision_cycles.decisioncycle",
                verbose_name="Decision Cycle",
            ),
        ),
        migrations.CreateModel(
            name="ConstraintSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(
                        db_index=True,
                        editable=False,
                        help_text="ID of the client company this record belongs to",
                        verbose_name="Client ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "canonical_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable identifier used to group multiple observations of the same fact for corroboration. Auto-computed by concrete model save() for PeopleSignal and TechStackSignal. Set manually or by LLM for PainSignal and ObjectiveSignal.",
                        max_length=255,
                        null=True,
                        verbose_name="Canonical Key",
                    ),
                ),
                (
                    "source_quote",
                    models.TextField(
                        blank=True,
                        help_text="Exact excerpt from the transcript that supports this signal, preserved in its original language",
                        null=True,
                        verbose_name="Source Quote",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="LLM confidence score (0.0–1.0). Null for manually entered signals.",
                        null=True,
                        verbose_name="Confidence",
                    ),
                ),
                (
                    "is_inferred",
                    models.BooleanField(
                        default=False,
                        help_text="False = verbatim from transcript. True = deduced / inferred by LLM.",
                        verbose_name="Is Inferred",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Flexible storage for merge history, LLM context, etc.",
                        null=True,
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual entry"),
                            ("LLM_EXTRACTED", "LLM extracted"),
                            ("LLM_MODIFIED", "LLM modified"),
                            ("EXTERNAL_RESEARCH", "External research"),
                        ],
                        default="MANUAL",
                        help_text="How the signal was created (manual entry vs. LLM)",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "language_original",
                    models.CharField(
                        blank=True,
                        help_text='BCP-47 language tag of the source transcript (e.g. "fr", "en-US")',
                        max_length=10,
                        null=True,
                        verbose_name="Original Language",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VALIDATED", "Validated"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        help_text="PENDING = awaiting rep validation (LLM signals). VALIDATED = approved (manual signals start here). REJECTED = dismissed. MERGED = absorbed into another signal.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the signal was validated (was approved_at in legacy)",
                        null=True,
                        verbose_name="Validated At",
                    ),
                ),
                (
                    "original_value",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of value before the first manual edit. Null for signals that have never been edited.",
                        null=True,
                        verbose_name="Original Value",
                    ),
                ),
                (
                    "what",
                    models.CharField(
                        choices=[
                            ("OPS", "Operations / Process"),
                            ("TECH", "Technology / System"),
                            ("DATA", "Data / Visibility"),
                            ("PEOPLE", "People / Org"),
                            ("GROWTH", "Growth / Revenue"),
                        ],
                        help_text="Domain axis of the constraint (first component of canonical_key)",
                        max_length=20,
                        verbose_name="What",
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("TIME", "Time / Speed"),
                            ("COST", "Cost / Budget"),
                            ("QUALITY", "Quality / Accuracy"),
                            ("SCALE", "Scale / Capacity"),
                            ("RISK", "Risk / Compliance"),
                        ],
                        help_text="Friction axis of the constraint (second component of canonical_key)",
                        max_length=20,
                        verbose_name="Dimension",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Description of the constraint or decision criterion",
                        verbose_name="Summary",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional context about this constraint",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "rigidity",
                    models.CharField(
                        choices=[("FIRM", "Firm"), ("FLEXIBLE", "Flexible")],
                        help_text="Whether this constraint is non-negotiable (FIRM) or a preference (FLEXIBLE).",
                        max_length=20,
                        verbose_name="Rigidity",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Account this signal belongs to — required",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_signals",
                        to="module_accounts.companyaccount",
                        verbose_name="Account",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        help_text="Campaign this signal is associated with",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_signals",
                        to="module_campaigns.campaign",
                        verbose_name="Campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "decision_cycle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Decision cycle this signal is associated with",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_signals",
                        to="decision_cycles.decisioncycle",
                        verbose_name="Decision Cycle",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the LLM extraction (null for manual signals)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "source_activity",
                    models.ForeignKey(
                        blank=True,
                        help_text='Activity (call/meeting) from which this signal was extracted. Nullable + on_delete=SET_NULL is INTENTIONAL: a validated signal survives the deletion of its source conversation as an account-level observation. The "source_activity required at create" rule is enforced at the application layer — in concrete model clean() methods and in the Create serializers (see PainSignal.clean, BlockerSignal.clean, etc.) — never via a DB-level NOT NULL constraint, because durifying the column would contradict the SET_NULL deletion semantic.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_signals",
                        to="module_activities.activity",
                        verbose_name="Source Activity",
                    ),
                ),
                (
                    "target_department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department that owns or enforces this constraint. Purely descriptive — no conditional enforcement.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="constraint_signals",
                        to="core_modules.standarddepartment",
                        verbose_name="Target Department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Rep who validated this signal (was approved_by in legacy)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_validated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Constraint Signal",
                "verbose_name_plural": "Constraint Signals",
                "db_table": "module_signals_constraint",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["account"], name="constsig_account_idx"),
                    models.Index(fields=["what"], name="constsig_what_idx"),
                    models.Index(fields=["dimension"], name="constsig_dimension_idx"),
                    models.Index(fields=["status"], name="constsig_status_idx"),
                    models.Index(
                        fields=["account", "canonical_key"],
                        name="constsig_account_canon_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PeopleSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(
                        db_index=True,
                        editable=False,
                        help_text="ID of the client company this record belongs to",
                        verbose_name="Client ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "canonical_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable identifier used to group multiple observations of the same fact for corroboration. Auto-computed by concrete model save() for PeopleSignal and TechStackSignal. Set manually or by LLM for PainSignal and ObjectiveSignal.",
                        max_length=255,
                        null=True,
                        verbose_name="Canonical Key",
                    ),
                ),
                (
                    "source_quote",
                    models.TextField(
                        blank=True,
                        help_text="Exact excerpt from the transcript that supports this signal, preserved in its original language",
                        null=True,
                        verbose_name="Source Quote",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="LLM confidence score (0.0–1.0). Null for manually entered signals.",
                        null=True,
                        verbose_name="Confidence",
                    ),
                ),
                (
                    "is_inferred",
                    models.BooleanField(
                        default=False,
                        help_text="False = verbatim from transcript. True = deduced / inferred by LLM.",
                        verbose_name="Is Inferred",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Flexible storage for merge history, LLM context, etc.",
                        null=True,
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual entry"),
                            ("LLM_EXTRACTED", "LLM extracted"),
                            ("LLM_MODIFIED", "LLM modified"),
                            ("EXTERNAL_RESEARCH", "External research"),
                        ],
                        default="MANUAL",
                        help_text="How the signal was created (manual entry vs. LLM)",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "language_original",
                    models.CharField(
                        blank=True,
                        help_text='BCP-47 language tag of the source transcript (e.g. "fr", "en-US")',
                        max_length=10,
                        null=True,
                        verbose_name="Original Language",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VALIDATED", "Validated"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        help_text="PENDING = awaiting rep validation (LLM signals). VALIDATED = approved (manual signals start here). REJECTED = dismissed. MERGED = absorbed into another signal.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the signal was validated (was approved_at in legacy)",
                        null=True,
                        verbose_name="Validated At",
                    ),
                ),
                (
                    "original_value",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of value before the first manual edit. Null for signals that have never been edited.",
                        null=True,
                        verbose_name="Original Value",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DECISION_MAKER", "Decision Maker"),
                            ("ECONOMIC_BUYER", "Economic Buyer"),
                            ("CHAMPION", "Champion"),
                            ("BLOCKER", "Blocker"),
                            ("END_USER", "End User"),
                            ("PROCUREMENT", "Procurement"),
                            ("INFLUENCER", "Influencer"),
                        ],
                        help_text="Stakeholder role in the buying process (MEDDPICC-aligned)",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "influence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        help_text="Perceived influence level of the stakeholder",
                        max_length=20,
                        null=True,
                        verbose_name="Influence Level",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional context about this stakeholder observation",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Account this signal belongs to — required",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_signals",
                        to="module_accounts.companyaccount",
                        verbose_name="Account",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        help_text="Campaign this signal is associated with",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_signals",
                        to="module_campaigns.campaign",
                        verbose_name="Campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "decision_cycle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Decision cycle this signal is associated with",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_signals",
                        to="decision_cycles.decisioncycle",
                        verbose_name="Decision Cycle",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the LLM extraction (null for manual signals)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "source_activity",
                    models.ForeignKey(
                        blank=True,
                        help_text='Activity (call/meeting) from which this signal was extracted. Nullable + on_delete=SET_NULL is INTENTIONAL: a validated signal survives the deletion of its source conversation as an account-level observation. The "source_activity required at create" rule is enforced at the application layer — in concrete model clean() methods and in the Create serializers (see PainSignal.clean, BlockerSignal.clean, etc.) — never via a DB-level NOT NULL constraint, because durifying the column would contradict the SET_NULL deletion semantic.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_signals",
                        to="module_activities.activity",
                        verbose_name="Source Activity",
                    ),
                ),
                (
                    "target_contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contact playing this role. Nullable because a role may be attributed at the department level when the specific person is not yet identified.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="people_signals",
                        to="module_contacts.contact",
                        verbose_name="Target Contact",
                    ),
                ),
                (
                    "target_department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department associated with this stakeholder role. Used when the specific contact is not yet identified, or as additional context alongside target_contact.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="people_signals",
                        to="core_modules.standarddepartment",
                        verbose_name="Target Department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Rep who validated this signal (was approved_by in legacy)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_validated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "People Signal",
                "verbose_name_plural": "People Signals",
                "db_table": "module_signals_people",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["account"], name="pplsig_account_idx"),
                    models.Index(fields=["status"], name="pplsig_status_idx"),
                    models.Index(fields=["role"], name="pplsig_role_idx"),
                    models.Index(fields=["target_contact"], name="pplsig_contact_idx"),
                    models.Index(
                        fields=["account", "source_activity"],
                        name="pplsig_account_activity_idx",
                    ),
                ],
            },
        ),
    ]
