# Generated by Django 5.2.15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_ai_pipelines", "0001_initial"),
        ("module_signals", "0018_impactsignal_target_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockersignal",
            name="source_run",
            field=models.ForeignKey(
                blank=True,
                help_text="AIPipelineRun that created this signal. Used to scope cache replay queries to a single run and prevent cross-run leakage. Null for manually created signals.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_signals",
                to="module_ai_pipelines.aipipelinerun",
                verbose_name="Source Pipeline Run",
            ),
        ),
        migrations.AddField(
            model_name="constraintsignal",
            name="source_run",
            field=models.ForeignKey(
                blank=True,
                help_text="AIPipelineRun that created this signal. Used to scope cache replay queries to a single run and prevent cross-run leakage. Null for manually created signals.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_signals",
                to="module_ai_pipelines.aipipelinerun",
                verbose_name="Source Pipeline Run",
            ),
        ),
        migrations.AddField(
            model_name="impactsignal",
            name="source_run",
            field=models.ForeignKey(
                blank=True,
                help_text="AIPipelineRun that created this signal. Used to scope cache replay queries to a single run and prevent cross-run leakage. Null for manually created signals.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_signals",
                to="module_ai_pipelines.aipipelinerun",
                verbose_name="Source Pipeline Run",
            ),
        ),
        migrations.AddField(
            model_name="nextstepsignal",
            name="source_run",
            field=models.ForeignKey(
                blank=True,
                help_text="AIPipelineRun that created this signal. Used to scope cache replay queries to a single run and prevent cross-run leakage. Null for manually created signals.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_signals",
                to="module_ai_pipelines.aipipelinerun",
                verbose_name="Source Pipeline Run",
            ),
        ),
        migrations.AddField(
            model_name="objectivesignal",
            name="source_run",
            field=models.ForeignKey(
                blank=True,
                help_text="AIPipelineRun that created this signal. Used to scope cache replay queries to a single run and prevent cross-run leakage. Null for manually created signals.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_signals",
                to="module_ai_pipelines.aipipelinerun",
                verbose_name="Source Pipeline Run",
            ),
        ),
        migrations.AddField(
            model_name="painsignal",
            name="source_run",
            field=models.ForeignKey(
                blank=True,
                help_text="AIPipelineRun that created this signal. Used to scope cache replay queries to a single run and prevent cross-run leakage. Null for manually created signals.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_signals",
                to="module_ai_pipelines.aipipelinerun",
                verbose_name="Source Pipeline Run",
            ),
        ),
        migrations.AddField(
            model_name="peoplesignal",
            name="source_run",
            field=models.ForeignKey(
                blank=True,
                help_text="AIPipelineRun that created this signal. Used to scope cache replay queries to a single run and prevent cross-run leakage. Null for manually created signals.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_signals",
                to="module_ai_pipelines.aipipelinerun",
                verbose_name="Source Pipeline Run",
            ),
        ),
        migrations.AddField(
            model_name="techstacksignal",
            name="source_run",
            field=models.ForeignKey(
                blank=True,
                help_text="AIPipelineRun that created this signal. Used to scope cache replay queries to a single run and prevent cross-run leakage. Null for manually created signals.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_signals",
                to="module_ai_pipelines.aipipelinerun",
                verbose_name="Source Pipeline Run",
            ),
        ),
    ]
