# Generated by Django 5.1.14 on 2026-08-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_signals", "0020_alter_nextstepsignal_suggested_activity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nextstepsignal",
            name="suggested_activity_type",
            field=models.CharField(
                choices=[
                    ("CALL", "Phone Call"),
                    ("EMAIL", "Email"),
                    ("MEETING", "Meeting"),
                    ("DEMO", "Demo"),
                    ("TASK", "Task"),
                    ("LINKEDIN", "LinkedIn"),
                    ("OTHER", "Other"),
                ],
                help_text="Proposed type of the next-step Activity (CALL / EMAIL / MEETING / TASK / LINKEDIN / OTHER). Choices imported directly from ActivityType to keep a single source of truth — no enum duplication.",
                max_length=20,
                verbose_name="Suggested Activity Type",
            ),
        ),
    ]
