# Generated by Django 5.1.14 on 2026-08-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_signals", "0021_alter_nextstepsignal_suggested_activity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="nextstepsignal",
            name="suggested_objective",
            field=models.TextField(
                blank=True,
                help_text='Optional proposed objective for the materialised Activity. Mapped onto Activity.call_to_action at materialisation (the unified "Activity Objective") when the create payload does not set one explicitly. The prompt that fills this is out of scope here — this only lays the field + mapping.',
                null=True,
                verbose_name="Suggested Objective",
            ),
        ),
    ]
