# Generated by Django 5.1.14 on 2026-08-17 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_modules", "0001_initial"),
        ("decision_cycles", "0019_remove_decisionstep_ds_status_idx_and_more"),
        ("module_accounts", "0004_companyaccount_became_client_at"),
        ("module_activities", "0022_alter_activity_activity_type"),
        ("module_ai_pipelines", "0005_prep_call_snapshot"),
        ("module_signals", "0022_nextstepsignal_suggested_objective"),
        ("tech_catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="techstacksignal",
            name="is_competitor",
            field=models.BooleanField(
                default=False,
                help_text="True when this tool overlaps with what we sell — displacing it is a winnable angle on the deal.",
                verbose_name="Is Competitor",
            ),
        ),
        migrations.AddField(
            model_name="techstacksignal",
            name="is_integration",
            field=models.BooleanField(
                default=False,
                help_text="True when this tool is one we connect to — integrating with it is a winnable angle on the deal.",
                verbose_name="Is Integration",
            ),
        ),
        migrations.AddField(
            model_name="techstacksignal",
            name="is_to_replace",
            field=models.BooleanField(
                default=False,
                help_text="True when the account intends to replace this tool — an open door regardless of whether we compete with it or integrate with it.",
                verbose_name="Is To Replace",
            ),
        ),
        migrations.AddField(
            model_name="techstacksignal",
            name="tech_name",
            field=models.CharField(
                blank=True,
                help_text='Raw display name of the tool exactly as it was written by the LLM or the rep (e.g. "Salesforce CRM"). Never rewritten — casing, spacing and wording are preserved for display. Grouping, filtering and de-duplication use `tech_name_normalized` instead.',
                max_length=255,
                verbose_name="Tech Name",
            ),
        ),
        migrations.AddField(
            model_name="techstacksignal",
            name="tech_name_normalized",
            field=models.CharField(
                blank=True,
                help_text="Derived from `tech_name` on every save: lowercased, trimmed, internal whitespace collapsed to single spaces. This is the key used to group, filter and de-duplicate observations of the same tool. Read-only by contract — it is recomputed at save() time, so any value written by a caller is discarded and the two columns cannot desync. Empty string when `tech_name` is blank.",
                max_length=255,
                verbose_name="Tech Name (normalised)",
            ),
        ),
        migrations.AddIndex(
            model_name="techstacksignal",
            index=models.Index(
                fields=["tech_name_normalized"], name="tssig_tech_norm_idx"
            ),
        ),
    ]
