# Generated by Django 5.1.14 on 2026-08-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_signals", "0023_techstacksignal_is_competitor_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="painsignal",
            name="painsig_account_techref_idx",
        ),
        migrations.RemoveIndex(
            model_name="techstacksignal",
            name="tssig_catalog_idx",
        ),
        migrations.RemoveIndex(
            model_name="techstacksignal",
            name="tssig_account_canon_idx",
        ),
        migrations.RemoveField(
            model_name="painsignal",
            name="related_techstack",
        ),
        migrations.RemoveField(
            model_name="techstacksignal",
            name="tech_catalog_entry",
        ),
        migrations.AlterField(
            model_name="painsignal",
            name="related_techstack_mention",
            field=models.CharField(
                blank=True,
                help_text='Free-text mention of a tool involved in this pain (e.g. "Salesforce"). Not linked to any TechStackSignal — purely a textual trace captured alongside the pain.',
                max_length=200,
                verbose_name="Related TechStack Mention",
            ),
        ),
    ]
