# Generated by Django 5.1.14 on 2026-08-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "module_signals",
            "0024_remove_painsignal_painsig_account_techref_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="blockersignal",
            name="is_domain_valid",
            field=models.BooleanField(
                default=True,
                help_text='False when the LLM emitted a `what` (domain) value outside the controlled SignalWhat vocabulary — e.g. a dimension word like "COST" placed in the domain slot. Such a signal is PERSISTED (not dropped) so it stays recoverable for reprocessing, but it is EXCLUDED from every user-facing list, cluster and count. Always True for signal types that have no `what` axis and for manually created signals (serializer-validated). This flag is orthogonal to `status`: it is a data-quality gate, not a review state.',
                verbose_name="Domain valid",
            ),
        ),
        migrations.AddField(
            model_name="constraintsignal",
            name="is_domain_valid",
            field=models.BooleanField(
                default=True,
                help_text='False when the LLM emitted a `what` (domain) value outside the controlled SignalWhat vocabulary — e.g. a dimension word like "COST" placed in the domain slot. Such a signal is PERSISTED (not dropped) so it stays recoverable for reprocessing, but it is EXCLUDED from every user-facing list, cluster and count. Always True for signal types that have no `what` axis and for manually created signals (serializer-validated). This flag is orthogonal to `status`: it is a data-quality gate, not a review state.',
                verbose_name="Domain valid",
            ),
        ),
        migrations.AddField(
            model_name="impactsignal",
            name="is_domain_valid",
            field=models.BooleanField(
                default=True,
                help_text='False when the LLM emitted a `what` (domain) value outside the controlled SignalWhat vocabulary — e.g. a dimension word like "COST" placed in the domain slot. Such a signal is PERSISTED (not dropped) so it stays recoverable for reprocessing, but it is EXCLUDED from every user-facing list, cluster and count. Always True for signal types that have no `what` axis and for manually created signals (serializer-validated). This flag is orthogonal to `status`: it is a data-quality gate, not a review state.',
                verbose_name="Domain valid",
            ),
        ),
        migrations.AddField(
            model_name="nextstepsignal",
            name="is_domain_valid",
            field=models.BooleanField(
                default=True,
                help_text='False when the LLM emitted a `what` (domain) value outside the controlled SignalWhat vocabulary — e.g. a dimension word like "COST" placed in the domain slot. Such a signal is PERSISTED (not dropped) so it stays recoverable for reprocessing, but it is EXCLUDED from every user-facing list, cluster and count. Always True for signal types that have no `what` axis and for manually created signals (serializer-validated). This flag is orthogonal to `status`: it is a data-quality gate, not a review state.',
                verbose_name="Domain valid",
            ),
        ),
        migrations.AddField(
            model_name="objectivesignal",
            name="is_domain_valid",
            field=models.BooleanField(
                default=True,
                help_text='False when the LLM emitted a `what` (domain) value outside the controlled SignalWhat vocabulary — e.g. a dimension word like "COST" placed in the domain slot. Such a signal is PERSISTED (not dropped) so it stays recoverable for reprocessing, but it is EXCLUDED from every user-facing list, cluster and count. Always True for signal types that have no `what` axis and for manually created signals (serializer-validated). This flag is orthogonal to `status`: it is a data-quality gate, not a review state.',
                verbose_name="Domain valid",
            ),
        ),
        migrations.AddField(
            model_name="painsignal",
            name="is_domain_valid",
            field=models.BooleanField(
                default=True,
                help_text='False when the LLM emitted a `what` (domain) value outside the controlled SignalWhat vocabulary — e.g. a dimension word like "COST" placed in the domain slot. Such a signal is PERSISTED (not dropped) so it stays recoverable for reprocessing, but it is EXCLUDED from every user-facing list, cluster and count. Always True for signal types that have no `what` axis and for manually created signals (serializer-validated). This flag is orthogonal to `status`: it is a data-quality gate, not a review state.',
                verbose_name="Domain valid",
            ),
        ),
        migrations.AddField(
            model_name="peoplesignal",
            name="is_domain_valid",
            field=models.BooleanField(
                default=True,
                help_text='False when the LLM emitted a `what` (domain) value outside the controlled SignalWhat vocabulary — e.g. a dimension word like "COST" placed in the domain slot. Such a signal is PERSISTED (not dropped) so it stays recoverable for reprocessing, but it is EXCLUDED from every user-facing list, cluster and count. Always True for signal types that have no `what` axis and for manually created signals (serializer-validated). This flag is orthogonal to `status`: it is a data-quality gate, not a review state.',
                verbose_name="Domain valid",
            ),
        ),
        migrations.AddField(
            model_name="techstacksignal",
            name="is_domain_valid",
            field=models.BooleanField(
                default=True,
                help_text='False when the LLM emitted a `what` (domain) value outside the controlled SignalWhat vocabulary — e.g. a dimension word like "COST" placed in the domain slot. Such a signal is PERSISTED (not dropped) so it stays recoverable for reprocessing, but it is EXCLUDED from every user-facing list, cluster and count. Always True for signal types that have no `what` axis and for manually created signals (serializer-validated). This flag is orthogonal to `status`: it is a data-quality gate, not a review state.',
                verbose_name="Domain valid",
            ),
        ),
    ]
