# Generated by Django 5.1.14 on 2026-08-30 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decision_cycles", "0023_decisioncycle_expected_close_date"),
        ("module_accounts", "0004_companyaccount_became_client_at"),
        ("module_activities", "0022_alter_activity_activity_type"),
        ("module_ai_pipelines", "0005_prep_call_snapshot"),
        ("module_campaigns", "0021_alter_campaignobjective_objective_type"),
        ("module_signals", "0029_merge_usage_department_drop"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitorSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(
                        db_index=True,
                        editable=False,
                        help_text="ID of the client company this record belongs to",
                        verbose_name="Client ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "canonical_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable identifier used to group multiple observations of the same fact for corroboration. Auto-computed by concrete model save() for PeopleSignal and TechStackSignal. Set manually or by LLM for PainSignal and ObjectiveSignal.",
                        max_length=255,
                        null=True,
                        verbose_name="Canonical Key",
                    ),
                ),
                (
                    "source_quote",
                    models.TextField(
                        blank=True,
                        help_text="Exact excerpt from the transcript that supports this signal, preserved in its original language",
                        null=True,
                        verbose_name="Source Quote",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="LLM confidence score (0.0–1.0). Null for manually entered signals.",
                        null=True,
                        verbose_name="Confidence",
                    ),
                ),
                (
                    "is_inferred",
                    models.BooleanField(
                        default=False,
                        help_text="False = verbatim from transcript. True = deduced / inferred by LLM.",
                        verbose_name="Is Inferred",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Flexible storage for merge history, LLM context, etc.",
                        null=True,
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual entry"),
                            ("LLM_EXTRACTED", "LLM extracted"),
                            ("LLM_MODIFIED", "LLM modified"),
                            ("EXTERNAL_RESEARCH", "External research"),
                        ],
                        default="MANUAL",
                        help_text="How the signal was created (manual entry vs. LLM)",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "language_original",
                    models.CharField(
                        blank=True,
                        help_text='BCP-47 language tag of the source transcript (e.g. "fr", "en-US")',
                        max_length=10,
                        null=True,
                        verbose_name="Original Language",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VALIDATED", "Validated"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        help_text="PENDING = awaiting rep validation (LLM signals). VALIDATED = approved (manual signals start here). REJECTED = dismissed. MERGED = absorbed into another signal.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_domain_valid",
                    models.BooleanField(
                        default=True,
                        help_text='False when the LLM emitted a `what` (domain) value outside the controlled SignalWhat vocabulary — e.g. a dimension word like "COST" placed in the domain slot. Such a signal is PERSISTED (not dropped) so it stays recoverable for reprocessing, but it is EXCLUDED from every user-facing list, cluster and count. Always True for signal types that have no `what` axis and for manually created signals (serializer-validated). This flag is orthogonal to `status`: it is a data-quality gate, not a review state.',
                        verbose_name="Domain valid",
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the signal was validated (was approved_at in legacy)",
                        null=True,
                        verbose_name="Validated At",
                    ),
                ),
                (
                    "original_value",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of value before the first manual edit. Null for signals that have never been edited.",
                        null=True,
                        verbose_name="Original Value",
                    ),
                ),
                (
                    "competitor_name",
                    models.CharField(
                        help_text='Raw display name of the competitor exactly as it was written by the LLM or the rep (e.g. "Acme Corp"). Never rewritten — casing, spacing and wording are preserved for display. Grouping, filtering and de-duplication use `competitor_name_normalized` instead.',
                        max_length=255,
                        verbose_name="Competitor Name",
                    ),
                ),
                (
                    "competitor_name_normalized",
                    models.CharField(
                        blank=True,
                        help_text="Derived from `competitor_name` on every save: lowercased, trimmed, internal whitespace collapsed to single spaces. This is the key used to group, filter and de-duplicate observations of the same competitor. Read-only by contract — it is recomputed at save() time, so any value written by a caller is discarded and the two columns cannot desync. Empty string when `competitor_name` is blank.",
                        max_length=255,
                        verbose_name="Competitor Name (normalised)",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="One-sentence description of the competitor observation",
                        verbose_name="Summary",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Account this signal belongs to — required",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_signals",
                        to="module_accounts.companyaccount",
                        verbose_name="Account",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        help_text="Campaign this signal is associated with",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_signals",
                        to="module_campaigns.campaign",
                        verbose_name="Campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "decision_cycle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Decision cycle this signal is associated with",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_signals",
                        to="decision_cycles.decisioncycle",
                        verbose_name="Decision Cycle",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the LLM extraction (null for manual signals)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_requested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "source_activity",
                    models.ForeignKey(
                        blank=True,
                        help_text='Activity (call/meeting) from which this signal was extracted. Nullable + on_delete=SET_NULL is INTENTIONAL: a validated signal survives the deletion of its source conversation as an account-level observation. The "source_activity required at create" rule is enforced at the application layer — in concrete model clean() methods and in the Create serializers (see PainSignal.clean, BlockerSignal.clean, etc.) — never via a DB-level NOT NULL constraint, because durifying the column would contradict the SET_NULL deletion semantic.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_signals",
                        to="module_activities.activity",
                        verbose_name="Source Activity",
                    ),
                ),
                (
                    "source_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="AIPipelineRun that created this signal. Used to scope cache replay queries to a single run and prevent cross-run leakage. Null for manually created signals.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_signals",
                        to="module_ai_pipelines.aipipelinerun",
                        verbose_name="Source Pipeline Run",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Rep who validated this signal (was approved_by in legacy)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_validated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competitor Signal",
                "verbose_name_plural": "Competitor Signals",
                "db_table": "module_signals_competitor",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["account"], name="cmpsig_account_idx"),
                    models.Index(fields=["status"], name="cmpsig_status_idx"),
                    models.Index(
                        fields=["competitor_name_normalized"],
                        name="cmpsig_name_norm_idx",
                    ),
                ],
            },
        ),
    ]
