# Generated by Django 5.1.14 on 2026-08-31 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_modules", "0001_initial"),
        ("decision_cycles", "0023_decisioncycle_expected_close_date"),
        ("module_accounts", "0004_companyaccount_became_client_at"),
        ("module_activities", "0022_alter_activity_activity_type"),
        ("module_ai_pipelines", "0005_prep_call_snapshot"),
        ("module_campaigns", "0021_alter_campaignobjective_objective_type"),
        ("module_contacts", "0003_normalize_empty_contact_email_phone_to_null"),
        ("module_signals", "0034_remove_techstacksignal_is_integration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="peoplesignal",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text='Raw display name of the stakeholder exactly as observed (e.g. "Marc Dubois"). Optional — a role may still be attributed via target_contact / target_department only. Never rewritten; casing and spacing are preserved for display. Grouping and matching use `full_name_normalized` instead.',
                max_length=255,
                verbose_name="Full Name",
            ),
        ),
        migrations.AddField(
            model_name="peoplesignal",
            name="full_name_normalized",
            field=models.CharField(
                blank=True,
                help_text="Derived from `full_name` on every save: lowercased, trimmed, internal whitespace collapsed to single spaces. Empty string when `full_name` is blank. Read-only by contract — recomputed at save() time, so the two columns cannot desync.",
                max_length=255,
                verbose_name="Full Name (normalised)",
            ),
        ),
        migrations.AddIndex(
            model_name="peoplesignal",
            index=models.Index(
                fields=["full_name_normalized"], name="peoplesig_name_norm_idx"
            ),
        ),
    ]
