# Generated by Django 5.1.14 on 2026-09-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_signals", "0041_remove_pain_impact_target_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signalclusterarchival",
            name="signal_type",
            field=models.CharField(
                choices=[
                    ("pain", "Pain"),
                    ("objective", "Objective"),
                    ("tech_stack", "Tech Stack"),
                    ("impact", "Impact"),
                    ("constraint", "Constraint"),
                    ("competitor", "Competitor"),
                    ("people", "People"),
                ],
                help_text="Signal family the cluster belongs to (e.g. 'pain'). Matches the type identifiers used by SignalDataService and the cluster endpoints.",
                max_length=20,
                verbose_name="Signal Type",
            ),
        ),
    ]
