# Generated by Django 5.1.14 on 2026-09-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_signals", "0042_alter_signalclusterarchival_signal_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impactsignal",
            name="impact_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FINANCIAL", "Financial impact"),
                    ("TIME", "Time impact"),
                    ("PRODUCTIVITY", "Productivity impact"),
                    ("REVENUE", "Revenue impact"),
                    ("RISK", "Risk impact"),
                    ("CUSTOMER", "Customer impact"),
                    ("HUMAN", "Human impact"),
                    ("STRATEGIC", "Strategic impact"),
                    ("METRIC", "Raw metric"),
                ],
                help_text="Nature of the impact observation — FINANCIAL, TIME, PRODUCTIVITY, REVENUE, RISK, CUSTOMER, HUMAN, STRATEGIC, or METRIC. Orthogonal axis to (what, dimension): two observations sharing the same canonical_key can carry different impact_types (e.g. one FINANCIAL, one HUMAN).",
                max_length=20,
                verbose_name="Impact Type",
            ),
        ),
    ]
