# Generated by Django 5.1.14 on 2026-09-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_signals", "0043_alter_impactsignal_impact_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constraintsignal",
            name="rigidity",
            field=models.CharField(
                blank=True,
                choices=[("FIRM", "Firm"), ("FLEXIBLE", "Flexible")],
                help_text="Whether this constraint is non-negotiable (FIRM) or a preference (FLEXIBLE).",
                max_length=20,
                verbose_name="Rigidity",
            ),
        ),
    ]
