# Generated by Django 5.1.14 on 2026-07-27 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("module_campaigns", "0014_campaign_channel_override"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quota",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(
                        db_index=True,
                        editable=False,
                        help_text="ID of the client company this record belongs to",
                        verbose_name="Client ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("DECISION_CYCLES", "Decision cycles"),
                            ("LEADS", "Leads"),
                            ("MEETINGS", "Meetings"),
                            ("NEW_LOGOS", "New logos"),
                            ("PIPELINE_VALUE", "Pipeline value"),
                            ("REVENUE_WON", "Revenue won"),
                        ],
                        help_text="Which canonical Sales metric this objective targets.",
                        max_length=30,
                        verbose_name="Metric",
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target to reach (Decimal covers both amounts and counts).",
                        max_digits=14,
                        verbose_name="Target Value",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        help_text="First day of the objective window.",
                        verbose_name="Period Start",
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        help_text="Last day of the objective window.",
                        verbose_name="Period End",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who owns this objective (always the creator).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "source_campaign",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional campaign this objective is declined onto. When null the objective is global (measured across all of the owner's work).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotas",
                        to="module_campaigns.campaign",
                        verbose_name="Source Campaign",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quota",
                "verbose_name_plural": "Quotas",
                "db_table": "quotas",
                "ordering": ["-period_start", "-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["owner"], name="quota_owner_idx"),
                    models.Index(
                        fields=["owner", "metric"], name="quota_owner_metric_idx"
                    ),
                    models.Index(
                        fields=["period_start", "period_end"], name="quota_window_idx"
                    ),
                    models.Index(
                        fields=["source_campaign"], name="quota_source_campaign_idx"
                    ),
                ],
            },
        ),
    ]
