# Generated by Django 5.1.14 on 2026-08-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quota",
            name="metric",
            field=models.CharField(
                choices=[
                    ("DECISION_CYCLES", "Decision cycles"),
                    ("LEADS", "Leads"),
                    ("MEETINGS", "Meetings"),
                    ("NEW_LOGOS", "New logos"),
                    ("PIPELINE_VALUE", "Pipeline value"),
                    ("REVENUE_WON", "Won value"),
                ],
                help_text="Which canonical Sales metric this objective targets.",
                max_length=30,
                verbose_name="Metric",
            ),
        ),
    ]
