# Generated by Django 5.1.14 on 2026-08-20 12:57
#
# LEADS leaves the metric vocabulary (PO). ``choices`` is metadata Django
# validates on write — it is NOT a database constraint — so this migration
# changes no column and touches no row. Any Quota already stored under 'LEADS'
# therefore survives it; the read path reports such a row at 0 against its
# original target rather than raising (quotas/services/progress._compute_value),
# so it stays visible for the PO to decide on. Deleting those rows is deliberately NOT
# done here: they are users' own objectives, and destroying them is a product
# decision, not a side effect of retiring an enum value.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotas", "0002_alter_quota_metric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quota",
            name="metric",
            field=models.CharField(
                choices=[
                    ("DECISION_CYCLES", "Decision cycles"),
                    ("MEETINGS", "Meetings"),
                    ("NEW_LOGOS", "New logos"),
                    ("PIPELINE_VALUE", "Pipeline value"),
                    ("REVENUE_WON", "Won value"),
                ],
                help_text="Which canonical Sales metric this objective targets.",
                max_length=30,
                verbose_name="Metric",
            ),
        ),
    ]
