"""
Django settings for salescommands project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
from django.core.cache.backends.filebased import FileBasedCache
from datetime import timedelta
import sys
import os

env = environ.Env()
environ.Env.read_env()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =========================================================================
# CRITICAL SECURITY SETTINGS - ENVIRONMENT VARIABLES
# =========================================================================


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'] if DEBUG else [])


# =========================================================================
# CORS CONFIGURATION - ENVIRONMENT GATING
# =========================================================================

# Get CORS origins from environment variable (comma-separated list)
# Development default: localhost origins
# Production: MUST be set via environment variable
_cors_origins_raw = env.list(
    'CORS_ALLOWED_ORIGINS',
    default=['http://localhost:3000', 'http://localhost:8081'] if DEBUG else []
)

# Validate CORS configuration based on environment
if DEBUG:
    # Development: Allow localhost, but warn if production origins are present
    CORS_ALLOWED_ORIGINS = _cors_origins_raw
    
    # Warn if HTTPS origins in development (possible misconfiguration)
    https_origins = [o for o in CORS_ALLOWED_ORIGINS if o.startswith('https://')]
    if https_origins:
        print(
            f"⚠️  WARNING: HTTPS origins detected in development mode: {https_origins}\n"
            f"   This is unusual. Verify your CORS_ALLOWED_ORIGINS configuration."
        )
else:
    # Production: Strict validation
    CORS_ALLOWED_ORIGINS = _cors_origins_raw
    
    # CRITICAL: Validate no localhost in production
    localhost_origins = [
        o for o in CORS_ALLOWED_ORIGINS 
        if 'localhost' in o or '127.0.0.1' in o or '0.0.0.0' in o
    ]
    
    if localhost_origins:
        error_msg = (
            f"\n{'='*70}\n"
            f"🚨 CRITICAL SECURITY ERROR: Localhost origins in production!\n"
            f"{'='*70}\n"
            f"The following localhost origins were found in CORS_ALLOWED_ORIGINS:\n"
            f"{localhost_origins}\n\n"
            f"This is a CRITICAL security vulnerability that allows any attacker\n"
            f"to bypass CORS protection by making requests from localhost.\n\n"
            f"ACTION REQUIRED:\n"
            f"1. Remove all localhost origins from CORS_ALLOWED_ORIGINS\n"
            f"2. Set production frontend URLs only (e.g., https://app.yourdomain.com)\n"
            f"3. Restart the application\n"
            f"{'='*70}\n"
        )
        print(error_msg, file=sys.stderr)
        raise ValueError("Localhost origins not allowed in production. Check CORS_ALLOWED_ORIGINS environment variable.")
    
    # Validate HTTPS in production (warning only, not blocking)
    http_origins = [o for o in CORS_ALLOWED_ORIGINS if o.startswith('http://') and not o.startswith('http://localhost')]
    if http_origins:
        print(
            f"⚠️  WARNING: Non-HTTPS origins in production: {http_origins}\n"
            f"   HTTPS is strongly recommended for production.\n"
            f"   HTTP origins are insecure and should only be used for testing."
        )
    
    # Validate at least one origin is configured in production
    if not CORS_ALLOWED_ORIGINS:
        error_msg = (
            f"\n{'='*70}\n"
            f"🚨 CONFIGURATION ERROR: No CORS origins in production!\n"
            f"{'='*70}\n"
            f"CORS_ALLOWED_ORIGINS is empty in production mode.\n\n"
            f"ACTION REQUIRED:\n"
            f"Set CORS_ALLOWED_ORIGINS environment variable with your frontend URLs.\n"
            f"Example: CORS_ALLOWED_ORIGINS=https://app.yourdomain.com,https://www.yourdomain.com\n"
            f"{'='*70}\n"
        )
        print(error_msg, file=sys.stderr)
        raise ValueError("CORS_ALLOWED_ORIGINS must be configured in production.")

# Additional CORS settings
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    # Default django-cors-headers
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    # 🔗 Custom header for distributed tracing
    'x-correlation-id',
]

# Sans ceci, JavaScript ne peut PAS lire ces headers à cause de CORS
CORS_EXPOSE_HEADERS = [
    'Retry-After',      # ← CRITIQUE pour Phase 1 (429 throttling)
    'X-Request-ID',     # Pour debug/tracing
    'X-Correlation-ID', # Pour distributed tracing
]


# Log CORS configuration on startup (DEBUG mode only)
if DEBUG:
    print(f"✓ CORS configuration loaded:")
    print(f"  - Allowed origins: {CORS_ALLOWED_ORIGINS}")
    print(f"  - Allow credentials: {CORS_ALLOW_CREDENTIALS}")
    print(f"  - Exposed headers: {CORS_EXPOSE_HEADERS}") 



# =========================================================================
# THROTTLING CONFIGURATION - MVP SECURITY
# =========================================================================

# Feature flag pour activer/désactiver le throttling
THROTTLING_ENABLED = env.bool('THROTTLING_ENABLED', default=True)

# Configuration par environnement
if DEBUG:
    # Dev: Plus permissif pour faciliter les tests
    THROTTLE_RATES = {
        'anon': '100/hour',      # Utilisateurs non authentifiés
        'user': '1000/hour',     # Utilisateurs authentifiés
        'login': '20/hour',      # Tentatives de login (par IP+email)
        'password': '10/hour',   # Changements de mot de passe
        'sensitive': '30/hour',  # Opérations sensibles
        'burst': '5/minute',    # Anti-burst
        'registration': '5/hour', # Inscriptions
    }
else:
    # Production: Plus restrictif
    THROTTLE_RATES = {
        'anon': '20/hour',       
        'user': '100/hour',      
        'login': '5/hour',       # Plus strict en prod : 5 tentatives/heure
        'password': '3/hour',    
        'sensitive': '10/hour',  
        'burst': '5/minute',
        'registration': '3/hour',
    }


# =========================================================================
# REST OF SETTINGS.PY 
# =========================================================================


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'core',
    'apps.core_apps',
    'apps.accounts',
    'apps.signals',
    'apps.campaign',
    'apps.opportunities',
    'apps.sequence',
    'apps.activities',
    'apps.leads',	
    # 'apps.accounts_app.accounts',
    # 'apps.accounts_app.org_units',
    # 'apps.accounts_app.account_product_detail',
    # 'apps.accounts_app.contacts',
    'apps.LLM_calls',
    'apps.products',
    'apps.sales_insight',
    'end_users',
    'product_admin',
    "phonenumber_field",
    'django_filters',
    'debug_toolbar',
]

MIDDLEWARE = [
    'core.logging.middlewares.RequestIdMiddleware',
    'core.logging.request_logging.RequestLoggingMiddleware',
    'core.http.etag.ETagMiddleware',
    
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middlewares.security_middleware.InputSanitizationMiddleware',
    'core.middlewares.middleware.LogRequestHeadersMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',	
]

ROOT_URLCONF = 'salescommands.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'salescommands.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# Database
DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.postgresql_psycopg2",
    #     "NAME": env('DATABASE_NAME'),
    #     "USER": env('DATABASE_USERNAME'),
    #     "PASSWORD": env('DATABASE_PASSWORD'),
    #     "HOST": env('DATABASE_HOSTNAME'),
    #     "PORT": env('DATABASE_PORT')
    # }
     'default': env.db()
}

# ==============================
# API CACHE CONFIGURATION
# ==============================

# Préfixes des endpoints API qui doivent avoir les headers no-cache
API_ENDPOINT_PREFIXES = [
    '/client/',       # end_users endpoints
    '/app/',          # app endpoints  
    '/campaign/',     # campaign endpoints
    '/leads/',        # leads endpoints
    '/activities/',   # activities endpoints
    '/opportunities/', # opportunities endpoints
    '/signals/',      # signals endpoints
    '/insights/',     # insights endpoints
    '/product_admin/', # product admin endpoints
]

# ==============================
# SECURITY HEADERS CONFIGURATION
# ==============================

# Security headers (managed by Django SecurityMiddleware)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'

# 🔒 HSTS (HTTP Strict Transport Security) - Production only
# Forces HTTPS connections and prevents SSL stripping attacks
# Only activated when DEBUG=False (production mode)
SECURE_HSTS_SECONDS = 31536000  # 1 year (31536000 seconds)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply to all subdomains
SECURE_HSTS_PRELOAD = True  # Enable HSTS preload list eligibility

# Note: HSTS headers will NOT be sent in development (DEBUG=True)
# to allow HTTP connections on localhost


# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',  # Update the location if Redis is hosted elsewhere
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         },
#         'KEY_PREFIX': 'crm_cache'
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

AUTH_USER_MODEL = 'end_users.User' 
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default backend
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.jwt_helpers.CustomJWTAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',

    # ===== THROTTLING CONFIGURATION (MVP) =====
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'core.throttling.BurstRateThrottle',  # 🔹 anti-burst par minute (auth only)
    ] if THROTTLING_ENABLED else [],

    'DEFAULT_THROTTLE_RATES': THROTTLE_RATES if THROTTLING_ENABLED else {},

    # ===== AUTRES CONFIGURATIONS =====
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S.%fZ',
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M:%S',
}



# Session Cookie Settings
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG  # True en production seulement
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 86400  # 24 heures

# CSRF Cookie Settings  
CSRF_COOKIE_SECURE = not DEBUG  # True en production seulement
CSRF_COOKIE_HTTPONLY = False  # False pour permettre JS de le lire (nécessaire pour AJAX)
CSRF_COOKIE_SAMESITE = 'Lax'


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    'ALGORITHM': 'HS256',
    'SIGNING_KEY_ADMIN': env('JWT_ADMIN_SECRET_KEY'),
    'SIGNING_KEY_USER': env('JWT_USER_SECRET_KEY'),
    'VERIFYING_KEY': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'TOKEN_USER_CLASS': 'core.jwt_helpers.CustomJWTAuthentication',

    # Cookie settings
    'AUTH_COOKIE': 'access_token',
    'AUTH_COOKIE_SECURE': True,
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SAMESITE': 'Lax',
}

ROLE_REFRESH_LIFETIMES = {
    'product_admin': timedelta(days=1),
    'user_admin': timedelta(days=1),
    'end_users': timedelta(days=7),
}


#OPEN AI

OPENAI_API_KEY= {
     "OPENAI_API_KEY": env('OPENAI_API_KEY')
} 


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# HSTS Configuration (Production only)
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True


# =========================================================================
# CACHE CONFIGURATION - Redis with graceful fallback
# =========================================================================


CACHE_DIR = BASE_DIR / ".cache"
os.makedirs(CACHE_DIR, exist_ok=True)

REDIS_URL = env('REDIS_URL', default=None)
REDIS_THROTTLE_URL = env('REDIS_THROTTLE_URL', default=None)


if REDIS_URL:
    # Redis cache (production/staging)
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "IGNORE_EXCEPTIONS": True,  # Graceful fallback if Redis fails
            },
            "KEY_PREFIX": "crm",
            "TIMEOUT": 300,  # 5 minutes default TTL
        }
    }
    
    # Optional: Dedicated Redis DB for throttling
    if REDIS_THROTTLE_URL:
        CACHES["throttle"] = {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_THROTTLE_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "IGNORE_EXCEPTIONS": True,
            },
            "KEY_PREFIX": "crm_throttle",
        }
else:
    # Fallback: File-based cache for development without Redis
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
            "LOCATION": str(CACHE_DIR),
            "TIMEOUT": None,
            "OPTIONS": {"MAX_ENTRIES": 50000},
        }
    }

# Configure DRF throttling to use dedicated cache if available
if "throttle" in CACHES:
    REST_FRAMEWORK["DEFAULT_THROTTLE_CACHE"] = "throttle"


# =========================================================================
# LOGGING FOR THROTTLING (OPTIONNEL MAIS UTILE)
# =========================================================================

# Ajouter dans votre configuration de logging existante
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        # ... vos formatters existants ...
    },
    'handlers': {
        # ... vos handlers existants ...
        
        # Handler spécifique pour le throttling
        'throttle_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'throttle.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # ... vos loggers existants ...
        
        # Logger pour le throttling
        'rest_framework.throttling': {
            'handlers': ['throttle_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Logger pour les tentatives de login bloquées
        'core.throttling': {
            'handlers': ['throttle_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# =========================================================================
# THROTTLE WHITELIST (OPTIONNEL)
# =========================================================================

# IPs ou ranges à exclure du throttling (ex: monitoring, CI/CD)
THROTTLE_WHITELIST_IPS = env.list('THROTTLE_WHITELIST_IPS', default=[
    '127.0.0.1',  # Localhost
    # '10.0.0.0/8',  # Réseau interne (décommenter si nécessaire)
])

# Utilisateurs à exclure du throttling (par email ou ID)
THROTTLE_WHITELIST_USERS = env.list('THROTTLE_WHITELIST_USERS', default=[
    # 'admin@yourcompany.com',
    # 'monitoring@yourcompany.com',
])

# =========================================================================
# CONFIGURATION DE MESSAGES D'ERREUR THROTTLING
# =========================================================================

# Messages personnalisés pour les erreurs de throttling
THROTTLE_ERROR_MESSAGES = {
    'anon': 'Too many requests from this IP. Please try again later.',
    'user': 'You have exceeded the rate limit. Please slow down your requests.',
    'login': 'Too many login attempts. Please wait before trying again.',
    'password': 'Too many password change attempts. Please wait before trying again.',
    'sensitive': 'This action has been rate limited for security. Please try again later.',
}

# =========================================================================
# MONITORING & ALERTING (OPTIONNEL)
# =========================================================================

# Seuils d'alerte pour le monitoring
THROTTLE_ALERT_THRESHOLDS = {
    'login_attempts_per_hour': 50,  # Alerter si plus de 50 tentatives de login/heure depuis une IP
    'user_requests_per_minute': 20,  # Alerter si un user fait plus de 20 requêtes/minute
    'total_throttled_per_hour': 100,  # Alerter si plus de 100 requêtes throttled/heure globalement
}



# ========================================================================
# PERMISSIONS CONFIGURATION
# ========================================================================

PERMISSIONS_CONFIG = {
    # Master kill switch - set to True to enable the permission system globally
    'GLOBAL_ENABLED': True,  # Start with False for safety
    
    # Debug mode - adds permission info to response headers (only in DEBUG=True)
    'DEBUG': True,
    
    # Audit logging - logs all permission checks
    'AUDIT_ENABLED': True,
    
    # Cache timeout for permission decisions (in seconds)
    'CACHE_TIMEOUT': 300,  # 5 minutes
    
    # Logger name for audit logs
    'AUDIT_LOGGER': 'permissions.audit',
    
    # Enable object-level permission checks (more expensive)
    'ENABLE_OBJECT_PERMISSIONS': False,
    
    # Strict mode - if True, any error results in permission denied
    'STRICT_MODE': False,  # Set to True in production
    
    # Module-by-module feature flags
    # Enable modules one by one for gradual rollout
    'MODULES': {
        'accounts': False,      # Account management
        'contacts': False,      # Contact management  
        'activities': False,    # Activity tracking
        'leads': False,         # Lead management
        'opportunities': False, # Opportunity/deals
        'campaign': False,      # Campaign management
        'pipelines': False,     # Buying process/pipelines
        'templates': False,     # Email/doc templates
        'users': True,         # User management
        'products': False,      # Product catalog
    }
}

# ========================================================================
# PERMISSION SYSTEM INITIALIZATION CHECK
# ========================================================================

# Add this at the end of settings.py to verify configuration on startup
def check_permission_config():
    """Validate permission configuration on startup."""
    if PERMISSIONS_CONFIG.get('GLOBAL_ENABLED'):
        enabled_modules = [
            module for module, enabled in PERMISSIONS_CONFIG['MODULES'].items() 
            if enabled
        ]
        if not enabled_modules:
            import warnings
            warnings.warn(
                "Permission system is globally enabled but no modules are activated. "
                "Enable specific modules in PERMISSIONS_CONFIG['MODULES']."
            )
        else:
            print(f"✓ Permission system enabled for modules: {', '.join(enabled_modules)}")
    else:
        print("✓ Permission system is currently DISABLED (GLOBAL_ENABLED=False)")

# Run the check (comment out in production)
if DEBUG:
    check_permission_config()

# ========================================
# LOGGING CONFIGURATION 
# ========================================

# Feature flag to enable header logging in production
# Set LOG_HEADERS_IN_PROD=true in environment to enable
LOG_HEADERS_IN_PROD = env.bool('LOG_HEADERS_IN_PROD', default=False)

# Allowlist of headers to log in production (case-insensitive)
# These headers provide useful debugging info without exposing sensitive data
LOG_HEADERS_ALLOWLIST = [
    'x-request-id',        # Correlation ID from proxies/LB
    'x-forwarded-for',     # Original client IP through proxies
    'x-real-ip',           # Alternative client IP header
    'cf-connecting-ip',    # Cloudflare's client IP header
    'user-agent',          # Browser/client identification
    'content-type',        # Request content type
    'x-forwarded-proto',   # Original protocol (http/https)
    'x-forwarded-host',    # Original host header
    'referer',             # Referrer for tracking navigation
    'accept',              # Content negotiation
    'accept-language',     # Language preferences
    'x-csrf-token',        # CSRF token (already public)
]

# Additional paths to exclude from logging (beyond defaults)
# Add paths here that are specific to your deployment
LOGGING_EXCLUDED_PATHS = {
    # '/api/v1/internal/health',
    # '/api/v1/internal/metrics',
}


# =========================================================================
# LOGGING CONFIGURATION - MVP
# =========================================================================


import time
import logging.handlers
from pathlib import Path
import datetime

class UTCFormatter(logging.Formatter):
    """
    Formatter that converts timestamp to UTC with proper milliseconds.
    Override formatTime to handle ISO-8601 format correctly.
    """
    converter = time.gmtime  # Keep UTC
    
    def formatTime(self, record, datefmt=None):
        """
        Format time as ISO-8601 with milliseconds in UTC.
        
        Args:
            record: LogRecord instance
            datefmt: Ignored (we always use ISO format)
            
        Returns:
            str: ISO-8601 formatted timestamp with milliseconds
        """
        # Convert timestamp to datetime in UTC
        dt = datetime.datetime.fromtimestamp(record.created, datetime.timezone.utc)
        
        # Format as ISO-8601 with milliseconds, replace +00:00 with Z
        # timespec='milliseconds' gives us .123 format
        return dt.isoformat(timespec='milliseconds').replace('+00:00', 'Z')

# Custom filter for safe logging (sanitization + default values)
class SafeExtraFilter(logging.Filter):
    """
    Filter that:
    1. Injects default values for missing context keys (avoid KeyError)
    2. Sanitizes sensitive data (passwords, tokens, emails, etc.)
    3. Truncates large values to prevent log bloat
    """
    
    # Default values for structured logging keys
    DEFAULTS = {
        'correlation_id': '-',
        'user_id': '-', 
        'client_id': '-',
        'method': '-',
        'path': '-',
        'status_code': '-',
        'duration_ms': '-',
        'remote_ip': '-'
    }
    
    # Sensitive keys to mask (case-insensitive substring match)
    SENSITIVE_PATTERNS = [
        'password', 'token', 'authorization', 'cookie', 
        'secret', 'api_key', 'jwt', 'bearer'
    ]
    
    # Keys containing payloads to fully redact
    PAYLOAD_KEYS = ['body', 'request_data', 'payload']
    
    # Built-in LogRecord attributes to skip
    BUILTIN_ATTRS = {
        'name', 'msg', 'args', 'created', 'filename', 'funcName', 
        'levelname', 'levelno', 'lineno', 'module', 'msecs', 
        'message', 'pathname', 'process', 'processName', 
        'relativeCreated', 'stack_info', 'thread', 'threadName', 
        'exc_info', 'exc_text', 'stack_info', 'getMessage'
    }
    
    def filter(self, record):
        """Process each log record for safety"""
        
        # 1. Inject default values for missing keys
        for key, default_value in self.DEFAULTS.items():
            if not hasattr(record, key):
                setattr(record, key, default_value)
        
        # 2. Sanitize all extra attributes (iterate on __dict__ for performance)
        for attr_name, attr_value in list(record.__dict__.items()):
            # Skip built-in attributes
            if attr_name.startswith('_') or attr_name in self.BUILTIN_ATTRS:
                continue
            
            # Skip if None or already a default value
            if attr_value is None or attr_value in self.DEFAULTS.values():
                continue
                
            # Convert to string for processing
            attr_value_str = str(attr_value)
            attr_name_lower = attr_name.lower()
            
            # 2a. Redact payload/body completely
            if any(payload_key in attr_name_lower for payload_key in self.PAYLOAD_KEYS):
                setattr(record, attr_name, '[PAYLOAD_REDACTED]')
                continue
            
            # 2b. Check for sensitive patterns
            is_sensitive = any(pattern in attr_name_lower for pattern in self.SENSITIVE_PATTERNS)
            
            if is_sensitive:
                # Mask the value
                if '@' in attr_value_str and '.' in attr_value_str:
                    # Email-like value
                    setattr(record, attr_name, self._mask_email(attr_value_str))
                else:
                    # Generic sensitive data
                    setattr(record, attr_name, '[REDACTED]')
                continue
            
            # 2c. Check value content for emails (even in non-sensitive keys)
            if '@' in attr_value_str and '.' in attr_value_str and len(attr_value_str) < 100:
                # Likely an email, mask it
                setattr(record, attr_name, self._mask_email(attr_value_str))
                continue
            
            # 2d. Truncate large values
            if len(attr_value_str) > 2000:
                setattr(record, attr_name, attr_value_str[:2000] + '[TRUNCATED_2000]')
        
        return True
    
    def _mask_email(self, email):
        """Mask email keeping domain: j***@domain.com"""
        try:
            if '@' in email:
                local, domain = email.split('@', 1)
                if len(local) > 0:
                    masked = local[0] + '***@' + domain
                    return masked
            return email
        except:
            return '[EMAIL_REDACTED]'


# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    # Formatters
    'formatters': {
        'structured': {
            '()': UTCFormatter,  # Force UTC timestamps
            'format': (
                'timestamp=%(asctime)s level=%(levelname)s logger=%(name)s '
                'msg="%(message)s" file=%(module)s line=%(lineno)d func=%(funcName)s '
                'correlation_id=%(correlation_id)s user_id=%(user_id)s client_id=%(client_id)s '
                'method=%(method)s path="%(path)s" status=%(status_code)s '
                'duration_ms=%(duration_ms)s ip=%(remote_ip)s'
            )
        }
    },
    
    # Filters
    'filters': {
        'safe_extra': {
            '()': SafeExtraFilter,
        }
    },
    
    # Handlers (will be set conditionally below)
    'handlers': {},
    
    # Loggers
    'loggers': {
        # Project root logger (catches all backend.* loggers)
        'backend': {
            'handlers': [],  # Will be set below
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        
        # Django system loggers
        'django': {
            'handlers': [],  # Will be set below
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': [],  # Will be set below
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': [],  # Will be set below
            'level': 'WARNING',  # Reduce noise from dev server
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': [],  # Will be set below
            'level': 'WARNING',
            'propagate': False,
        },
    },
    
    # Root logger (catches everything else)
    'root': {
        'handlers': [],  # Will be set below
        'level': 'DEBUG' if DEBUG else 'INFO',  # Changed from WARNING
    }
}

# Determine if file logging should be enabled (via ENV variable)
enable_file_logs = os.getenv('ENABLE_FILE_LOGS', '').lower() in {'1', 'true', 'yes'}
logs_dir = Path(BASE_DIR / 'logs')
use_files = enable_file_logs and logs_dir.exists()

# Console handler (always present)
LOGGING['handlers']['console'] = {
    'class': 'logging.StreamHandler',
    'formatter': 'structured',
    'filters': ['safe_extra'],
}

# Add file handlers if enabled and directory exists
if use_files:
    LOGGING['handlers']['file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': str(logs_dir / 'app.log'),
        'maxBytes': 5 * 1024 * 1024,  # 5MB
        'backupCount': 5,
        'formatter': 'structured',
        'filters': ['safe_extra'],
    }
    LOGGING['handlers']['error_file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': str(logs_dir / 'error.log'),
        'maxBytes': 5 * 1024 * 1024,  # 5MB
        'backupCount': 5,
        'formatter': 'structured',
        'filters': ['safe_extra'],
        'level': 'ERROR',
    }
    active_handlers = ['console', 'file', 'error_file']
else:
    # Console only (default for PaaS or when file logs disabled)
    active_handlers = ['console']

# Apply handlers to all loggers
for logger_name in LOGGING['loggers']:
    LOGGING['loggers'][logger_name]['handlers'] = active_handlers
LOGGING['root']['handlers'] = active_handlers

# Log configuration status (only in DEBUG)
if DEBUG:
    import sys
    config_msg = f"Logging configured: file_logs={use_files}, handlers={active_handlers}"
    if not use_files and enable_file_logs:
        config_msg += f" (logs/ directory not found)"
    print(f"[LOGGING] {config_msg}", file=sys.stderr)


