"""
Django settings for salescommands project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
from django.core.cache.backends.filebased import FileBasedCache
from datetime import timedelta
import sys
import os

env = environ.Env()
environ.Env.read_env()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =========================================================================
# CRITICAL SECURITY SETTINGS - ENVIRONMENT VARIABLES
# =========================================================================


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'] if DEBUG else [])


# =========================================================================
# CORS CONFIGURATION - ENVIRONMENT GATING
# =========================================================================

# Get CORS origins from environment variable (comma-separated list)
# Development default: localhost origins
# Production: MUST be set via environment variable
_cors_origins_raw = env.list(
    'CORS_ALLOWED_ORIGINS',
    default=['http://localhost:3000', 'http://localhost:8081'] if DEBUG else []
)

# Validate CORS configuration based on environment
if DEBUG:
    # Development: Allow localhost, but warn if production origins are present
    CORS_ALLOWED_ORIGINS = _cors_origins_raw
    
    # Warn if HTTPS origins in development (possible misconfiguration)
    https_origins = [o for o in CORS_ALLOWED_ORIGINS if o.startswith('https://')]
    if https_origins:
        print(
            f"⚠️  WARNING: HTTPS origins detected in development mode: {https_origins}\n"
            f"   This is unusual. Verify your CORS_ALLOWED_ORIGINS configuration."
        )
else:
    # Production: Strict validation
    CORS_ALLOWED_ORIGINS = _cors_origins_raw
    
    # CRITICAL: Validate no localhost in production
    localhost_origins = [
        o for o in CORS_ALLOWED_ORIGINS 
        if 'localhost' in o or '127.0.0.1' in o or '0.0.0.0' in o
    ]
    
    if localhost_origins:
        error_msg = (
            f"\n{'='*70}\n"
            f"🚨 CRITICAL SECURITY ERROR: Localhost origins in production!\n"
            f"{'='*70}\n"
            f"The following localhost origins were found in CORS_ALLOWED_ORIGINS:\n"
            f"{localhost_origins}\n\n"
            f"This is a CRITICAL security vulnerability that allows any attacker\n"
            f"to bypass CORS protection by making requests from localhost.\n\n"
            f"ACTION REQUIRED:\n"
            f"1. Remove all localhost origins from CORS_ALLOWED_ORIGINS\n"
            f"2. Set production frontend URLs only (e.g., https://app.yourdomain.com)\n"
            f"3. Restart the application\n"
            f"{'='*70}\n"
        )
        print(error_msg, file=sys.stderr)
        raise ValueError("Localhost origins not allowed in production. Check CORS_ALLOWED_ORIGINS environment variable.")
    
    # Validate HTTPS in production (warning only, not blocking)
    http_origins = [o for o in CORS_ALLOWED_ORIGINS if o.startswith('http://') and not o.startswith('http://localhost')]
    if http_origins:
        print(
            f"⚠️  WARNING: Non-HTTPS origins in production: {http_origins}\n"
            f"   HTTPS is strongly recommended for production.\n"
            f"   HTTP origins are insecure and should only be used for testing."
        )
    
    # Validate at least one origin is configured in production
    if not CORS_ALLOWED_ORIGINS:
        error_msg = (
            f"\n{'='*70}\n"
            f"🚨 CONFIGURATION ERROR: No CORS origins in production!\n"
            f"{'='*70}\n"
            f"CORS_ALLOWED_ORIGINS is empty in production mode.\n\n"
            f"ACTION REQUIRED:\n"
            f"Set CORS_ALLOWED_ORIGINS environment variable with your frontend URLs.\n"
            f"Example: CORS_ALLOWED_ORIGINS=https://app.yourdomain.com,https://www.yourdomain.com\n"
            f"{'='*70}\n"
        )
        print(error_msg, file=sys.stderr)
        raise ValueError("CORS_ALLOWED_ORIGINS must be configured in production.")

# Additional CORS settings
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    # Default django-cors-headers
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    # 🔗 Custom header for distributed tracing
    'x-correlation-id',
    "Idempotency-Key",
]

# Sans ceci, JavaScript ne peut PAS lire ces headers à cause de CORS
CORS_EXPOSE_HEADERS = [
    "Idempotency-Key",
    'Retry-After',      # (429 throttling)
    'X-Request-ID',     # Pour debug/tracing
    'X-Correlation-ID', # Pour distributed tracing
]


# Log CORS configuration on startup (DEBUG mode only)
if DEBUG:
    print(f"✓ CORS configuration loaded:")
    print(f"  - Allowed origins: {CORS_ALLOWED_ORIGINS}")
    print(f"  - Allow credentials: {CORS_ALLOW_CREDENTIALS}")
    print(f"  - Exposed headers: {CORS_EXPOSE_HEADERS}") 



# =========================================================================
# THROTTLING CONFIGURATION - MVP SECURITY
# =========================================================================

# Feature flag pour activer/désactiver le throttling
THROTTLING_ENABLED = env.bool('THROTTLING_ENABLED', default=True)

# Configuration par environnement
if DEBUG:
    # Dev: Plus permissif pour faciliter les tests
    THROTTLE_RATES = {
        'anon': '100/hour',      # Utilisateurs non authentifiés
        'user': '1000/hour',
        'login': '10/hour',      # Tentatives de login (par IP+email) 
        'password': '10/hour',   # Changements de mot de passe
        'sensitive': '30/hour',  # Opérations sensibles
        'burst': '100/minute',    # Anti-burst
        'registration': '5/hour', # Inscriptions
        'standard': '50/minute',  # GET endpoints (list/search/filter) - permissif en DEV
        'bulk': '5/minute',       # POST bulk operations - permissif en DEV pour tests
    }
else:
    # Production: Plus restrictif
    THROTTLE_RATES = {
        'anon': '20/hour',       
        'user': '100/hour',    
        'login': '5/hour',       # Plus strict en prod : 5 tentatives/heure
        'password': '3/hour',    
        'sensitive': '10/hour',  
        'burst': '10/minute',
        'registration': '3/hour',
        'standard': '30/minute',  #  GET endpoints - évite blocage utilisateurs normaux
        'bulk': '3/minute',       # POST bulk operations - strict pour limiter abuse'
    }


# =========================================================================
# REST OF SETTINGS.PY 
# =========================================================================


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'core',
    'apps.core_apps',
    'apps.accounts', #OBSOLETE
    'app_modules.accounts',  # New UUID-based accounts module
    'app_modules.territories',  # Territories module for sales segmentation
    'app_modules.contacts',
    'app_modules.decision_cycles',  # Decision Cycle module for sales execution
    'app_modules.activities',  # Activity module for sales execution
    'app_modules.core_modules',
    'app_modules.campaigns',
    'apps.signals',
    'apps.campaign',
    'apps.opportunities',
    'apps.sequence',
    'apps.activities',
    'apps.leads',	
    # 'apps.accounts_app.accounts',
    # 'apps.accounts_app.org_units',
    # 'apps.accounts_app.account_product_detail',
    # 'apps.accounts_app.contacts',
    'apps.LLM_calls',
    'apps.products',
    'apps.sales_insight',
    'end_users',
    'product_admin',
    "phonenumber_field",
    'django_filters',
    'debug_toolbar',
    'ops'
]

MIDDLEWARE = [
    # 1. Request ID / Correlation ID (MUST be first for distributed tracing)
    'core.logging.middlewares.RequestIdMiddleware',
    'core.logging.request_logging.RequestLoggingMiddleware',

    # No-Cache headers for API endpoints (prevents browser caching + 304 on /client/*)
    'core.middlewares.cache_headers_middleware.NoCacheHeadersMiddleware',

    # ETag caching (static assets only - API endpoints excluded via Cache-Control)
    'core.http.etag.ETagMiddleware',

    # CORS (before SecurityMiddleware to handle preflight OPTIONS)
    'corsheaders.middleware.CorsMiddleware',

    # Django security
    'django.middleware.security.SecurityMiddleware',

    # WhiteNoise static files (MUST be after SecurityMiddleware)
    # Serves static files efficiently in production without nginx/Apache
    'whitenoise.middleware.WhiteNoiseMiddleware',

    # Django core middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 7. Custom security & logging
    # 'core.middlewares.security_middleware.InputSanitizationMiddleware',
    'core.middlewares.input_sanitization.InputSanitizationMiddleware',
    'core.middlewares.middleware.LogRequestHeadersMiddleware',

    # 8. Debug toolbar (development only)
    'debug_toolbar.middleware.DebugToolbarMiddleware',

]

ROOT_URLCONF = 'salescommands.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'salescommands.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# Database
# DATABASES = {
#     'default': {
#         **env.db(),  # Load connection params from DATABASE_URL env var
#         'OPTIONS': {
#             # PostgreSQL connection options for Supabase
#             # statement_timeout: Max time for a single SQL query (10s)
#             # idle_in_transaction_session_timeout: Max idle time in transaction (10s)
#             # Both timeouts prevent long-running queries and zombie connections
#             'options': '-c statement_timeout=6000 -c idle_in_transaction_session_timeout=10000'
#         }
#     }
# }

DATABASES = {
    "default": env.db("DATABASE_URL")
}
DATABASES["default"]["OPTIONS"] = {
    "options": "-c statement_timeout=6000 -c idle_in_transaction_session_timeout=10000"
}
DATABASES["default"]["CONN_MAX_AGE"] = 600  # Reuse DB connections for 10 minutes


# ==============================
# API CACHE CONFIGURATION
# ==============================

# Préfixes des endpoints API qui doivent avoir les headers no-cache
API_ENDPOINT_PREFIXES = [
    '/client/',       # end_users endpoints
    '/app/',          # app endpoints  
    '/campaign/',     # campaign endpoints
    '/leads/',        # leads endpoints
    '/activities/',   # activities endpoints
    '/opportunities/', # opportunities endpoints
    '/signals/',      # signals endpoints
    '/insights/',     # insights endpoints
    '/product_admin/', # product admin endpoints
]

# ==============================
# SECURITY HEADERS CONFIGURATION
# ==============================

# Security headers (managed by Django SecurityMiddleware)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'

if not DEBUG:
    # Force HTTPS for all requests
    SECURE_SSL_REDIRECT = True
    
    # Secure cookie flags (HTTPS only)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year (31536000 seconds)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply to all subdomains
    SECURE_HSTS_PRELOAD = True  # Enable HSTS preload list eligibility
    
    # Note: Once HSTS is enabled and the browser caches it, you cannot
    # easily disable it. Use with caution. Consider starting with a
    # shorter duration (e.g., 300 seconds) for testing.
else:
    # Development: Allow HTTP connections
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    
    # HSTS headers will NOT be sent in development
    # This allows HTTP connections on localhost for easier testing


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

AUTH_USER_MODEL = 'end_users.User' 
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default backend
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.jwt_helpers.CustomJWTAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',

    # ===== THROTTLING CONFIGURATION (MVP) =====
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'core.throttling.StandardRateThrottle',  # 🔹 anti-burst par minute (auth only)
    ] if THROTTLING_ENABLED else [],

    'DEFAULT_THROTTLE_RATES': THROTTLE_RATES if THROTTLING_ENABLED else {},

    # ===== AUTRES CONFIGURATIONS =====
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S.%fZ',
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M:%S',
}



# Session Cookie Settings
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG  # True en production seulement
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 86400  # 24 heures

# CSRF Cookie Settings  
CSRF_COOKIE_SECURE = not DEBUG  # True en production seulement
CSRF_COOKIE_HTTPONLY = False  # False pour permettre JS de le lire (nécessaire pour AJAX)
CSRF_COOKIE_SAMESITE = 'Lax'


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),


    'ALGORITHM': 'HS256',
    'SIGNING_KEY_ADMIN': env('JWT_ADMIN_SECRET_KEY'),
    'SIGNING_KEY_USER': env('JWT_USER_SECRET_KEY'),
    'VERIFYING_KEY': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'TOKEN_USER_CLASS': 'core.jwt_helpers.CustomJWTAuthentication',

    # Cookie settings
    'AUTH_COOKIE': 'access_token',
    'AUTH_COOKIE_SECURE': True,
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SAMESITE': 'Lax',
}

ROLE_REFRESH_LIFETIMES = {
    'product_admin': timedelta(days=1),
    'user_admin': timedelta(days=1),
    'end_users': timedelta(days=7),
}


#OPEN AI

OPENAI_API_KEY= {
     "OPENAI_API_KEY": env('OPENAI_API_KEY')
} 


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# =========================================================================
# STATIC FILES CONFIGURATION - WhiteNoise for production
# =========================================================================
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# URL prefix for static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Directory where collectstatic will collect static files for production
# Render needs this to serve static files via WhiteNoise
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise storage backend with compression and caching
# Only used in production (DEBUG=False)
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    
    # WhiteNoise configuration for optimal performance
    WHITENOISE_MANIFEST_STRICT = False  # Don't fail on missing manifest entries
    WHITENOISE_AUTOREFRESH = False      # Disable in production (use manifest)
    WHITENOISE_USE_FINDERS = False      # Use collected files only
    
    # Compression settings (gzip + brotli)
    WHITENOISE_SKIP_COMPRESS_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'gz', 'tgz', 'bz2', 'tbz', 'xz', 'br', 'swf', 'flv', 'woff', 'woff2']
else:
    # Development: Use default storage (no compression)
    # Django's built-in static files serving via runserver
    pass

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# HSTS Configuration (Production only)
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True


# =========================================================================
# CACHE CONFIGURATION - Redis with graceful fallback
# =========================================================================


CACHE_DIR = BASE_DIR / ".cache"
os.makedirs(CACHE_DIR, exist_ok=True)

REDIS_URL = env('REDIS_URL', default=None)
REDIS_THROTTLE_URL = env('REDIS_THROTTLE_URL', default=None)

def _is_redis_active(url):
    """Return True iff a Redis instance is configured and reachable (PING ok)."""
    if not url:
        return False
    try:
        import redis
        client = redis.Redis.from_url(
            url,
            socket_connect_timeout=0.5,
            socket_timeout=0.5,
            health_check_interval=0  # ping explicit below
        )
        return bool(client.ping())
    except Exception:
        return False

USE_REDIS_DEFAULT = _is_redis_active(REDIS_URL)
USE_REDIS_THROTTLE = _is_redis_active(REDIS_THROTTLE_URL)

if USE_REDIS_DEFAULT:
    # Redis cache (production/staging) — only if active
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "IGNORE_EXCEPTIONS": True,  # Graceful fallback if Redis fails at runtime
            },
            "KEY_PREFIX": "crm",
            "TIMEOUT": 300,  # 5 minutes default TTL
        }
    }

    # Optional: Dedicated Redis DB for throttling — only if active
    if USE_REDIS_THROTTLE:
        CACHES["throttle"] = {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_THROTTLE_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "IGNORE_EXCEPTIONS": True,
            },
            "KEY_PREFIX": "crm_throttle",
        }
else:
    # Fallback: File-based cache for development OR if Redis is down
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
            "LOCATION": str(CACHE_DIR),
            "TIMEOUT": None,
            "OPTIONS": {"MAX_ENTRIES": 50000},
        }
    }

# Configure DRF throttling to use dedicated cache if available
if "throttle" in CACHES:
    REST_FRAMEWORK["DEFAULT_THROTTLE_CACHE"] = "throttle"


# =========================================================================
# THROTTLE WHITELIST (OPTIONNEL)
# =========================================================================

# IPs ou ranges à exclure du throttling (ex: monitoring, CI/CD)
# THROTTLE_WHITELIST_IPS = env.list('THROTTLE_WHITELIST_IPS', default=[
#     '127.0.0.1',  # Localhost
#     # '10.0.0.0/8',  # Réseau interne (décommenter si nécessaire)
# ])
THROTTLE_WHITELIST_IPS=env.list('THROTTLE_WHITELIST_IPS', default=[])

# Utilisateurs à exclure du throttling (par email ou ID)
THROTTLE_WHITELIST_USERS = env.list('THROTTLE_WHITELIST_USERS', default=[
    # 'admin@yourcompany.com',
    # 'monitoring@yourcompany.com',
])

# =========================================================================
# CONFIGURATION DE MESSAGES D'ERREUR THROTTLING
# =========================================================================

# Messages personnalisés pour les erreurs de throttling
THROTTLE_ERROR_MESSAGES = {
    'anon': 'Too many requests from this IP. Please try again later.',
    'user': 'You have exceeded the rate limit. Please slow down your requests.',
    'login': 'Too many login attempts BUBU. Please wait before trying again.',
    'password': 'Too many password change attempts. Please wait before trying again.',
    'sensitive': 'This action has been rate limited for security. Please try again later.',
}

# =========================================================================
# MONITORING & ALERTING (OPTIONNEL)
# =========================================================================

# Seuils d'alerte pour le monitoring
THROTTLE_ALERT_THRESHOLDS = {
    'login_attempts_per_hour': 50,  # Alerter si plus de 50 tentatives de login/heure depuis une IP
    'user_requests_per_minute': 20,  # Alerter si un user fait plus de 20 requêtes/minute
    'total_throttled_per_hour': 100,  # Alerter si plus de 100 requêtes throttled/heure globalement
}



# ========================================================================
# PERMISSIONS CONFIGURATION
# ========================================================================

PERMISSIONS_CONFIG = {
    # Master kill switch - set to True to enable the permission system globally
    'GLOBAL_ENABLED': True,  # Start with False for safety
    
    # Debug mode - adds permission info to response headers (only in DEBUG=True)
    'DEBUG': True,
    
    # Audit logging - logs all permission checks
    'AUDIT_ENABLED': True,
    
    # Cache timeout for permission decisions (in seconds)
    'CACHE_TIMEOUT': 300,  # 5 minutes
    
    # Logger name for audit logs
    'AUDIT_LOGGER': 'permissions.audit',
    
    # Enable object-level permission checks (more expensive)
    'ENABLE_OBJECT_PERMISSIONS': False,
    
    # Strict mode - if True, any error results in permission denied
    'STRICT_MODE': False,  # Set to True in production
    
    # Module-by-module feature flags
    # Enable modules one by one for gradual rollout
    'MODULES': {
        'accounts': True,      # Account management
        'contacts': True,      # Contact management 
        'decision_cycles': True, # Decision Cycle module
        'activities': True,    # Activity tracking
        'leads': False,         # Lead management
        'opportunities': False, # Opportunity/deals
        'campaign': False,      # Campaign management
        'pipelines': False,     # Buying process/pipelines
        'templates': False,     # Email/doc templates
        'users': True,         # User management
        'products': False,      # Product catalog
    }
}

# ========================================================================
# PERMISSION SYSTEM INITIALIZATION CHECK
# ========================================================================

# Add this at the end of settings.py to verify configuration on startup
def check_permission_config():
    """Validate permission configuration on startup."""
    if PERMISSIONS_CONFIG.get('GLOBAL_ENABLED'):
        enabled_modules = [
            module for module, enabled in PERMISSIONS_CONFIG['MODULES'].items() 
            if enabled
        ]
        if not enabled_modules:
            import warnings
            warnings.warn(
                "Permission system is globally enabled but no modules are activated. "
                "Enable specific modules in PERMISSIONS_CONFIG['MODULES']."
            )
        else:
            print(f"✓ Permission system enabled for modules: {', '.join(enabled_modules)}")
    else:
        print("✓ Permission system is currently DISABLED (GLOBAL_ENABLED=False)")

# Run the check (comment out in production)
if DEBUG:
    check_permission_config()

# ========================================
# LOGGING CONFIGURATION 
# ========================================

# Feature flag to enable header logging in production
# Set LOG_HEADERS_IN_PROD=true in environment to enable
LOG_HEADERS_IN_PROD = env.bool('LOG_HEADERS_IN_PROD', default=False)

# Allowlist of headers to log in production (case-insensitive)
# These headers provide useful debugging info without exposing sensitive data
LOG_HEADERS_ALLOWLIST = [
    'x-request-id',        # Correlation ID from proxies/LB
    'x-forwarded-for',     # Original client IP through proxies
    'x-real-ip',           # Alternative client IP header
    'cf-connecting-ip',    # Cloudflare's client IP header
    'user-agent',          # Browser/client identification
    'content-type',        # Request content type
    'x-forwarded-proto',   # Original protocol (http/https)
    'x-forwarded-host',    # Original host header
    'referer',             # Referrer for tracking navigation
    'accept',              # Content negotiation
    'accept-language',     # Language preferences
    'x-csrf-token',        # CSRF token (already public)
]

# Additional paths to exclude from logging (beyond defaults)
# Add paths here that are specific to your deployment
LOGGING_EXCLUDED_PATHS = {
    # '/api/v1/internal/health',
    # '/api/v1/internal/metrics',
}

# =========================================================================
# LOGGING CONFIGURATION - MVP + AUDIT + THROTTLING
# =========================================================================


import time
import logging
import logging.handlers
import datetime

class UTCFormatter(logging.Formatter):
    """
    Formatter that converts timestamp to UTC with proper milliseconds.
    Override formatTime to handle ISO-8601 format correctly.
    """
    converter = time.gmtime  # Keep UTC
    
    def formatTime(self, record, datefmt=None):
        """
        Format time as ISO-8601 with milliseconds in UTC.
        
        Args:
            record: LogRecord instance
            datefmt: Ignored (we always use ISO format)
            
        Returns:
            str: ISO-8601 formatted timestamp with milliseconds
        """
        # Convert timestamp to datetime in UTC
        dt = datetime.datetime.fromtimestamp(record.created, datetime.timezone.utc)
        
        # Format as ISO-8601 with milliseconds, replace +00:00 with Z
        # timespec='milliseconds' gives us .123 format
        return dt.isoformat(timespec='milliseconds').replace('+00:00', 'Z')

# Custom filter for safe logging (sanitization + default values)
class SafeExtraFilter(logging.Filter):
    """
    Filter that:
    1. Injects default values for missing context keys (avoid KeyError)
    2. Sanitizes sensitive data (passwords, tokens, emails, etc.)
    3. Truncates large values to prevent log bloat
    """
    
    # Default values for structured logging keys
    DEFAULTS = {
        'correlation_id': '-',
        'user_id': '-', 
        'client_id': '-',
        'method': '-',
        'path': '-',
        'status_code': '-',
        'duration_ms': '-',
        'remote_ip': '-',

        # 🔹 Champs d'audit SOC 2
        'event': '-',
        'action': '-',
        'actor_id': '-',
        'target_type': '-',
        'target_id': '-',
        'target_count': '-',
        'fields_changed': '-',
        'outcome': '-',
        'reason': '-',
    }
    
    # Sensitive keys to mask (case-insensitive substring match)
    SENSITIVE_PATTERNS = [
        'password', 'token', 'authorization', 'cookie', 
        'secret', 'api_key', 'jwt', 'bearer'
    ]
    
    # Keys containing payloads to fully redact
    PAYLOAD_KEYS = ['body', 'request_data', 'payload']
    
    # Built-in LogRecord attributes to skip
    BUILTIN_ATTRS = {
        'name', 'msg', 'args', 'created', 'filename', 'funcName', 
        'levelname', 'levelno', 'lineno', 'module', 'msecs', 
        'message', 'pathname', 'process', 'processName', 
        'relativeCreated', 'stack_info', 'thread', 'threadName', 
        'exc_info', 'exc_text', 'stack_info', 'getMessage'
    }
    
    def filter(self, record):
        """Process each log record for safety"""
        
        # 1. Inject default values for missing keys
        for key, default_value in self.DEFAULTS.items():
            if not hasattr(record, key):
                setattr(record, key, default_value)
        
        # 2. Sanitize all extra attributes (iterate on __dict__ for performance)
        for attr_name, attr_value in list(record.__dict__.items()):
            # Skip built-in attributes
            if attr_name.startswith('_') or attr_name in self.BUILTIN_ATTRS:
                continue
            
            # Skip if None or already a default value
            if attr_value is None or attr_value in self.DEFAULTS.values():
                continue
                
            # Convert to string for processing
            attr_value_str = str(attr_value)
            attr_name_lower = attr_name.lower()
            
            # 2a. Redact payload/body completely
            if any(payload_key in attr_name_lower for payload_key in self.PAYLOAD_KEYS):
                setattr(record, attr_name, '[PAYLOAD_REDACTED]')
                continue
            
            # 2b. Check for sensitive patterns
            is_sensitive = any(pattern in attr_name_lower for pattern in self.SENSITIVE_PATTERNS)
            
            if is_sensitive:
                # Mask the value
                if '@' in attr_value_str and '.' in attr_value_str:
                    # Email-like value
                    setattr(record, attr_name, self._mask_email(attr_value_str))
                else:
                    # Generic sensitive data
                    setattr(record, attr_name, '[REDACTED]')
                continue
            
            # 2c. Check value content for emails (even in non-sensitive keys)
            if '@' in attr_value_str and '.' in attr_value_str and len(attr_value_str) < 100:
                # Likely an email, mask it
                setattr(record, attr_name, self._mask_email(attr_value_str))
                continue
            
            # 2d. Truncate large values
            if len(attr_value_str) > 2000:
                setattr(record, attr_name, attr_value_str[:2000] + '[TRUNCATED_2000]')
        
        return True
    
    def _mask_email(self, email):
        """Mask email keeping domain: j***@domain.com"""
        try:
            if '@' in email:
                local, domain = email.split('@', 1)
                if len(local) > 0:
                    masked = local[0] + '***@' + domain
                    return masked
            return email
        except:
            return '[EMAIL_REDACTED]'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    'formatters': {
        'structured': {
            '()': UTCFormatter,
            'format': (
                'timestamp=%(asctime)s '
                'level=%(levelname)s '
                'logger=%(name)s '
                'msg="%(message)s" '
                # 🔹 Audit
                'event=%(event)s '
                'action=%(action)s '
                'actor_id=%(actor_id)s '
                'target_type=%(target_type)s '
                'target_id=%(target_id)s '
                'target_count=%(target_count)s '
                'fields_changed=%(fields_changed)s '
                'outcome=%(outcome)s '
                'reason="%(reason)s" '
                # 🔹 Contexte HTTP
                'file=%(module)s '
                'line=%(lineno)d '
                'func=%(funcName)s '
                'correlation_id=%(correlation_id)s '
                'user_id=%(user_id)s '
                'client_id=%(client_id)s '
                'method=%(method)s '
                'path="%(path)s" '
                'status=%(status_code)s '
                'duration_ms=%(duration_ms)s '
                'ip=%(remote_ip)s'
            )
        }
    },
    
    'filters': {
        'safe_extra': {
            '()': SafeExtraFilter,
        }
    },
    
    'handlers': {},
    
    'loggers': {
        'backend': {
            'handlers': [],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': [],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': [],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': [],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': [],
            'level': 'WARNING',
            'propagate': False,
        },
        # 🔹 Audit app
        'audit': {
            'handlers': [],
            'level': 'INFO',
            'propagate': False,
        },
        'permissions.audit': {
            'handlers': [],
            'level': 'INFO',
            'propagate': False,
        },
        # 🔹 Throttling
        'rest_framework.throttling': {
            'handlers': [],
            'level': 'INFO',
            'propagate': False,
        },
        'core.throttling': {
            'handlers': [],
            'level': 'WARNING',
            'propagate': False,
        },
    },
    
    'root': {
        'handlers': [],
        'level': 'DEBUG' if DEBUG else 'INFO',
    }
}

# ========================================
# INPUT SANITIZATION CONFIG
# ========================================

# "log" pour observer ce qui serait bloqué sans retourner 403
# "block" pour activer le blocage réel
INPUT_SANITIZATION_MODE = "block"

# Préfixes d'URL à exclure (ancien comportement sur /insights/)
INPUT_SANITIZATION_EXCLUDED_PREFIXES = [
    '/insights/',
]

# Si True : un JSON invalide est traité comme suspect et peut être bloqué
# Si False : on laisse la view/DRF gérer l'erreur de JSON
INPUT_SANITIZATION_BLOCK_INVALID_JSON = False


# ==========
# HANDLERS
# ==========

# ✅ Crée toujours le dossier logs/ pour ne pas l'oublier
logs_dir = BASE_DIR / 'logs'
logs_dir.mkdir(parents=True, exist_ok=True)

enable_file_logs = os.getenv('ENABLE_FILE_LOGS', '').lower() in {'1', 'true', 'yes'}
use_files = enable_file_logs

LOGGING['handlers']['console'] = {
    'class': 'logging.StreamHandler',
    'formatter': 'structured',
    'filters': ['safe_extra'],
}

if use_files:
    LOGGING['handlers']['file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': str(logs_dir / 'app.log'),
        'maxBytes': 10 * 1024 * 1024,
        'backupCount': 5,
        'formatter': 'structured',
        'filters': ['safe_extra'],
    }
    LOGGING['handlers']['error_file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': str(logs_dir / 'error.log'),
        'maxBytes': 10 * 1024 * 1024,
        'backupCount': 5,
        'formatter': 'structured',
        'filters': ['safe_extra'],
        'level': 'WARNING',
    }
    LOGGING['handlers']['audit_file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': str(logs_dir / 'audit.log'),
        'maxBytes': 10 * 1024 * 1024,
        'backupCount': 10,
        'formatter': 'structured',
        'filters': ['safe_extra'],
        'level': 'INFO',
    }
    LOGGING['handlers']['throttle_file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': str(logs_dir / 'throttle.log'),
        'maxBytes': 5 * 1024 * 1024,
        'backupCount': 3,
        'formatter': 'structured',
        'filters': ['safe_extra'],
        'level': 'WARNING',
    }

active_handlers = ['console'] + (['file', 'error_file'] if use_files else [])

# ==========
# ASSIGNATION DES HANDLERS
# ==========

for logger_name, logger_cfg in LOGGING['loggers'].items():
    if logger_name in ('audit', 'permissions.audit'):
        # Audit → console + audit_file
        logger_cfg['handlers'] = ['console'] + (['audit_file'] if use_files else [])
    elif logger_name in ('rest_framework.throttling', 'core.throttling'):
        # Throttling → console + throttle_file
        logger_cfg['handlers'] = ['console'] + (['throttle_file'] if use_files else [])
    else:
        # Le reste → console + app/error logs
        logger_cfg['handlers'] = active_handlers

LOGGING['root']['handlers'] = active_handlers

if DEBUG:
    import sys
    config_msg = f"Logging configured: file_logs={use_files}, handlers={active_handlers}"
    print(f"[LOGGING] {config_msg}", file=sys.stderr)