# Generated by Django 5.1.4 on 2025-03-01 10:03

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('end_users', '0001_initial'),
        ('org_units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('post_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Post Code')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State/Region')),
                ('country', models.CharField(choices=[('AD', 'Andorra'), ('AE', 'United Arab Emirates'), ('AF', 'Afghanistan'), ('AG', 'Antigua and Barbuda'), ('AI', 'Anguilla'), ('AL', 'Albania'), ('AM', 'Armenia'), ('AO', 'Angola'), ('AR', 'Argentina'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BA', 'Bosnia and Herzegovina'), ('BB', 'Barbados'), ('BD', 'Bangladesh'), ('BE', 'Belgium'), ('BF', 'Burkina Faso'), ('BG', 'Bulgaria'), ('BH', 'Bahrain'), ('BI', 'Burundi'), ('BJ', 'Benin'), ('BR', 'Brazil'), ('CA', 'Canada'), ('CN', 'China'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('DE', 'Germany'), ('DK', 'Denmark'), ('DO', 'Dominican Republic'), ('DZ', 'Algeria'), ('EC', 'Ecuador'), ('EE', 'Estonia'), ('EG', 'Egypt'), ('ES', 'Spain'), ('FI', 'Finland'), ('FR', 'France'), ('GB', 'United Kingdom'), ('GR', 'Greece'), ('HU', 'Hungary'), ('ID', 'Indonesia'), ('IE', 'Ireland'), ('IN', 'India'), ('IT', 'Italy'), ('JP', 'Japan'), ('KE', 'Kenya'), ('KR', 'South Korea'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MX', 'Mexico'), ('NG', 'Nigeria'), ('NL', 'Netherlands'), ('NO', 'Norway'), ('NZ', 'New Zealand'), ('PK', 'Pakistan'), ('PL', 'Poland'), ('PT', 'Portugal'), ('RU', 'Russia'), ('SA', 'Saudi Arabia'), ('SE', 'Sweden'), ('SG', 'Singapore'), ('TH', 'Thailand'), ('TR', 'Turkey'), ('UA', 'Ukraine'), ('US', 'United States'), ('VN', 'Vietnam'), ('ZA', 'South Africa'), ('ZW', 'Zimbabwe')], default='US', max_length=2, verbose_name='Country')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Invalid phone number format'}, max_length=20, null=True, region=None, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, error_messages={'invalid': 'Invalid URL format'}, null=True, verbose_name='Website')),
                ('linkedin', models.URLField(blank=True, error_messages={'invalid': 'Invalid URL format'}, null=True, verbose_name='LinkedIn Profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('objectives', models.JSONField(blank=True, null=True, verbose_name='Objectives')),
                ('compelling_events', models.JSONField(blank=True, null=True, verbose_name='Compelling Events')),
                ('motivations', models.JSONField(blank=True, null=True, verbose_name='Motivations')),
                ('key_kpis', models.JSONField(blank=True, null=True, verbose_name='Key KPIs')),
                ('criteria', models.JSONField(blank=True, null=True, verbose_name='Criteria')),
                ('pain_points', models.JSONField(blank=True, null=True, verbose_name='Pain Points')),
                ('implications', models.JSONField(blank=True, null=True, verbose_name='Implications')),
                ('current_tech_stack', models.JSONField(blank=True, null=True, verbose_name='Current Tech Stack')),
                ('partners', models.JSONField(blank=True, null=True, verbose_name='Partners')),
                ('buying_process', models.JSONField(blank=True, null=True, verbose_name='Buying Process')),
                ('projects', models.JSONField(blank=True, null=True, verbose_name='Projects')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Budget')),
                ('new_budget_start_date', models.DateField(blank=True, null=True, verbose_name='New Budget Start Date')),
                ('historical_data', models.JSONField(blank=True, null=True, verbose_name='Historical Data')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title')),
                ('influence_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Influence Level')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.account', verbose_name='Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='org_units.accountorganizationunit', verbose_name='Organization Unit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
                'ordering': ['-created_at', 'last_name', 'first_name'],
                'abstract': False,
                'indexes': [models.Index(fields=['first_name', 'last_name', 'client_id'], name='contacts_first_n_70c452_idx')],
                'unique_together': {('account', 'email', 'client_id')},
            },
        ),
    ]
