# Generated by Django 5.1.4 on 2025-03-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='signal_metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Signal Metadata'),
        ),
    ]
