# Generated by Django 5.1.4 on 2025-01-18 10:48

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('end_users', '0003_user_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.UUIDField(db_index=True, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('post_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Post Code')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State/Region')),
                ('country', models.CharField(choices=[('AD', 'Andorra'), ('AE', 'United Arab Emirates'), ('AF', 'Afghanistan'), ('AG', 'Antigua and Barbuda'), ('AI', 'Anguilla'), ('AL', 'Albania'), ('AM', 'Armenia'), ('AO', 'Angola'), ('AR', 'Argentina'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BA', 'Bosnia and Herzegovina'), ('BB', 'Barbados'), ('BD', 'Bangladesh'), ('BE', 'Belgium'), ('BF', 'Burkina Faso'), ('BG', 'Bulgaria'), ('BH', 'Bahrain'), ('BI', 'Burundi'), ('BJ', 'Benin'), ('BR', 'Brazil'), ('CA', 'Canada'), ('CN', 'China'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('DE', 'Germany'), ('DK', 'Denmark'), ('DO', 'Dominican Republic'), ('DZ', 'Algeria'), ('EC', 'Ecuador'), ('EE', 'Estonia'), ('EG', 'Egypt'), ('ES', 'Spain'), ('FI', 'Finland'), ('FR', 'France'), ('GB', 'United Kingdom'), ('GR', 'Greece'), ('HU', 'Hungary'), ('ID', 'Indonesia'), ('IE', 'Ireland'), ('IN', 'India'), ('IT', 'Italy'), ('JP', 'Japan'), ('KE', 'Kenya'), ('KR', 'South Korea'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MX', 'Mexico'), ('NG', 'Nigeria'), ('NL', 'Netherlands'), ('NO', 'Norway'), ('NZ', 'New Zealand'), ('PK', 'Pakistan'), ('PL', 'Poland'), ('PT', 'Portugal'), ('RU', 'Russia'), ('SA', 'Saudi Arabia'), ('SE', 'Sweden'), ('SG', 'Singapore'), ('TH', 'Thailand'), ('TR', 'Turkey'), ('UA', 'Ukraine'), ('US', 'United States'), ('VN', 'Vietnam'), ('ZA', 'South Africa'), ('ZW', 'Zimbabwe')], default='US', max_length=2, verbose_name='Country')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry')),
                ('type', models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('PROSPECT', 'Prospect'), ('PARTNER', 'Partner'), ('VENDOR', 'Vendor'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Account Type')),
                ('classification', models.CharField(blank=True, choices=[('SMB', 'Small and Medium Business'), ('ENTERPRISE', 'Enterprise'), ('STARTUP', 'Startup'), ('NONPROFIT', 'Non-Profit')], max_length=50, null=True, verbose_name='Account Classification')),
                ('number_of_employees', models.CharField(blank=True, null=True, verbose_name='Number of Employees')),
                ('potential', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Potential Revenue')),
                ('account_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='end_users.user', verbose_name='Account Owner')),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_child_companies', to='accounts.account', verbose_name='Parent Company')),
                ('team_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='end_users.team', verbose_name='Team Owner')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'company_accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_name'], name='company_acc_company_08dd13_idx'), models.Index(fields=['account_owner'], name='company_acc_account_53b95a_idx'), models.Index(fields=['team_owner'], name='company_acc_team_ow_322cc4_idx')],
            },
        ),
    ]
