# Generated by Django 5.1.4 on 2024-12-18 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='child_companies',
            field=models.ManyToManyField(blank=True, help_text='Links to child companies if this is a parent company.', related_name='parent_companies', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent_company',
            field=models.ForeignKey(blank=True, help_text='Link to a parent company if this is a child company.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_child_companies', to='accounts.account'),
        ),
    ]
