# Generated by Django 5.1.4 on 2025-01-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='company_acc_company_08dd13_idx',
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('company_name', 'city', 'country', 'client_id')},
        ),
    ]
