# Generated by Django 5.1.4 on 2025-03-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_new', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='compelling_events',
        ),
        migrations.RemoveField(
            model_name='account',
            name='coverage_stats',
        ),
        migrations.RemoveField(
            model_name='account',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='account',
            name='key_kpis',
        ),
        migrations.AddField(
            model_name='account',
            name='metrics',
            field=models.JSONField(blank=True, null=True, verbose_name='Metrics'),
        ),
        migrations.AddField(
            model_name='account',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='partnered_with', to='accounts_new.account', verbose_name='Partners'),
        ),
    ]
