# Generated by Django 5.1.4 on 2025-04-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='has_buying_authority',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has Buying Authority'),
        ),
    ]
