# Generated by Django 5.1.4 on 2025-04-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_contact_has_buying_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='historical_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Historical Data'),
        ),
    ]
