# Generated by Django 5.1.4 on 2025-03-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_new', '0002_remove_account_compelling_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_buying_decision',
            field=models.BooleanField(default=True, help_text='Indicates if this account has authority to make buying decisions', verbose_name='Has Buying Decision'),
        ),
    ]
