# Generated by Django 5.1.4 on 2024-12-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_child_companies_alter_account_parent_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dummy_field',
            field=models.BooleanField(default=False),
        ),
    ]
