# Generated by Django 5.1.4 on 2025-03-26 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_new', '0003_account_has_buying_decision'),
        ('core_apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='buying_authority',
            new_name='has_buying_authority',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='criteria',
        ),
        migrations.AddField(
            model_name='contact',
            name='metrics',
            field=models.JSONField(blank=True, null=True, verbose_name='Metrics'),
        ),
        migrations.AddField(
            model_name='contact',
            name='motivations',
            field=models.JSONField(blank=True, null=True, verbose_name='Motivations'),
        ),
        migrations.AddField(
            model_name='contact',
            name='standard_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='core_apps.standarddepartment', verbose_name='Standard Department'),
        ),
    ]
