# Generated by Django 5.1.4 on 2025-04-07 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_techstack_historical_data'),
        ('core_apps', '0001_initial'),
        ('products', '0002_remove_product_potential_cons_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyingprocessstep',
            options={'ordering': ['id'], 'verbose_name': 'Buying Process Step', 'verbose_name_plural': 'Buying Process Steps'},
        ),
        migrations.AlterUniqueTogether(
            name='buyingprocess',
            unique_together={('account', 'name'), ('account', 'product')},
        ),
        migrations.RemoveField(
            model_name='buyingprocessstep',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='buyingprocessstep',
            name='depends_on_steps',
        ),
        migrations.RemoveField(
            model_name='buyingprocessstep',
            name='step_index',
        ),
        migrations.AddField(
            model_name='buyingprocessstep',
            name='previous_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_steps', to='accounts.buyingprocessstep', verbose_name='Previous Step'),
        ),
        migrations.AddField(
            model_name='buyingprocessstep',
            name='standard_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_apps.standarddepartment', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='buyingprocessstep',
            name='average_time_in_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Average Time in Days'),
        ),
        migrations.RemoveField(
            model_name='buyingprocess',
            name='estimated_timeline_days',
        ),
        migrations.RemoveField(
            model_name='buyingprocess',
            name='status',
        ),
    ]
