# Generated by Django 5.1.4 on 2024-12-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='dummy_field',
        ),
        migrations.RemoveField(
            model_name='account',
            name='child_companies',
        ),
        migrations.AddField(
            model_name='account',
            name='child_companies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
