# Generated by Django 5.1.4 on 2024-12-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_dummy_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='child_companies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
