# Generated by Django 5.1.4 on 2025-04-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_buyingprocessstep_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='implications',
        ),
        migrations.RemoveField(
            model_name='account',
            name='metrics',
        ),
        migrations.RemoveField(
            model_name='account',
            name='motivations',
        ),
        migrations.RemoveField(
            model_name='account',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='account',
            name='pain_points',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='historical_data',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='metrics',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='motivations',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='pain_points',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='signal_metadata',
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='annual_cost',
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='pros',
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='renewal_date',
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='years_of_usage',
        ),
    ]
