# Generated by Django 5.1.4 on 2025-03-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_new', '0004_rename_buying_authority_contact_has_buying_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
