# Generated by Django 5.1.4 on 2024-12-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_child_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='child_companies',
        ),
    ]
