# Generated by Django 5.1.4 on 2025-04-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_implications_remove_account_metrics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='historical_data',
        ),
        migrations.RemoveField(
            model_name='account',
            name='signal_metadata',
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='historical_data',
        ),
    ]
