# Generated by Django 5.1.4 on 2025-05-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_account_historical_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_is_valid',
            field=models.BooleanField(default=True, help_text='Whether the email address is valid and not bouncing', verbose_name='Email is Valid'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_is_valid',
            field=models.BooleanField(default=True, help_text='Whether the phone number is valid and reachable', verbose_name='Phone is Valid'),
        ),
        migrations.AddField(
            model_name='account',
            name='tier',
            field=models.CharField(choices=[('A', 'Tier A - High Priority'), ('B', 'Tier B - Medium Priority'), ('C', 'Tier C - Low Priority')], default='C', help_text='Account priority for campaign management', max_length=1, verbose_name='Account Tier'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_is_valid',
            field=models.BooleanField(default=True, help_text='Whether the email address is valid and not bouncing', verbose_name='Email is Valid'),
        ),
        migrations.AddField(
            model_name='contact',
            name='opted_out',
            field=models.BooleanField(default=False, help_text='Whether the contact has opted out of communications', verbose_name='Opted Out'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_is_valid',
            field=models.BooleanField(default=True, help_text='Whether the phone number is valid and reachable', verbose_name='Phone is Valid'),
        ),
    ]
