# Generated by Django 5.1.4 on 2024-12-18 16:25

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_account_child_companies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_child_company',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_parent_company',
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='account',
            name='classification',
            field=models.CharField(blank=True, choices=[('SMB', 'Small and Medium Business'), ('ENTERPRISE', 'Enterprise'), ('STARTUP', 'Startup'), ('NONPROFIT', 'Non-Profit')], max_length=50, null=True, verbose_name='Account Classification'),
        ),
        migrations.AlterField(
            model_name='account',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='account',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='account',
            name='number_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Employees'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_child_companies', to='accounts.account', verbose_name='Parent Company'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Post Code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='potential',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Potential Revenue'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('PROSPECT', 'Prospect'), ('PARTNER', 'Partner'), ('VENDOR', 'Vendor')], max_length=50, null=True, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
