# Generated by Django 5.1.4 on 2025-12-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_email_is_valid_account_phone_is_valid_and_more'),
        ('core_modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingprocessstep',
            name='standard_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_modules.standarddepartment', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='standard_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='core_modules.standarddepartment', verbose_name='Standard Department'),
        ),
    ]
