# Generated by Django 5.1.4 on 2024-12-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='account',
            name='number_of_employees',
            field=models.CharField(blank=True, null=True, verbose_name='Number of Employees'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
