# Generated by Django 5.1.4 on 2025-01-09 10:40

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('PROSPECT', 'Prospect'), ('PARTNER', 'Partner'), ('VENDOR', 'Vendor'), ('OTHER', 'Other')], max_length=50, null=True, verbose_name='Account Type'),
        ),
    ]
