# Generated by Django 5.1.4 on 2025-03-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='signal_metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Signal Metadata'),
        ),
    ]
