# Generated by Django 5.1.4 on 2025-01-27 08:34

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_company_acc_company_08dd13_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='classification',
            field=models.CharField(blank=True, choices=[('SMB', 'Small and Medium Business'), ('MIDMARKET', 'Mid-Market'), ('ENTERPRISE', 'Enterprise'), ('STARTUP', 'Startup'), ('NONPROFIT', 'Non-Profit')], max_length=50, null=True, verbose_name='Account Classification'),
        ),
        migrations.AlterField(
            model_name='account',
            name='client_id',
            field=models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='company_name',
            field=models.CharField(error_messages={'blank': 'Company name is required', 'max_length': 'Company name exceeds maximum length of 255 characters'}, max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='linkedin',
            field=models.URLField(blank=True, error_messages={'invalid': 'Invalid URL format'}, null=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Invalid phone number format'}, max_length=20, null=True, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True, error_messages={'invalid': 'Invalid URL format'}, null=True, verbose_name='Website'),
        ),
    ]
