# Generated by Django 5.1.4 on 2025-01-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_classification_alter_account_client_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='number_of_employees',
            new_name='company_size',
        ),
        migrations.RemoveField(
            model_name='account',
            name='potential',
        ),
        migrations.AddField(
            model_name='account',
            name='annual_revenue',
            field=models.CharField(blank=True, null=True, verbose_name='Annual Revenue'),
        ),
        migrations.AddField(
            model_name='account',
            name='budgets',
            field=models.JSONField(blank=True, null=True, verbose_name='Budgets'),
        ),
        migrations.AddField(
            model_name='account',
            name='business_impact',
            field=models.JSONField(blank=True, null=True, verbose_name='Business Impact'),
        ),
        migrations.AddField(
            model_name='account',
            name='buying_process',
            field=models.JSONField(blank=True, null=True, verbose_name='Buying Process'),
        ),
        migrations.AddField(
            model_name='account',
            name='historical_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Historical Data'),
        ),
        migrations.AddField(
            model_name='account',
            name='pain_points',
            field=models.JSONField(blank=True, null=True, verbose_name='Pain Points'),
        ),
        migrations.AddField(
            model_name='account',
            name='strategic_goals',
            field=models.JSONField(blank=True, null=True, verbose_name='Strategic Goals'),
        ),
        migrations.AddField(
            model_name='account',
            name='success_criteria',
            field=models.JSONField(blank=True, null=True, verbose_name='Success Criteria'),
        ),
        migrations.AddField(
            model_name='account',
            name='technology_stack',
            field=models.JSONField(blank=True, null=True, verbose_name='Technology Stack'),
        ),
    ]
