# Generated by Django 5.1.4 on 2025-01-27 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_number_of_employees_account_company_size_and_more'),
        ('end_users', '0003_user_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='budgets',
        ),
        migrations.RemoveField(
            model_name='account',
            name='business_impact',
        ),
        migrations.RemoveField(
            model_name='account',
            name='buying_process',
        ),
        migrations.RemoveField(
            model_name='account',
            name='pain_points',
        ),
        migrations.RemoveField(
            model_name='account',
            name='strategic_goals',
        ),
        migrations.RemoveField(
            model_name='account',
            name='success_criteria',
        ),
        migrations.RemoveField(
            model_name='account',
            name='technology_stack',
        ),
        migrations.AddField(
            model_name='account',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
    ]
