# Generated by Django 5.1.4 on 2025-01-27 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_budgets_and_more'),
        ('sales_insight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_insights',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_account', to='sales_insight.salesinsight', verbose_name='Account Insights'),
        ),
    ]
