# Generated by Django 5.1.4 on 2025-01-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_account_insights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Company Name'),
        ),
    ]
