# Generated by Django 5.1.4 on 2025-01-27 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_account_account_insights'),
        ('end_users', '0003_user_role_name'),
        ('sales_insight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('organization_name', models.CharField(error_messages={'blank': 'Organization name is required', 'max_length': 'Organization name exceeds maximum length of 255 characters'}, max_length=255, verbose_name='Organization Name')),
                ('unit_type', models.CharField(choices=[('DEPARTMENT', 'Department'), ('DIVISION', 'Division'), ('TEAM', 'Team')], max_length=50, verbose_name='Unit Type')),
                ('estimated_employee_count', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.account', verbose_name='Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('org_insights', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_org', to='sales_insight.salesinsight')),
                ('parent_organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_organization_units', to='org_units.accountorganizationunit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Organization Unit',
                'ordering': ['-created_at', 'organization_name'],
                'abstract': False,
                'indexes': [models.Index(fields=['account'], name='org_units_a_account_e9d410_idx'), models.Index(fields=['parent_organization_unit'], name='org_units_a_parent__916804_idx')],
                'unique_together': {('account', 'organization_name', 'client_id')},
            },
        ),
    ]
