# Generated by Django 5.1.4 on 2025-02-26 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core_apps', '0001_initial'),
        ('end_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('objectives', models.JSONField(blank=True, null=True, verbose_name='Objectives')),
                ('compelling_events', models.JSONField(blank=True, null=True, verbose_name='Compelling Events')),
                ('motivations', models.JSONField(blank=True, null=True, verbose_name='Motivations')),
                ('key_kpis', models.JSONField(blank=True, null=True, verbose_name='Key KPIs')),
                ('criteria', models.JSONField(blank=True, null=True, verbose_name='Criteria')),
                ('pain_points', models.JSONField(blank=True, null=True, verbose_name='Pain Points')),
                ('implications', models.JSONField(blank=True, null=True, verbose_name='Implications')),
                ('current_tech_stack', models.JSONField(blank=True, null=True, verbose_name='Current Tech Stack')),
                ('partners', models.JSONField(blank=True, null=True, verbose_name='Partners')),
                ('buying_process', models.JSONField(blank=True, null=True, verbose_name='Buying Process')),
                ('projects', models.JSONField(blank=True, null=True, verbose_name='Projects')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Budget')),
                ('new_budget_start_date', models.DateField(blank=True, null=True, verbose_name='New Budget Start Date')),
                ('historical_data', models.JSONField(blank=True, null=True, verbose_name='Historical Data')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('unit_type', models.CharField(choices=[('DEPARTMENT', 'Department'), ('DIVISION', 'Division'), ('TEAM', 'Team')], max_length=50, verbose_name='Unit Type')),
                ('estimated_employee_count', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.account', verbose_name='Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('parent_organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_organization_units', to='org_units.accountorganizationunit')),
                ('standard_department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='organization_units', to='core_apps.standarddepartment', verbose_name='Standard Department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Organization Unit',
                'db_table': 'Organization_Unit',
                'ordering': ['-created_at', 'organization_name'],
                'abstract': False,
                'indexes': [models.Index(fields=['account'], name='Organizatio_account_2c8071_idx'), models.Index(fields=['parent_organization_unit'], name='Organizatio_parent__e14789_idx')],
                'unique_together': {('account', 'organization_name', 'client_id')},
            },
        ),
    ]
