# Generated by Django 5.1.4 on 2025-01-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_units', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountorganizationunit',
            new_name='Organizatio_account_40a6c3_idx',
            old_name='org_units_a_account_e9d410_idx',
        ),
        migrations.RenameIndex(
            model_name='accountorganizationunit',
            new_name='Organizatio_parent__70cd9d_idx',
            old_name='org_units_a_parent__916804_idx',
        ),
        migrations.AlterField(
            model_name='accountorganizationunit',
            name='organization_name',
            field=models.CharField(max_length=255, verbose_name='Organization Name'),
        ),
        migrations.AlterModelTable(
            name='accountorganizationunit',
            table='Organization Unit',
        ),
    ]
