# Generated by Django 5.1.4 on 2025-02-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_apps', '0002_initial'),
        ('org_units', '0002_rename_org_units_a_account_e9d410_idx_organizatio_account_40a6c3_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountorganizationunit',
            new_name='Organizatio_account_2c8071_idx',
            old_name='Organizatio_account_40a6c3_idx',
        ),
        migrations.RenameIndex(
            model_name='accountorganizationunit',
            new_name='Organizatio_parent__e14789_idx',
            old_name='Organizatio_parent__70cd9d_idx',
        ),
        migrations.AddField(
            model_name='accountorganizationunit',
            name='standard_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='organization_units', to='core_apps.standarddepartment', verbose_name='Standard Department'),
        ),
        migrations.AlterModelTable(
            name='accountorganizationunit',
            table='Organization_Unit',
        ),
    ]
