# Generated by Django 5.1.4 on 2025-02-13 10:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_account_company_name'),
        ('end_users', '0003_user_role_name'),
        ('org_units', '0003_rename_organizatio_account_40a6c3_idx_organizatio_account_2c8071_idx_and_more'),
        ('products', '0007_alter_pricing_pricing_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('estimated_units', models.PositiveIntegerField(help_text='Estimated number of units/seats for this product', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Estimated Units/Seats')),
                ('potential_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated potential revenue based on pricing and estimated units', max_digits=12, verbose_name='Potential Revenue')),
                ('revenue_type', models.CharField(choices=[('MRR', 'Monthly Recurring Revenue'), ('QRR', 'Quarterly Recurring Revenue'), ('ARR', 'Annual Recurring Revenue'), ('ONE_TIME', 'One Time Payment')], max_length=10, verbose_name='Revenue Type')),
                ('ai_relevance_score', models.FloatField(blank=True, help_text='AI-generated score for product relevance to this account', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='AI Relevance Score')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about product potential in this account', verbose_name='Analysis Notes')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.account', verbose_name='Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to='products.product', verbose_name='Product')),
                ('selected_pricing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_potentials', to='products.pricing', verbose_name='Selected Pricing Model')),
                ('target_org_units', models.ManyToManyField(related_name='product_potentials', to='org_units.accountorganizationunit', verbose_name='Target Organization Units')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Account Product Detail',
                'verbose_name_plural': 'Account Product Details',
                'db_table': 'account_product_details',
                'ordering': ['-potential_revenue', 'product__product_name'],
                'abstract': False,
                'indexes': [models.Index(fields=['revenue_type', 'client_id'], name='account_pro_revenue_4a2022_idx')],
                'unique_together': {('account', 'product', 'client_id')},
            },
        ),
    ]
