# Generated by Django 5.1.4 on 2025-03-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_product_detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountproductdetail',
            name='historical_data',
            field=models.JSONField(blank=True, help_text='Stores changes in key fields over time', null=True, verbose_name='Historical Data'),
        ),
    ]
