# Generated by Django 5.1.4 on 2025-03-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_product_detail', '0002_accountproductdetail_historical_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountproductdetail',
            name='coverage_stats',
            field=models.JSONField(blank=True, help_text='Statistical metrics about product coverage', null=True, verbose_name='Coverage Statistics'),
        ),
        migrations.AddField(
            model_name='accountproductdetail',
            name='economic_impact',
            field=models.JSONField(blank=True, help_text='Economic impact analysis of the product for this account', null=True, verbose_name='Economic Impact'),
        ),
        migrations.AddField(
            model_name='accountproductdetail',
            name='last_analysis_date',
            field=models.DateTimeField(blank=True, help_text='When the product alignment was last analyzed', null=True, verbose_name='Last Analysis Date'),
        ),
        migrations.AddField(
            model_name='accountproductdetail',
            name='objectives_alignment',
            field=models.JSONField(blank=True, help_text='Alignment between account objectives and product benefits', null=True, verbose_name='Objectives Alignment'),
        ),
        migrations.AddField(
            model_name='accountproductdetail',
            name='pain_points_coverage',
            field=models.JSONField(blank=True, help_text='Coverage of account pain points by product features', null=True, verbose_name='Pain Points Coverage'),
        ),
    ]
