# Generated by Django 5.1.4 on 2025-03-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_product_detail', '0003_accountproductdetail_coverage_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountproductdetail',
            name='tech_relationships',
            field=models.JSONField(blank=True, help_text="Relationships between this product and customer's existing technologies", null=True, verbose_name='Tech Stack Relationships'),
        ),
    ]
