# Generated by Django 5.1.4 on 2025-03-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_product_detail', '0004_accountproductdetail_tech_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountproductdetail',
            name='buying_process',
            field=models.JSONField(blank=True, help_text='Structured representation of the customer buying process', null=True, verbose_name='Buying Process'),
        ),
        migrations.AddField(
            model_name='accountproductdetail',
            name='sales_cycle_estimated_days',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated total duration of the sales cycle in days', null=True, verbose_name='Estimated Sales Cycle (Days)'),
        ),
    ]
