# Generated by Django 5.1.4 on 2025-12-17 15:29
"""
StandardDepartment retirement from `apps.core_apps`.

Wrapped in SeparateDatabaseAndState — physical table is owned by
app_modules.core_modules and MUST remain after this migration. State-only
operation; the database is left intact. See chore sprint PR #7
(chore/fix-pre-existing-migration-drifts) for the full rationale.

Migration architecture in short
-------------------------------
Two apps both declare a model whose `db_table` is 'standard_departments':
  * apps.core_apps.StandardDepartment (legacy — deleted from Python in
    the chore sprint; the migration files remain in the historical chain).
  * app_modules.core_modules.StandardDepartment (canonical — registered
    state-only by core_modules.0001_initial pointing at the same physical
    table created here in core_apps.0001_initial).

The intended sequence on a fresh database is:

  apps.core_apps.0001_initial              (CREATE TABLE — table exists)
  legacy FK creations target core_apps.standarddepartment
  app_modules.core_modules.0001_initial    (STATE ONLY — no CREATE TABLE)
  AlterField repoints                       (FKs move to core_modules.standarddepartment)
  apps.core_apps.0002_delete_standarddepartment  (STATE ONLY — no DROP TABLE)
                                            ← THIS MIGRATION

This migration is the final step. It removes core_apps.StandardDepartment
from the migration state. The physical table is preserved because it
now belongs to core_modules.StandardDepartment, which all live FKs in
the codebase reference.

Production safety
-----------------
Existing production databases have this migration already applied
(presumably with the original destructive `DeleteModel`, when the
historical state allowed it — i.e. before core_modules.StandardDepartment
existed). Django never replays applied migrations, so the
SeparateDatabaseAndState wrapper has zero observable effect on those
databases. Only fresh databases (CI / new dev environments / pytest
with --create-db) replay the chain and benefit from the wrapper.

Dependencies on the four FK-repoint migrations
----------------------------------------------
This migration must run AFTER every migration that repoints a FK from
core_apps.standarddepartment to core_modules.standarddepartment.
Otherwise those repoints would run after core_apps.StandardDepartment
has been removed from state and crash with
`ValueError: Related model 'core_apps.standarddepartment' cannot be resolved`.

The four repoint migrations are:
  * apps.accounts.0008_alter_buyingprocessstep_standard_department_and_more
  * apps.signals.0004_alter_profilesignal_source_department_and_more
  * apps.products.0003_alter_product_target_categories
  * apps.opportunities.0013_alter_substagemetadata_department
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_apps', '0001_initial'),
        # See module docstring — every migration repointing a FK from
        # core_apps.standarddepartment to core_modules.standarddepartment
        # must complete before we remove core_apps.StandardDepartment
        # from state. Pinning these four deps guarantees the safe order
        # under any topological sort Django produces.
        ('accounts', '0008_alter_buyingprocessstep_standard_department_and_more'),
        ('signals', '0004_alter_profilesignal_source_department_and_more'),
        ('products', '0003_alter_product_target_categories'),
        ('opportunities', '0013_alter_substagemetadata_department'),
    ]

    operations = [
        # State-only: remove the model from the migration state but do
        # NOT issue DROP TABLE. The physical `standard_departments` table
        # is shared with app_modules.core_modules.StandardDepartment and
        # must persist. SeparateDatabaseAndState makes this explicit.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='StandardDepartment',
                ),
            ],
            database_operations=[],
        ),
    ]
