# Generated by Django 5.1.4 on 2025-12-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StandardDepartment',
        ),
    ]
