# Generated by Django 5.1.4 on 2025-06-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_account_email_is_valid_account_phone_is_valid_and_more'),
        ('activities', '0001_initial'),
        ('campaign', '0001_initial'),
        ('end_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('title', models.CharField(max_length=200, verbose_name='Lead Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('lead_source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('CAMPAIGN', 'Campaign'), ('ACTIVITY', 'Activity'), ('INBOUND', 'Inbound'), ('REFERRAL', 'Referral'), ('WEBSITE', 'Website'), ('OTHER', 'Other')], default='MANUAL', max_length=20, verbose_name='Lead Source')),
                ('lead_source_detail', models.CharField(blank=True, help_text='Additional details about the source', max_length=255, null=True, verbose_name='Lead Source Detail')),
                ('lead_status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('UNQUALIFIED', 'Unqualified'), ('CONVERTED', 'Converted')], default='NEW', max_length=20, verbose_name='Lead Status')),
                ('last_activity_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Activity Date')),
                ('last_contacted_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Contacted Date')),
                ('number_of_touches', models.IntegerField(default=0, help_text='Total number of interactions specifically for this lead', verbose_name='Number of Touches')),
                ('conversion_date', models.DateTimeField(blank=True, null=True, verbose_name='Conversion Date')),
                ('is_qualified', models.BooleanField(default=False, help_text='Whether this lead meets qualification criteria', verbose_name='Is Qualified')),
                ('qualification_date', models.DateTimeField(blank=True, null=True, verbose_name='Qualification Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set_new', to='accounts.account', verbose_name='Account')),
                ('activities', models.ManyToManyField(blank=True, help_text='Activities specifically related to this lead', related_name='related_leads', to='activities.activity', verbose_name='Lead Activities')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='end_users.user', verbose_name='Assigned To')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_leads', to='campaign.campaign', verbose_name='Source Campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.contact', verbose_name='Primary Contact')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'leads',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
