# Generated by Django 5.1.4 on 2025-06-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_initial'),
        ('end_users', '0001_initial'),
        ('leads', '0001_initial'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_to_opportunity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='opportunities.opportunity', verbose_name='Converted to Opportunity'),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_activity',
            field=models.ForeignKey(blank=True, help_text='The activity that initially generated this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_leads', to='activities.activity', verbose_name='Source Activity'),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['account', 'lead_status'], name='leads_account_30e12a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_source'], name='leads_lead_so_f62041_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['conversion_date'], name='leads_convers_903935_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'lead_status'], name='leads_assigne_1895e9_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['last_activity_date'], name='leads_last_ac_0787f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('contact', 'campaign', 'client_id')},
        ),
    ]
