# Generated by Django 5.1.4 on 2025-05-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_account_email_is_valid_account_phone_is_valid_and_more'),
        ('campaign', '0001_initial'),
        ('end_users', '0001_initial'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('title', models.CharField(max_length=200, verbose_name='Activity Title')),
                ('activity_type', models.CharField(choices=[('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('TASK', 'Task'), ('LINKEDIN', 'LinkedIn Message'), ('CUSTOM', 'Custom Activity')], max_length=20, verbose_name='Activity Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('scheduled_start', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Start')),
                ('scheduled_end', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled End')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20, verbose_name='Status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('outcome_notes', models.TextField(blank=True, null=True, verbose_name='Outcome Notes')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.account', verbose_name='Account')),
                ('contacts', models.ManyToManyField(blank=True, related_name='activities', to='accounts.contact', verbose_name='Contacts')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('next_activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_activity_rel', to='activities.activity', verbose_name='Next Activity')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='opportunities.opportunity', verbose_name='Related Opportunity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_activities', to='end_users.user', verbose_name='Activity Owner')),
                ('previous_activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_activity_rel', to='activities.activity', verbose_name='Previous Activity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='ActivityCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('meeting_scheduled', models.BooleanField(default=False, verbose_name='Meeting Scheduled')),
                ('opportunity_created', models.BooleanField(default=False, verbose_name='Opportunity Created')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_info', to='activities.activity', verbose_name='Activity')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_campaigns', to='campaign.campaign', verbose_name='Campaign')),
                ('campaign_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_campaigns', to='campaign.campaigntarget', verbose_name='Campaign Target')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Activity Campaign Information',
                'verbose_name_plural': 'Activity Campaign Information',
            },
        ),
        migrations.CreateModel(
            name='ActivitySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('source_type', models.CharField(choices=[('CAMPAIGN', 'Campaign Sequence'), ('MANUAL', 'Manual Activity'), ('LEAD', 'Lead Sequence'), ('OPPORTUNITY', 'Opportunity Sequence')], default='CAMPAIGN', max_length=20, verbose_name='Activity Source')),
                ('sequence_position', models.IntegerField(help_text='Position in the sequence (e.g., 1-10 for chasing)', verbose_name='Sequence Position')),
                ('sequence_outcome', models.CharField(blank=True, choices=[('NO_ANSWER', 'No Answer'), ('NOT_INTERESTED', 'Not Interested'), ('CALLBACK_REQUESTED', 'Callback Requested'), ('MEETING_SCHEDULED', 'Meeting Scheduled')], max_length=30, null=True, verbose_name='Sequence Outcome')),
                ('call_attempts', models.IntegerField(default=0, help_text='Number of call attempts made (max 3 per step)', verbose_name='Call Attempts')),
                ('callback_requested_date', models.DateField(blank=True, help_text='Date when contact requested to be called back', null=True, verbose_name='Callback Requested Date')),
                ('sequence_paused_until', models.DateField(blank=True, help_text='Sequence is paused until this date', null=True, verbose_name='Sequence Paused Until')),
                ('days_since_last_sequence_activity', models.IntegerField(blank=True, null=True, verbose_name='Days Since Last Sequence Activity')),
                ('min_delay_days', models.IntegerField(default=0, help_text='Days to wait since previous activity before this becomes available', verbose_name='Minimum Delay Days')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_info', to='activities.activity', verbose_name='Activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('next_sequence_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_sequence_activities', to='activities.activity', verbose_name='Next Sequence Activity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Activity Sequence Information',
                'verbose_name_plural': 'Activity Sequence Information',
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['owner', 'scheduled_start'], name='activities__owner_i_51da0c_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['account', 'status'], name='activities__account_a76fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type'], name='activities__activit_8e7970_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['previous_activity'], name='activities__previou_18c54d_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['next_activity'], name='activities__next_ac_3d779d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitycampaign',
            index=models.Index(fields=['campaign', 'activity'], name='activities__campaig_7cf644_idx'),
        ),
        migrations.AddIndex(
            model_name='activitycampaign',
            index=models.Index(fields=['campaign_target'], name='activities__campaig_9ece19_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysequence',
            index=models.Index(fields=['source_type', 'sequence_position'], name='activities__source__0a3080_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysequence',
            index=models.Index(fields=['sequence_outcome'], name='activities__sequenc_29ce28_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysequence',
            index=models.Index(fields=['callback_requested_date'], name='activities__callbac_90111b_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysequence',
            index=models.Index(fields=['sequence_paused_until'], name='activities__sequenc_df0989_idx'),
        ),
    ]
