# Generated by Django 5.1.4 on 2025-05-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysequence',
            name='min_delay_days',
            field=models.IntegerField(default=0, help_text='Days to wait since previous activity before this becomes available', verbose_name='Minimum Delay Days'),
        ),
    ]
