# Generated by Django 5.1.4 on 2025-05-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('campaign', '0001_initial'),
        ('end_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycampaign',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_campaigns', to='campaign.campaign', verbose_name='Campaign'),
        ),
        migrations.AddField(
            model_name='activitycampaign',
            name='campaign_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_campaigns', to='campaign.campaigntarget', verbose_name='Campaign Target'),
        ),
        migrations.AddField(
            model_name='activitycampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='activitycampaign',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='activitysequence',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_info', to='activities.activity', verbose_name='Activity'),
        ),
        migrations.AddField(
            model_name='activitysequence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='activitysequence',
            name='next_sequence_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_sequence_activities', to='activities.activity', verbose_name='Next Sequence Activity'),
        ),
        migrations.AddField(
            model_name='activitysequence',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['owner', 'scheduled_start'], name='activities__owner_i_51da0c_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['account', 'status'], name='activities__account_a76fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type'], name='activities__activit_8e7970_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['previous_activity'], name='activities__previou_18c54d_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['next_activity'], name='activities__next_ac_3d779d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitycampaign',
            index=models.Index(fields=['campaign', 'activity'], name='activities__campaig_7cf644_idx'),
        ),
        migrations.AddIndex(
            model_name='activitycampaign',
            index=models.Index(fields=['campaign_target'], name='activities__campaig_9ece19_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysequence',
            index=models.Index(fields=['source_type', 'sequence_position'], name='activities__source__0a3080_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysequence',
            index=models.Index(fields=['sequence_outcome'], name='activities__sequenc_29ce28_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysequence',
            index=models.Index(fields=['callback_requested_date'], name='activities__callbac_90111b_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysequence',
            index=models.Index(fields=['sequence_paused_until'], name='activities__sequenc_df0989_idx'),
        ),
    ]
