# Generated by Django 5.1.4 on 2025-05-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activitysequence_min_delay_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Start'),
        ),
    ]
