# Generated by Django 5.1.4 on 2025-06-30 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysequence',
            name='sequence_type',
            field=models.CharField(blank=True, help_text='Type of sequence (CHASING, NURTURING, etc.) - copied from campaign for fast access', max_length=30, null=True, verbose_name='Sequence Type'),
        ),
        migrations.AddField(
            model_name='activitysequence',
            name='sequence_variant',
            field=models.CharField(blank=True, help_text='Variant of sequence used (standard, without_phone, without_email, phone_only)', max_length=20, null=True, verbose_name='Sequence Variant'),
        ),
        migrations.AlterField(
            model_name='activitysequence',
            name='sequence_outcome',
            field=models.CharField(blank=True, choices=[('NO_ANSWER', 'No Answer'), ('NOT_INTERESTED', 'Not Interested'), ('CALLBACK_REQUESTED', 'Callback Requested'), ('COMPLETED', 'Completed')], max_length=30, null=True, verbose_name='Sequence Outcome'),
        ),
        migrations.AddIndex(
            model_name='activitysequence',
            index=models.Index(fields=['sequence_type'], name='activities__sequenc_d747cb_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysequence',
            index=models.Index(fields=['sequence_variant'], name='activities__sequenc_c8f23f_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysequence',
            index=models.Index(fields=['sequence_type', 'sequence_variant'], name='activities__sequenc_e4fabc_idx'),
        ),
    ]
