# Generated by Django 5.1.4 on 2025-07-11 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_email_is_valid_account_phone_is_valid_and_more'),
        ('activities', '0003_activitysequence_sequence_type_and_more'),
        ('opportunities', '0002_opportunitypipeline_pipelinestage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='call_to_action',
            field=models.CharField(blank=True, help_text='Clear action the salesperson should take (e.g., "Ask about legal review timeline")', max_length=500, null=True, verbose_name='Call to Action'),
        ),
        migrations.AddField(
            model_name='activity',
            name='context_info',
            field=models.JSONField(blank=True, default=dict, help_text='Additional context information (substage details, stakeholder info, etc.)', verbose_name='Context Information'),
        ),
        migrations.AddField(
            model_name='activity',
            name='objectives',
            field=models.TextField(blank=True, help_text='Specific objectives or goals for this activity (e.g., from substage)', null=True, verbose_name='Activity Objectives'),
        ),
        migrations.AddField(
            model_name='activity',
            name='pipeline_substage',
            field=models.ForeignKey(blank=True, help_text='Pipeline substage this activity is directly linked to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_activities', to='opportunities.pipelinesubstage', verbose_name='Pipeline SubStage'),
        ),
        migrations.AddField(
            model_name='activity',
            name='substage_name',
            field=models.CharField(blank=True, help_text='Name of the related substage for quick reference', max_length=200, null=True, verbose_name='SubStage Name'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['pipeline_substage'], name='activity_substage_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['pipeline_substage', 'status'], name='activity_substage_status_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['pipeline_substage', 'status'], name='activities__pipelin_f17e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['substage_name'], name='activities__substag_bf6957_idx'),
        ),
    ]
