# Generated by Django 5.1.4 on 2026-04-28 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company_name', models.CharField(help_text='Name of the vendor (e.g. "Salesforce", "Microsoft", "Notion"). Required.', max_length=255, verbose_name='Company Name')),
                ('product_name', models.CharField(help_text='Name of the specific product (e.g. "Sales Cloud", "Teams"). Required, but auto-populated from `company_name` when left blank — useful when the vendor ships a single product sharing its name (e.g. "Notion" / "Notion").', max_length=255, verbose_name='Product Name')),
                ('vendor_url', models.URLField(blank=True, help_text='Optional canonical URL of the vendor (homepage).', max_length=500, null=True, verbose_name='Vendor URL')),
                ('is_competitor', models.BooleanField(default=False, help_text='True when this product overlaps with what we sell — replacing it is a winnable angle in a deal.', verbose_name='Is Competitor')),
                ('is_integration_target', models.BooleanField(default=False, help_text='True when this product is one we connect to — integrating with it is a winnable angle in a deal.', verbose_name='Is Integration Target')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Tech Catalog Entry',
                'verbose_name_plural': 'Tech Catalog Entries',
                'db_table': 'tech_catalog',
                'ordering': ['company_name', 'product_name'],
                'abstract': False,
                'indexes': [models.Index(fields=['company_name', 'client_id'], name='tech_catalo_company_bf2245_idx')],
                'unique_together': {('company_name', 'product_name', 'client_id')},
            },
        ),
    ]
