# Generated by Django 5.1.14 on 2026-08-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "module_signals",
            "0024_remove_painsignal_painsig_account_techref_idx_and_more",
        ),
        ("tech_catalog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TechCatalog",
        ),
    ]
