# Generated by Django 5.1.4 on 2025-06-04 15:00

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_account_email_is_valid_account_phone_is_valid_and_more'),
        ('activities', '0001_initial'),
        ('campaign', '0002_initial'),
        ('end_users', '0001_initial'),
        ('leads', '0001_initial'),
        ('products', '0002_remove_product_potential_cons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('title', models.CharField(max_length=200, verbose_name='Opportunity Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('opportunity_type', models.CharField(choices=[('NEW_BUSINESS', 'New Business'), ('EXISTING_CUSTOMER', 'Existing Customer'), ('RENEWAL', 'Renewal'), ('UPGRADE', 'Upgrade')], default='NEW_BUSINESS', max_length=20, verbose_name='Opportunity Type')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('WON', 'Won'), ('LOST', 'Lost'), ('PENDING', 'Pending')], default='OPEN', max_length=20, verbose_name='Status')),
                ('date_open', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Opened')),
                ('expected_close_date', models.DateField(verbose_name='Expected Close Date')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='Closed Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set_new', to='accounts.account', verbose_name='Account')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='accounts.contact', verbose_name='Primary Contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('deal_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_opportunities', to='end_users.user', verbose_name='Deal Owner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'db_table': 'opportunities',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpportunityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('is_key_activity', models.BooleanField(default=False, help_text='Whether this is a key milestone activity', verbose_name='Is Key Activity')),
                ('notes', models.TextField(blank=True, help_text='Notes about how this activity relates to the opportunity', null=True, verbose_name='Context Notes')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_links', to='activities.activity', verbose_name='Activity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='end_users.user', verbose_name='Created By')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_links', to='opportunities.opportunity', verbose_name='Opportunity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Opportunity Activity',
                'verbose_name_plural': 'Opportunity Activities',
                'db_table': 'opportunity_activities',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpportunityFinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('forecast_category', models.CharField(choices=[('PIPELINE', 'Pipeline'), ('UPSIDE', 'Upside'), ('COMMIT', 'Commit'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost')], default='PIPELINE', max_length=20, verbose_name='Forecast Category')),
                ('probability', models.IntegerField(default=0, help_text='Likelihood of closing as a percentage', verbose_name='Probability (%)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Amount')),
                ('expected_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Expected Revenue')),
                ('mrr_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='MRR Amount')),
                ('qrr_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='QRR Amount')),
                ('arr_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='ARR Amount')),
                ('one_time_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='One-Time Amount')),
                ('asset_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Asset Revenue')),
                ('service_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Service Revenue')),
                ('subscription_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Subscription Revenue')),
                ('usage_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Usage Revenue')),
                ('primary_currency', models.CharField(default='USD', max_length=3, verbose_name='Primary Currency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summary', to='opportunities.opportunity', verbose_name='Opportunity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Opportunity Financial Summary',
                'verbose_name_plural': 'Opportunity Financial Summaries',
                'db_table': 'opportunity_financial_summaries',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpportunityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('change_type', models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGE', 'Status Change'), ('STAGE_CHANGE', 'Stage Change'), ('OWNER_CHANGE', 'Owner Change'), ('AMOUNT_CHANGE', 'Amount Change'), ('DATE_CHANGE', 'Date Change'), ('CONVERSION_CREATED', 'Conversion Created'), ('CONVERSION_ACCEPTED', 'Conversion Accepted'), ('CONVERSION_REJECTED', 'Conversion Rejected'), ('CUSTOM', 'Custom')], max_length=30, verbose_name='Change Type')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Change Date')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='end_users.user', verbose_name='Changed By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='opportunities.opportunity', verbose_name='Opportunity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Opportunity History',
                'verbose_name_plural': 'Opportunity History',
                'db_table': 'opportunity_history',
                'ordering': ['-change_date'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('custom_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Custom Unit Price')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Discount (%)')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Line Total')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Line Item Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='opportunities.opportunity', verbose_name='Opportunity')),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_items', to='products.pricing', verbose_name='Pricing Model')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_items', to='products.product', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Opportunity Line Item',
                'verbose_name_plural': 'Opportunity Line Items',
                'db_table': 'opportunity_line_items',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpportunitySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('source_type', models.CharField(choices=[('LEAD', 'Lead Conversion'), ('CAMPAIGN', 'Campaign'), ('MANUAL', 'Manual Creation'), ('INBOUND', 'Inbound Request'), ('EXISTING_CUSTOMER', 'Existing Customer'), ('PARTNER', 'Partner Referral')], default='MANUAL', max_length=20, verbose_name='Source Type')),
                ('conversion_status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', max_length=20, verbose_name='Conversion Status')),
                ('conversion_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Conversion Date')),
                ('conversion_notes', models.TextField(blank=True, null=True, verbose_name='Conversion Notes')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('days_as_lead', models.IntegerField(default=0, help_text='Days from lead creation to opportunity conversion', verbose_name='Days as Lead')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunity_conversions', to='end_users.user', verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to='end_users.user', verbose_name='Created By')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='opportunities.opportunity', verbose_name='Opportunity')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_opportunities', to='accounts.account', verbose_name='Partner')),
                ('source_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_opportunities', to='campaign.campaign', verbose_name='Source Campaign')),
                ('source_campaign_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_opportunities', to='campaign.campaigntarget', verbose_name='Campaign Target')),
                ('source_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_opportunities', to='leads.lead', verbose_name='Source Lead')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Opportunity Source',
                'verbose_name_plural': 'Opportunity Sources',
                'db_table': 'opportunity_sources',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['account', 'status'], name='opportuniti_account_f550d6_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['opportunity_type'], name='opportuniti_opportu_b8dd5f_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['expected_close_date'], name='opportuniti_expecte_7f6286_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['closed_date'], name='opportuniti_closed__542c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['date_open'], name='opportuniti_date_op_fe7cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['account', 'status', 'deal_owner'], name='opp_account_status_owner_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opportunity',
            unique_together={('account', 'title', 'client_id')},
        ),
        migrations.AddIndex(
            model_name='opportunityactivity',
            index=models.Index(fields=['is_key_activity', 'client_id'], name='opportunity_is_key__7a3670_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opportunityactivity',
            unique_together={('opportunity', 'activity', 'client_id')},
        ),
        migrations.AddIndex(
            model_name='opportunityfinancialsummary',
            index=models.Index(fields=['probability'], name='opportunity_probabi_51a2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityfinancialsummary',
            index=models.Index(fields=['total_amount'], name='opportunity_total_a_e467dd_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityfinancialsummary',
            index=models.Index(fields=['forecast_category', 'probability'], name='opp_forecast_prob_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opportunityfinancialsummary',
            unique_together={('opportunity', 'client_id')},
        ),
        migrations.AddIndex(
            model_name='opportunityhistory',
            index=models.Index(fields=['opportunity', 'change_type'], name='opportunity_opportu_763313_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityhistory',
            index=models.Index(fields=['change_date'], name='opportunity_change__080e95_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitylineitem',
            index=models.Index(fields=['product', 'client_id'], name='opportunity_product_f26555_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opportunitylineitem',
            unique_together={('opportunity', 'product', 'pricing', 'client_id')},
        ),
        migrations.AddIndex(
            model_name='opportunitysource',
            index=models.Index(fields=['source_lead'], name='opportunity_source__6837d5_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitysource',
            index=models.Index(fields=['source_campaign'], name='opportunity_source__69325f_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitysource',
            index=models.Index(fields=['created_by'], name='opportunity_created_8393d1_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitysource',
            index=models.Index(fields=['assigned_to'], name='opportunity_assigne_60d5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitysource',
            index=models.Index(fields=['conversion_date'], name='opportunity_convers_f49c16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opportunitysource',
            unique_together={('opportunity', 'client_id')},
        ),
    ]
