# Generated by Django 5.1.4 on 2025-07-11 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_call_to_action_activity_context_info_and_more'),
        ('opportunities', '0002_opportunitypipeline_pipelinestage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubStageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('link_type', models.CharField(choices=[('PAST_ACTIVITY', 'Past Activity'), ('FUTURE_ACTIVITY', 'Future Activity'), ('TRIGGER_ACTIVITY', 'Trigger Activity'), ('MILESTONE_ACTIVITY', 'Milestone Activity')], default='FUTURE_ACTIVITY', help_text='Type of link between substage and activity', max_length=20, verbose_name='Link Type')),
                ('priority_order', models.PositiveIntegerField(default=0, help_text='Priority order of this activity within the substage', verbose_name='Priority Order')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this activity is required to complete the substage', verbose_name='Is Required')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether this activity has been completed', verbose_name='Is Completed')),
                ('auto_created', models.BooleanField(default=False, help_text='Whether this link was created automatically', verbose_name='Auto Created')),
                ('linked_at', models.DateTimeField(auto_now_add=True, help_text='When this activity was linked to the substage', verbose_name='Linked At')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this activity was completed', null=True, verbose_name='Completed At')),
                ('link_notes', models.TextField(blank=True, help_text='Notes about why this activity is linked to this substage', null=True, verbose_name='Link Notes')),
                ('substage_outcome', models.TextField(blank=True, help_text='How the activity outcome affects the substage', null=True, verbose_name='SubStage Outcome')),
                ('activity', models.ForeignKey(help_text='Activity linked to this substage', on_delete=django.db.models.deletion.CASCADE, related_name='substage_links', to='activities.activity', verbose_name='Activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('substage', models.ForeignKey(help_text='SubStage this activity is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='activity_links', to='opportunities.pipelinesubstage', verbose_name='Pipeline SubStage')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'SubStage Activity Link',
                'verbose_name_plural': 'SubStage Activity Links',
                'db_table': 'substage_activities',
                'ordering': ['substage', 'priority_order', 'linked_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['substage', 'activity', 'link_type', 'client_id'], name='substage_ac_substag_15c779_idx')],
                'constraints': [models.UniqueConstraint(fields=('substage', 'activity', 'client_id'), name='unique_substage_activity_per_client')],
            },
        ),
    ]
