# Generated by Django 5.1.4 on 2025-07-14 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_substageactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipelinetemplate',
            options={'verbose_name': 'Pipeline Template', 'verbose_name_plural': 'Pipeline Templates'},
        ),
        migrations.RemoveIndex(
            model_name='pipelinetemplate',
            name='pipeline_te_order_d00436_idx',
        ),
        migrations.RemoveField(
            model_name='pipelinetemplate',
            name='order',
        ),
        migrations.AddIndex(
            model_name='pipelinetemplate',
            index=models.Index(fields=['is_active', 'is_default', 'client_id'], name='pipeline_te_is_acti_5509fa_idx'),
        ),
    ]
