# Generated by Django 5.1.4 on 2025-07-14 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_alter_pipelinetemplate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipelinetemplate',
            options={'ordering': ['name', 'template_type'], 'verbose_name': 'Pipeline Template', 'verbose_name_plural': 'Pipeline Templates'},
        ),
        migrations.RemoveIndex(
            model_name='pipelinetemplate',
            name='pipeline_te_is_acti_5509fa_idx',
        ),
        migrations.AddField(
            model_name='pipelinetemplate',
            name='template_type',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('CUSTOM', 'Custom'), ('RENEWAL', 'Renewal')], default='DEFAULT', help_text='Type of template that determines the default stages', max_length=20, verbose_name='Template Type'),
        ),
        migrations.AddIndex(
            model_name='pipelinetemplate',
            index=models.Index(fields=['is_active', 'is_default', 'template_type', 'client_id'], name='pipeline_te_is_acti_1a8801_idx'),
        ),
    ]
