# Generated by Django 5.1.4 on 2025-07-16 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_alter_pipelinetemplate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Ajouter le champ opportunity avec null=True temporairement
        migrations.AddField(
            model_name='pipelinetemplate',
            name='opportunity',
            field=models.ForeignKey(
                null=True,
                blank=True,
                help_text='Opportunity this pipeline template belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pipeline_templates',
                to='opportunities.opportunity',
                verbose_name='Opportunity'
            ),
        ),
        
        # Modifier la relation OpportunityPipeline.template vers CASCADE
        migrations.AlterField(
            model_name='opportunitypipeline',
            name='template',
            field=models.ForeignKey(
                help_text='Template used to create this pipeline',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='opportunity_pipelines',
                to='opportunities.pipelinetemplate',
                verbose_name='Pipeline Template'
            ),
        ),
        
        # Modifier les options du modèle
        migrations.AlterModelOptions(
            name='pipelinetemplate',
            options={
                'ordering': ['opportunity', 'name', 'template_type'],
                'verbose_name': 'Pipeline Template',
                'verbose_name_plural': 'Pipeline Templates'
            },
        ),
        
        # Supprimer l'ancien index
        migrations.RemoveIndex(
            model_name='pipelinetemplate',
            name='pipeline_te_is_acti_1a8801_idx',
        ),
        
        # Ajouter le nouvel index avec opportunity
        migrations.AddIndex(
            model_name='pipelinetemplate',
            index=models.Index(
                fields=['is_active', 'is_default', 'template_type', 'opportunity', 'client_id'],
                name='pipeline_te_is_acti_2a8801_idx'
            ),
        ),
        
        # Modifier les contraintes d'unicité : un seul template par opportunité
        migrations.AlterUniqueTogether(
            name='pipelinetemplate',
            unique_together={('opportunity', 'client_id')},
        ),
    ]