# Generated by Django 5.1.4 on 2025-07-17 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_alter_pipelinetemplate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pipelinetemplate',
            name='pipeline_te_is_acti_2a8801_idx',
        ),
        migrations.AlterUniqueTogether(
            name='pipelinetemplate',
            unique_together={('opportunity', 'name', 'client_id')},
        ),
        migrations.AlterField(
            model_name='pipelinetemplate',
            name='opportunity',
            field=models.ForeignKey(default=13, help_text='Opportunity this pipeline template belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_templates', to='opportunities.opportunity', verbose_name='Opportunity'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='pipelinetemplate',
            index=models.Index(fields=['is_default', 'template_type', 'opportunity', 'client_id'], name='pipeline_te_is_defa_efd3bf_idx'),
        ),
        migrations.RemoveField(
            model_name='pipelinetemplate',
            name='is_active',
        ),
    ]
