# Generated by Django 5.1.4 on 2025-07-18 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_call_to_action_activity_context_info_and_more'),
        ('opportunities', '0007_remove_pipelinetemplate_pipeline_te_is_acti_2a8801_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='substageactivity',
            options={'ordering': ['substage', 'created_at'], 'verbose_name': 'SubStage Activity Link', 'verbose_name_plural': 'SubStage Activity Links'},
        ),
        migrations.RemoveIndex(
            model_name='substageactivity',
            name='substage_ac_substag_15c779_idx',
        ),
        migrations.RemoveField(
            model_name='substageactivity',
            name='auto_created',
        ),
        migrations.RemoveField(
            model_name='substageactivity',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='substageactivity',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='substageactivity',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='substageactivity',
            name='link_notes',
        ),
        migrations.RemoveField(
            model_name='substageactivity',
            name='link_type',
        ),
        migrations.RemoveField(
            model_name='substageactivity',
            name='linked_at',
        ),
        migrations.RemoveField(
            model_name='substageactivity',
            name='priority_order',
        ),
        migrations.RemoveField(
            model_name='substageactivity',
            name='substage_outcome',
        ),
        migrations.AddIndex(
            model_name='substageactivity',
            index=models.Index(fields=['substage', 'activity', 'client_id'], name='substage_ac_substag_b1c612_idx'),
        ),
        migrations.AddIndex(
            model_name='substageactivity',
            index=models.Index(fields=['substage', 'created_at'], name='substage_ac_substag_0a7d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='substageactivity',
            index=models.Index(fields=['activity'], name='substage_ac_activit_d21690_idx'),
        ),
    ]
