# Generated by Django 5.1.4 on 2025-07-22 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0008_alter_substageactivity_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunitypipeline',
            options={'ordering': ['-last_updated', 'opportunity__title'], 'verbose_name': 'Opportunity Pipeline', 'verbose_name_plural': 'Opportunity Pipelines'},
        ),
        migrations.RemoveIndex(
            model_name='opportunitypipeline',
            name='opportunity_opportu_0e71a4_idx',
        ),
        migrations.RemoveField(
            model_name='opportunitypipeline',
            name='completed_stages',
        ),
        migrations.RemoveField(
            model_name='opportunitypipeline',
            name='estimated_duration_days',
        ),
        migrations.RemoveField(
            model_name='opportunitypipeline',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='opportunitypipeline',
            name='template',
        ),
        migrations.RemoveField(
            model_name='opportunitypipeline',
            name='total_stages',
        ),
        migrations.AddField(
            model_name='opportunitypipeline',
            name='actual_duration_days',
            field=models.PositiveIntegerField(default=0, help_text='Actual number of days since pipeline started', verbose_name='Actual Duration (Days)'),
        ),
        migrations.AddField(
            model_name='opportunitypipeline',
            name='current_substage',
            field=models.ForeignKey(blank=True, help_text='Current substage of this pipeline for precise tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_opportunities', to='opportunities.pipelinesubstage', verbose_name='Current SubStage'),
        ),
        migrations.AddField(
            model_name='opportunitypipeline',
            name='expected_close_date',
            field=models.DateField(blank=True, help_text='Calculated expected completion date based on substage durations', null=True, verbose_name='Expected Close Date'),
        ),
        migrations.AlterField(
            model_name='opportunitypipeline',
            name='is_customized',
            field=models.BooleanField(default=False, help_text='Whether this pipeline has been customized from the template', verbose_name='Is Customized'),
        ),
        migrations.AddIndex(
            model_name='opportunitypipeline',
            index=models.Index(fields=['opportunity', 'current_stage', 'current_substage', 'status', 'client_id'], name='opportunity_opportu_567bf9_idx'),
        ),
    ]
