# Generated by Django 5.1.4 on 2025-07-23 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0009_alter_opportunitypipeline_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pipelinestage',
            name='pipeline_st_templat_daccd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='pipelinesubstage',
            name='pipeline_su_stage_i_c4be35_idx',
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='overdue',
            field=models.BooleanField(default=False, help_text='Whether this stage is overdue (automatically calculated)', verbose_name='Is Overdue'),
        ),
        migrations.AddField(
            model_name='pipelinesubstage',
            name='overdue',
            field=models.BooleanField(default=False, help_text='Whether this substage is overdue (automatically calculated)', verbose_name='Is Overdue'),
        ),
        migrations.AddIndex(
            model_name='pipelinestage',
            index=models.Index(fields=['template', 'opportunity_pipeline', 'order', 'status', 'overdue', 'client_id'], name='pipeline_st_templat_6cea77_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinesubstage',
            index=models.Index(fields=['stage', 'order', 'status', 'substage_type', 'overdue', 'client_id'], name='pipeline_su_stage_i_1716f8_idx'),
        ),
    ]
