# Generated by Django 5.1.4 on 2025-07-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_email_is_valid_account_phone_is_valid_and_more'),
        ('opportunities', '0010_remove_pipelinestage_pipeline_st_templat_daccd3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestage',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, help_text='Stakeholders involved in this pipeline stage (aggregated from substages)', related_name='pipeline_stages', to='accounts.contact', verbose_name='Stakeholders'),
        ),
        migrations.AddField(
            model_name='pipelinesubstage',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, help_text='Stakeholders directly involved in this substage', related_name='pipeline_substages', to='accounts.contact', verbose_name='Stakeholders'),
        ),
    ]
