# Generated by Django 5.1.4 on 2025-07-30 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_call_to_action_activity_context_info_and_more'),
        ('opportunities', '0011_pipelinestage_stakeholders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitypipeline',
            name='detected_activity',
            field=models.ForeignKey(blank=True, help_text='Activity automatically detected as current position', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_in_pipelines', to='activities.activity', verbose_name='Detected Activity'),
        ),
        migrations.AddField(
            model_name='opportunitypipeline',
            name='detected_stage',
            field=models.ForeignKey(blank=True, help_text='Stage automatically detected as current position', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_in_pipelines', to='opportunities.pipelinestage', verbose_name='Detected Stage'),
        ),
        migrations.AddField(
            model_name='opportunitypipeline',
            name='detected_substage',
            field=models.ForeignKey(blank=True, help_text='SubStage automatically detected as current position', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_in_pipelines', to='opportunities.pipelinesubstage', verbose_name='Detected SubStage'),
        ),
        migrations.AddField(
            model_name='opportunitypipeline',
            name='position_last_updated',
            field=models.DateTimeField(auto_now=True, help_text='When position detection was last run', verbose_name='Position Last Updated'),
        ),
    ]
