# Generated by Django 5.1.4 on 2025-12-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_modules', '0001_initial'),
        ('opportunities', '0012_opportunitypipeline_detected_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substagemetadata',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department responsible for this substage', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_modules.standarddepartment', verbose_name='Department'),
        ),
    ]
