# Generated by Django 5.1.4 on 2025-01-29 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_account_company_name'),
        ('core_apps', '0002_initial'),
        ('end_users', '0003_user_role_name'),
        ('org_units', '0002_rename_org_units_a_account_e9d410_idx_organizatio_account_40a6c3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProductTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_mapping_confidence', models.FloatField(blank=True, null=True, verbose_name='AI Mapping Confidence Score')),
                ('manually_validated', models.BooleanField(default=False, verbose_name='Manually Validated by User')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_targets', to='accounts.account')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org_units.accountorganizationunit', verbose_name='Specific Organization Unit')),
            ],
            options={
                'verbose_name': 'Account Product Target',
                'verbose_name_plural': 'Account Product Targets',
                'db_table': 'account_product_targets',
            },
        ),
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('name', models.CharField(help_text='Unique name for this billing cycle offer', max_length=255, verbose_name='Cycle Name')),
                ('cycle_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('THREE_YEARS', '3 Years')], max_length=20, verbose_name='Cycle Type')),
                ('multiplier', models.DecimalField(decimal_places=2, help_text='Multiplier applied to base price (e.g., 0.9 for 10% discount)', max_digits=10, verbose_name='Price Multiplier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Billing Cycle',
                'verbose_name_plural': 'Billing Cycles',
                'db_table': 'billing_cycles',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('product_type', models.CharField(choices=[('REGULAR', 'Physical or Digital Product'), ('SERVICE', 'Service-Based Offering')], max_length=20, verbose_name='Product Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Marketing Description')),
                ('value_proposition', models.JSONField(blank=True, null=True, verbose_name='Value Proposition')),
                ('potential_cons', models.JSONField(blank=True, null=True, verbose_name='Potential Cons')),
                ('competitors', models.JSONField(blank=True, null=True, verbose_name='Most Frequent Competitors')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('target_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_apps.standarddepartment', verbose_name='Standard Department Category')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('pricing_type', models.CharField(choices=[('ONE_TIME', 'One-Time Fee'), ('SUBSCRIPTION', 'Subscription')], max_length=20, verbose_name='Pricing Type')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Price')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Currency')),
                ('available_cycles', models.ManyToManyField(blank=True, related_name='pricing_models', to='products.billingcycle', verbose_name='Available Billing Cycles')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_models', to='products.product')),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricing Models',
                'db_table': 'product_pricing',
            },
        ),
    ]
