# Generated by Django 5.1.4 on 2025-02-26 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_apps', '0001_initial'),
        ('end_users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Marketing Description')),
                ('value_proposition', models.JSONField(blank=True, null=True, verbose_name='Value Proposition')),
                ('potential_cons', models.JSONField(blank=True, null=True, verbose_name='Potential Cons')),
                ('competitors', models.JSONField(blank=True, null=True, verbose_name='Most Frequent Competitors')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('target_categories', models.ManyToManyField(blank=True, related_name='products_for_category', to='core_apps.standarddepartment', verbose_name='Standard Department Categories')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['product_name'],
                'abstract': False,
                'unique_together': {('product_name', 'client_id')},
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('pricing_type', models.CharField(choices=[('ASSET', 'Asset'), ('SERVICE', 'Service'), ('SUBSCRIPTION', 'Subscription'), ('USAGE', 'Usage')], max_length=20, verbose_name='Pricing Type')),
                ('contract_payment_term', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('ONE_TIME', 'One Time')], default='YEARLY', max_length=20, verbose_name='Contract Payment Term')),
                ('unit_of_measure', models.CharField(choices=[('UNIT', 'Unit'), ('SEAT', 'Seats'), ('GB', 'GIGA BIT'), ('MIN', 'Minute'), ('API_CALL', 'API call'), ('TOKEN', 'Token')], default='UNIT', max_length=20, verbose_name='Unit of Measure')),
                ('units_per', models.PositiveIntegerField(default=1, help_text='Number of base units per billing unit (e.g., 60 minutes per hour)', verbose_name='Units Per')),
                ('unit_price', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Unit Price')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Flat fee charged before unit pricing', max_digits=10, verbose_name='Base Price')),
                ('pricing_term', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20, null=True, verbose_name='Billing Term')),
                ('currency', models.CharField(choices=[('USD', 'DOLLAR'), ('EUR', 'EURO'), ('GBP', 'GREAT BRITAIN POUND')], default='USD', max_length=3, verbose_name='Currency')),
                ('formula', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_models', to='products.product')),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricing Models',
                'db_table': 'product_pricing',
                'abstract': False,
                'indexes': [models.Index(fields=['pricing_type', 'client_id'], name='product_pri_pricing_6969d4_idx')],
                'unique_together': {('product', 'pricing_type', 'client_id')},
            },
        ),
    ]
