# Generated by Django 5.1.4 on 2025-03-12 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='potential_cons',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value_proposition',
        ),
        migrations.AddField(
            model_name='product',
            name='key_benefits',
            field=models.JSONField(blank=True, default=list, help_text='Tangible values the product delivers to customers', null=True, verbose_name='Key Benefits'),
        ),
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=models.JSONField(blank=True, default=list, help_text='List of product features with their functions and roles', null=True, verbose_name='Key Features'),
        ),
        migrations.AddField(
            model_name='product',
            name='typical_implementation_time',
            field=models.PositiveIntegerField(blank=True, help_text='Average number of days to implement this product', null=True, verbose_name='Typical Implementation Time (Days)'),
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('name', models.CharField(max_length=255, verbose_name='Competitor Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('battle_cards', models.JSONField(blank=True, default=dict, help_text='Competitive differentiation points', null=True, verbose_name='Battle Cards')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('products', models.ManyToManyField(blank=True, related_name='competitor_list', to='products.product', verbose_name='Competing Products')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Competitor',
                'verbose_name_plural': 'Competitors',
                'db_table': 'competitors',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('name', 'client_id')},
            },
        ),
    ]
