# Generated by Django 5.1.4 on 2025-02-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_apps', '0002_initial'),
        ('end_users', '0003_user_role_name'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='currency',
            field=models.CharField(choices=[('USD', 'DOLLAR'), ('EUR', 'EURO'), ('GBP', 'GREAT BRITAIN POUND')], default='USD', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='target_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_apps.standarddepartment', verbose_name='Standard Department Category'),
        ),
        migrations.AlterUniqueTogether(
            name='pricing',
            unique_together={('product', 'pricing_type', 'client_id')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_name', 'client_id')},
        ),
        migrations.AddIndex(
            model_name='pricing',
            index=models.Index(fields=['pricing_type', 'client_id'], name='product_pri_pricing_6969d4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'target_category', 'client_id'], name='products_product_c67981_idx'),
        ),
    ]
