# Generated by Django 5.1.4 on 2025-02-10 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_apps', '0002_initial'),
        ('end_users', '0003_user_role_name'),
        ('products', '0002_alter_pricing_currency_alter_product_target_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('label', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('field_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='accountproducttarget',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountproducttarget',
            name='org_unit',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_product_c67981_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='target_category',
        ),
        migrations.AddField(
            model_name='pricing',
            name='formula',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='target_categories',
            field=models.ManyToManyField(blank=True, related_name='products_for_category', to='core_apps.standarddepartment', verbose_name='Standard Department Categories'),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='cycle_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('THREE_YEARS', '3 Years')], max_length=20, verbose_name='Cycle Type'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='pricing_type',
            field=models.CharField(choices=[('ONE_TIME', 'One-Time Fee'), ('SUBSCRIPTION', 'Subscription'), ('USAGE', 'Usage')], max_length=20, verbose_name='Pricing Type'),
        ),
        migrations.AddField(
            model_name='productvariable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='productvariable',
            name='pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='products.pricing'),
        ),
        migrations.AddField(
            model_name='productvariable',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By'),
        ),
        migrations.DeleteModel(
            name='AccountProductTarget',
        ),
    ]
