# Generated by Django 5.1.4 on 2025-12-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_modules', '0001_initial'),
        ('products', '0002_remove_product_potential_cons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='target_categories',
            field=models.ManyToManyField(blank=True, related_name='products_for_category', to='core_modules.standarddepartment', verbose_name='Standard Department Categories'),
        ),
    ]
