# Generated by Django 5.1.4 on 2025-02-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariable_remove_accountproducttarget_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='available_cycles',
        ),
        migrations.AddField(
            model_name='pricing',
            name='billing_term',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('THREE_YEARS', '3 Years')], max_length=20, null=True, verbose_name='Billing Term'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='unit_of_measure',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('SEAT', 'Seats'), ('GB', 'GIGA BIT'), ('MIN', 'Minute'), ('API_CALL', 'API call'), ('TOKEN', 'Token')], default='UNIT', max_length=20, verbose_name='Unit of Measure'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='units_per',
            field=models.PositiveIntegerField(default=1, help_text='Number of base units per billing unit (e.g., 60 minutes per hour)', verbose_name='Units Per'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Flat fee charged before unit pricing', max_digits=10, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='currency',
            field=models.CharField(choices=[('USD', 'DOLLAR'), ('EUR', 'EURO'), ('GBP', 'GREAT BRITAIN POUND')], default='USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='pricing_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('SERVICE', 'Service'), ('SUBSCRIPTION', 'Subscription'), ('USAGE', 'Usage')], max_length=20, verbose_name='Pricing Type'),
        ),
        migrations.DeleteModel(
            name='ProductVariable',
        ),
    ]
