# Generated by Django 5.1.4 on 2025-02-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_pricing_available_cycles_pricing_billing_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='contract_payment_term',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('ONE_TIME', 'One Time')], default='YEARLY', max_length=20, verbose_name='Contract Payment Term'),
        ),
        migrations.DeleteModel(
            name='BillingCycle',
        ),
    ]
