# Generated by Django 5.1.4 on 2025-02-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_pricing_contract_payment_term_delete_billingcycle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='billing_term',
            new_name='pricing_term',
        ),
    ]
