# Generated by Django 5.1.4 on 2025-02-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_billing_term_pricing_pricing_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='pricing_term',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20, null=True, verbose_name='Billing Term'),
        ),
    ]
