# Generated by Django 5.1.4 on 2026-01-12 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decision_cycles', '0002_decisionstep_completed_at_and_more'),
        ('module_accounts', '0003_alter_companyaccount_industry'),
        ('module_contacts', '0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('activity_type', models.CharField(choices=[('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('TASK', 'Task'), ('LINKEDIN', 'LinkedIn Message'), ('OTHER', 'Other')], max_length=20, verbose_name='Activity Type')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the activity', null=True, verbose_name='Description')),
                ('call_to_action', models.CharField(blank=True, help_text='Clear action the salesperson should take (e.g., "Ask about legal review timeline")', max_length=500, null=True, verbose_name='Call to Action')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20, verbose_name='Status')),
                ('outcome', models.CharField(blank=True, choices=[('SUCCESSFUL', 'Successful'), ('NO_ANSWER', 'No Answer'), ('CALLBACK_REQUESTED', 'Callback Requested'), ('NOT_INTERESTED', 'Not Interested'), ('WRONG_CONTACT', 'Wrong Contact'), ('MEETING_SCHEDULED', 'Meeting Scheduled'), ('FOLLOW_UP_NEEDED', 'Follow-up Needed'), ('OTHER', 'Other')], help_text='Result of the activity (only when completed)', max_length=30, null=True, verbose_name='Outcome')),
                ('outcome_notes', models.TextField(blank=True, help_text='Notes about the activity result', null=True, verbose_name='Outcome Notes')),
                ('scheduled_date', models.DateField(blank=True, help_text='Date when the activity is scheduled', null=True, verbose_name='Scheduled Date')),
                ('scheduled_time', models.TimeField(blank=True, help_text='Time when the activity is scheduled', null=True, verbose_name='Scheduled Time')),
                ('due_date', models.DateField(blank=True, help_text='Deadline for completing the activity', null=True, verbose_name='Due Date')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the activity was completed', null=True, verbose_name='Completed At')),
                ('transcript', models.TextField(blank=True, help_text='Call transcript or email content for AI analysis', null=True, verbose_name='Transcript')),
                ('preparation_notes', models.TextField(blank=True, help_text='AI-generated preparation notes (future feature)', null=True, verbose_name='Preparation Notes')),
                ('account', models.ForeignKey(help_text='The company account this activity is for', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='module_accounts.companyaccount', verbose_name='Account')),
                ('contacts', models.ManyToManyField(blank=True, help_text='Contacts involved in this activity', related_name='activities', to='module_contacts.contact', verbose_name='Contacts')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('decision_cycle', models.ForeignKey(blank=True, help_text='Decision cycle this activity contributes to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='decision_cycles.decisioncycle', verbose_name='Decision Cycle')),
                ('decision_step', models.ForeignKey(blank=True, help_text='Specific decision step this activity is linked to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='decision_cycles.decisionstep', verbose_name='Decision Step')),
                ('next_activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_activity_rel', to='module_activities.activity', verbose_name='Next Activity')),
                ('owner', models.ForeignKey(help_text='User responsible for this activity', on_delete=django.db.models.deletion.CASCADE, related_name='module_owned_activities', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('previous_activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_activity_rel', to='module_activities.activity', verbose_name='Previous Activity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'module_activities',
                'ordering': ['-scheduled_date', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['account'], name='act_account_idx'), models.Index(fields=['owner'], name='act_owner_idx'), models.Index(fields=['status'], name='act_status_idx'), models.Index(fields=['activity_type'], name='act_type_idx'), models.Index(fields=['scheduled_date'], name='act_scheduled_idx'), models.Index(fields=['due_date'], name='act_due_date_idx'), models.Index(fields=['decision_step'], name='act_step_idx'), models.Index(fields=['previous_activity'], name='act_prev_idx'), models.Index(fields=['next_activity'], name='act_next_idx')],
            },
        ),
    ]
