# Generated by Django 5.1.4 on 2026-01-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='next_step_agreed',
            field=models.BooleanField(blank=True, default=None, help_text='True = follow-up activity or step planned, False = explicitly no next step agreed, Null = not yet determined', null=True, verbose_name='Next Step Agreed'),
        ),
        migrations.AddField(
            model_name='activity',
            name='no_next_step_reason',
            field=models.TextField(blank=True, help_text='Reason provided when next_step_agreed is False', null=True, verbose_name='No Next Step Reason'),
        ),
    ]
