# Generated by Django 5.1.4 on 2026-01-27 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_activities', '0002_add_next_step_agreed_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='invited_users',
            field=models.ManyToManyField(blank=True, help_text='Internal users invited to participate in this activity', related_name='module_invited_activities', to=settings.AUTH_USER_MODEL, verbose_name='Invited Users'),
        ),
    ]
