# Generated by Django 5.1.4 on 2026-01-29 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_cycles', '0007_alter_decisionstep_expected_end'),
        ('module_accounts', '0003_alter_companyaccount_industry'),
        ('module_activities', '0003_activity_invited_users'),
        ('module_contacts', '0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='next_activity',
            field=models.OneToOneField(blank=True, help_text='DEPRECATED: Use sequence_context for activities in a cycle. Manual linking only for standalone activities.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_activity_rel', to='module_activities.activity', verbose_name='Next Activity (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='previous_activity',
            field=models.OneToOneField(blank=True, help_text='DEPRECATED: Use sequence_context for activities in a cycle. Manual linking only for standalone activities.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_activity_rel', to='module_activities.activity', verbose_name='Previous Activity (DEPRECATED)'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['decision_cycle', 'decision_step', 'scheduled_date', 'scheduled_time', 'created_at'], name='act_sequence_order_idx'),
        ),
    ]
