# Generated by Django 5.1.4 on 2026-03-02 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_cycles', '0011_remove_decisioncycle_dc_owner_idx_and_more'),
        ('module_accounts', '0003_alter_companyaccount_industry'),
        ('module_activities', '0005_alter_activity_status'),
        ('module_campaigns', '0001_initial'),
        ('module_contacts', '0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Campaign that generated this activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='module_campaigns.campaign', verbose_name='Campaign'),
        ),
        migrations.AddField(
            model_name='activity',
            name='campaign_account',
            field=models.ForeignKey(blank=True, help_text='Specific campaign-account pivot this activity belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='module_campaigns.campaignaccount', verbose_name='Campaign Account'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sequence_position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Position in the campaign sequence (1-based)', null=True, verbose_name='Sequence Position'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['campaign'], name='act_campaign_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['campaign_account'], name='act_camp_account_idx'),
        ),
    ]
