# Generated by Django 5.1.4 on 2026-03-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_activities', '0006_activity_campaign_activity_campaign_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='min_delay_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minimum days to wait after previous activity completion before scheduling this one', null=True, verbose_name='Minimum Delay Days'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sequence_variant',
            field=models.CharField(blank=True, help_text='Variant used to generate this activity (STANDARD, WITHOUT_PHONE, etc.)', max_length=50, null=True, verbose_name='Sequence Variant'),
        ),
    ]
