# Generated by Django 5.1.4 on 2026-03-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_activities', '0007_activity_min_delay_days_activity_sequence_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_callback_followup',
            field=models.BooleanField(default=False, help_text='True when this activity was created in response to a CALLBACK_REQUESTED outcome. Used to surface only this activity in the PAUSED playlist section while the campaign account is in CALLBACK_PENDING status.', verbose_name='Is Callback Follow-up'),
        ),
    ]
