# Generated by Django 5.1.4 on 2026-03-11 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_activities', '0008_activity_is_callback_followup'),
        ('module_campaigns', '0004_alter_campaignaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='campaign_contact',
            field=models.ForeignKey(blank=True, help_text='Contact-scoped campaign pivot this activity belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='module_campaigns.campaigncontact', verbose_name='Campaign Contact'),
        ),
    ]
