# Generated by Django 5.1.4 on 2026-03-13 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_cycles', '0011_remove_decisioncycle_dc_owner_idx_and_more'),
        ('module_accounts', '0003_alter_companyaccount_industry'),
        ('module_activities', '0010_alter_activity_status'),
        ('module_campaigns', '0006_alter_campaign_planned_end_date_and_more'),
        ('module_contacts', '0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='no_answer_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of no-answer attempts recorded on this specific activity.', verbose_name='No Answer Count'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['campaign', 'status', 'scheduled_date'], name='act_camp_status_sched_idx'),
        ),
    ]
