# Generated by Django 5.1.4 on 2026-03-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_activities', '0011_activity_no_answer_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='outcome',
            field=models.CharField(blank=True, choices=[('SUCCESSFUL', 'Successful'), ('NO_ANSWER', 'No Answer'), ('CALLBACK_REQUESTED', 'Callback Requested'), ('NOT_INTERESTED', 'Not Interested'), ('WRONG_CONTACT', 'Wrong Contact'), ('MEETING_SCHEDULED', 'Meeting Scheduled'), ('FOLLOW_UP_NEEDED', 'Follow-up Needed'), ('UNSUBSCRIBE_OPTOUT', 'Unsubscribe / Opt-out'), ('WRONG_EMAIL', 'Wrong Email'), ('INVALID_PHONE_NUMBER', 'Invalid Phone Number'), ('OTHER', 'Other')], help_text='Result of the activity (only when completed)', max_length=30, null=True, verbose_name='Outcome'),
        ),
    ]
