# Generated by Django 5.1.4 on 2026-03-24 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_activities', '0012_alter_activity_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='source_activity',
            field=models.ForeignKey(blank=True, help_text='Campaign activity that triggered the creation of this decision cycle activity. Set during campaign-to-cycle conversion flow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_activities', to='module_activities.activity', verbose_name='Source Activity'),
        ),
    ]
