# Generated by Django 5.1.4 on 2026-03-27 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_cycles', '0012_decisioncycle_source_campaign'),
        ('module_activities', '0016_drop_prev_next_activity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='source_decision_cycle',
            field=models.ForeignKey(blank=True, help_text='Decision cycle that triggered the creation of this activity. Set when enrolling contacts into a Targeted campaign from a DC context, without a prior activity to reference.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_activities', to='decision_cycles.decisioncycle', verbose_name='Source Decision Cycle'),
        ),
    ]
