# Generated by Django 5.1.14 on 2026-07-14 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decision_cycles", "0018_decisioncycle_dc_outcome_date_idx"),
        ("module_accounts", "0003_alter_companyaccount_industry"),
        ("module_activities", "0019_add_demo_activity_type"),
        ("module_campaigns", "0014_campaign_channel_override"),
        (
            "module_contacts",
            "0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more",
        ),
        ("module_signals", "0020_alter_nextstepsignal_suggested_activity_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["outcome"], name="act_outcome_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["completed_at"], name="act_completed_at_idx"),
        ),
    ]
