# Generated by Django 5.1.14 on 2026-07-29 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decision_cycles", "0019_remove_decisionstep_ds_status_idx_and_more"),
        ("module_accounts", "0004_companyaccount_became_client_at"),
        ("module_activities", "0020_activity_act_outcome_idx_and_more"),
        ("module_campaigns", "0015_campaigncontact_sequence_run"),
        (
            "module_contacts",
            "0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more",
        ),
        ("module_signals", "0020_alter_nextstepsignal_suggested_activity_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="sequence_run",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Chasing-run number this activity belongs to. Stamped at creation from the CampaignContact.sequence_run and never changed afterwards. Lets the completed view show only the current run while previous runs remain in the database.",
                verbose_name="Sequence Run",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["campaign_contact", "sequence_run"],
                name="act_camp_contact_run_idx",
            ),
        ),
    ]
