# Generated by Django 5.1.14 on 2026-08-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_activities", "0021_activity_sequence_run_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("CALL", "Phone Call"),
                    ("EMAIL", "Email"),
                    ("MEETING", "Meeting"),
                    ("DEMO", "Demo"),
                    ("TASK", "Task"),
                    ("LINKEDIN", "LinkedIn"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
                verbose_name="Activity Type",
            ),
        ),
    ]
