# Generated by Django 5.1.4 on 2026-03-02 08:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_modules', '0001_initial'),
        ('module_accounts', '0003_alter_companyaccount_industry'),
        ('module_contacts', '0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more'),
        ('module_territories', '0002_alter_territory_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Campaign Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('campaign_type', models.CharField(choices=[('OUTBOUND', 'Outbound Campaign'), ('TARGETED', 'Targeted Campaign')], help_text='OUTBOUND = territory-based, TARGETED = manual account selection', max_length=20, verbose_name='Campaign Type')),
                ('sequence_type', models.CharField(blank=True, help_text='Automated sequence pattern. NULL for campaigns without sequences.', max_length=30, null=True, verbose_name='Sequence Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('territory', models.ForeignKey(blank=True, help_text='Source territory for OUTBOUND campaigns', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='module_territories.territory', verbose_name='Territory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'module_campaigns',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('CALLBACK_PENDING', 'Callback Pending'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='TARGETED: specific reason / context for this account', null=True, verbose_name='Notes')),
                ('callback_date', models.DateField(blank=True, help_text='Scheduled callback date when in CALLBACK_PENDING', null=True, verbose_name='Callback Date')),
                ('activities_generated', models.BooleanField(default=False, help_text='Whether sequence activities have been generated for this account', verbose_name='Activities Generated')),
                ('no_answer_count', models.IntegerField(default=0, help_text='Number of unanswered call attempts', verbose_name='No Answer Count')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_enrollments', to='module_accounts.companyaccount', verbose_name='Account')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_accounts', to='module_campaigns.campaign', verbose_name='Campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('target_contacts', models.ManyToManyField(blank=True, help_text='Optional: narrow activities to these contacts', related_name='campaign_account_targets', to='module_contacts.contact', verbose_name='Target Contacts')),
                ('target_departments', models.ManyToManyField(blank=True, help_text='Optional: narrow activities to these departments', related_name='campaign_account_targets', to='core_modules.standarddepartment', verbose_name='Target Departments')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Campaign Account',
                'verbose_name_plural': 'Campaign Accounts',
                'db_table': 'module_campaign_accounts',
                'ordering': ['campaign', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('role', models.CharField(choices=[('OWNER', 'Campaign Owner'), ('EXECUTOR', 'Executor'), ('RECEIVER', 'Receiver'), ('OBSERVER', 'Observer')], default='OBSERVER', max_length=20, verbose_name='Role')),
                ('is_primary_owner', models.BooleanField(default=False, help_text='Exactly one member per campaign should be the primary owner', verbose_name='Is Primary Owner')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='module_campaigns.campaign', verbose_name='Campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Campaign Member',
                'verbose_name_plural': 'Campaign Members',
                'db_table': 'module_campaign_members',
                'ordering': ['campaign', 'role', 'added_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Objective Name')),
                ('objective_type', models.CharField(choices=[('MEETINGS', 'Number of Meetings'), ('DECISION_CYCLES', 'Decision Cycles Opened'), ('CONTACTS_REACHED', 'Contacts Reached'), ('PIPELINE_VALUE', 'Pipeline Value'), ('REVENUE_WON', 'Revenue Won'), ('NEW_LOGOS', 'New Logos')], max_length=30, verbose_name='Objective Type')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Target Value')),
                ('is_primary', models.BooleanField(default=False, help_text='Only one primary objective per campaign', verbose_name='Is Primary')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='module_campaigns.campaign', verbose_name='Campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Campaign Objective',
                'verbose_name_plural': 'Campaign Objectives',
                'db_table': 'module_campaign_objectives',
                'ordering': ['campaign', '-is_primary', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type'], name='mod_camp_type_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['territory'], name='mod_camp_territory_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date', 'end_date'], name='mod_camp_dates_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('name', 'client_id')},
        ),
        migrations.AddIndex(
            model_name='campaignaccount',
            index=models.Index(fields=['campaign', 'status'], name='mod_ca_camp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignaccount',
            index=models.Index(fields=['account'], name='mod_ca_account_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignaccount',
            unique_together={('campaign', 'account', 'client_id')},
        ),
        migrations.AddIndex(
            model_name='campaignmember',
            index=models.Index(fields=['campaign', 'role'], name='mod_cm_camp_role_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignmember',
            index=models.Index(fields=['user', 'role'], name='mod_cm_user_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignmember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_owner', True)), fields=('campaign',), name='unique_primary_owner_per_campaign'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignmember',
            unique_together={('campaign', 'user', 'role', 'client_id')},
        ),
        migrations.AddIndex(
            model_name='campaignobjective',
            index=models.Index(fields=['is_primary', 'client_id'], name='module_camp_is_prim_952579_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignobjective',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('campaign',), name='mod_unique_primary_objective_per_campaign'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignobjective',
            unique_together={('campaign', 'objective_type', 'client_id')},
        ),
    ]
