# Generated by Django 5.1.4 on 2026-03-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_campaigns', '0001_initial'),
        ('module_territories', '0002_alter_territory_owner'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaign',
            name='mod_camp_territory_idx',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='territory',
        ),
        migrations.AddField(
            model_name='campaign',
            name='territories',
            field=models.ManyToManyField(blank=True, help_text='Source territories for OUTBOUND campaigns', related_name='campaigns', to='module_territories.territory', verbose_name='Territories'),
        ),
    ]
