# Generated by Django 5.1.4 on 2026-03-11 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_campaigns', '0002_remove_campaign_mod_camp_territory_idx_and_more'),
        ('module_contacts', '0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('CALLBACK_PENDING', 'Callback Pending'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=20, verbose_name='Status')),
                ('callback_date', models.DateField(blank=True, help_text='Scheduled callback date when status is CALLBACK_PENDING', null=True, verbose_name='Callback Date')),
                ('no_answer_count', models.PositiveSmallIntegerField(default=0, help_text='Number of consecutive no-answer outcomes for this contact', verbose_name='No Answer Count')),
                ('activities_generated', models.BooleanField(default=False, help_text='Whether sequence activities have been generated for this contact', verbose_name='Activities Generated')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('campaign_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='module_campaigns.campaignaccount', verbose_name='Campaign Account')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='module_contacts.contact', verbose_name='Contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Campaign Contact',
                'verbose_name_plural': 'Campaign Contacts',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('campaign_account', 'contact'), name='unique_campaign_account_contact')],
            },
        ),
    ]
