# Generated by Django 5.1.4 on 2026-03-11 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_modules', '0001_initial'),
        ('module_accounts', '0003_alter_companyaccount_industry'),
        ('module_campaigns', '0003_campaigncontact'),
        ('module_contacts', '0002_remove_contact_module_cont_first_n_da6ea2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignaccount',
            options={'ordering': ['-created_at'], 'verbose_name': 'Campaign Account', 'verbose_name_plural': 'Campaign Accounts'},
        ),
        migrations.AlterUniqueTogether(
            name='campaignaccount',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='campaignaccount',
            name='notes',
            field=models.TextField(blank=True, help_text='Context or reason for this account enrollment', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='campaignaccount',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AddConstraint(
            model_name='campaignaccount',
            constraint=models.UniqueConstraint(fields=('campaign', 'account', 'client_id'), name='unique_campaign_account_client'),
        ),
        migrations.RemoveField(
            model_name='campaignaccount',
            name='activities_generated',
        ),
        migrations.RemoveField(
            model_name='campaignaccount',
            name='callback_date',
        ),
        migrations.RemoveField(
            model_name='campaignaccount',
            name='no_answer_count',
        ),
    ]
