# Generated by Django 5.1.4
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_campaigns', '0004_alter_campaignaccount_options_and_more'),
    ]

    operations = [
        # Rename planned dates
        migrations.RenameField(
            model_name='campaign',
            old_name='start_date',
            new_name='planned_start_date',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='end_date',
            new_name='planned_end_date',
        ),

        # Add actual dates
        migrations.AddField(
            model_name='campaign',
            name='actual_start_date',
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name='Actual Start Date',
                help_text='Auto-set when campaign is started',
            ),
        ),
        migrations.AddField(
            model_name='campaign',
            name='actual_end_date',
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name='Actual End Date',
                help_text='Auto-set when campaign is completed or last activity is done',
            ),
        ),

        # Update index
        migrations.RemoveIndex(
            model_name='campaign',
            name='mod_camp_dates_idx',
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(
                fields=['planned_start_date', 'planned_end_date'],
                name='mod_camp_dates_idx',
            ),
        ),
    ]