# Generated by Django 5.1.4 on 2026-03-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_campaigns', '0005_campaign_date_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='planned_end_date',
            field=models.DateField(help_text='User-defined campaign end date', verbose_name='Planned End Date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='planned_start_date',
            field=models.DateField(help_text='User-defined campaign start date', verbose_name='Planned Start Date'),
        ),
    ]
