# Generated by Django 5.1.4 on 2026-03-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_campaigns', '0006_alter_campaign_planned_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigncontact',
            name='no_answer_count',
        ),
    ]
