# Generated by Django 5.1.4 on 2026-03-17 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_campaigns', '0007_remove_campaigncontact_no_answer_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='executor',
            field=models.ForeignKey(blank=True, help_text='User who executes activities. Defaults to owner if not set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_executing_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Executor'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who created and manages this campaign', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='module_owned_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.DeleteModel(
            name='CampaignMember',
        ),
    ]
