# Generated by Django 5.1.4 on 2026-03-17 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_campaigns', '0008_campaign_executor_campaign_owner_and_more'),
        ('module_territories', '0002_alter_territory_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(default='6d45bdd1-d27b-4b94-86c4-b5f612da2af3', help_text='User who created and manages this campaign', on_delete=django.db.models.deletion.PROTECT, related_name='module_owned_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(condition=models.Q(('campaign_type', 'TARGETED')), fields=('client_id', 'campaign_type', 'owner'), name='unique_targeted_campaign_per_user'),
        ),
    ]
