# Generated by Django 5.1.4 on 2026-03-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_campaigns', '0009_alter_campaign_owner_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together=set(),
        ),
    ]
