# Generated by Django 5.1.4 on 2026-03-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_campaigns', '0010_alter_campaign_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncontact',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('CALLBACK_PENDING', 'Callback Pending'), ('COMPLETED', 'Completed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
