# Generated by Django 5.1.4 on 2026-03-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_campaigns', '0012_campaignmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignMember',
        ),
    ]
