# Generated by Django 5.1.4 on 2026-03-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_campaigns', '0013_delete_campaignmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='channel_override',
            field=models.CharField(default='AUTO', help_text='AUTO = backend selects variant per contact channels. EMAIL_ONLY = force WITHOUT_PHONE variant for all contacts.', max_length=20, verbose_name='Channel Override'),
        ),
    ]
