# Generated by Django 5.1.14 on 2026-07-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_campaigns", "0014_campaign_channel_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigncontact",
            name="sequence_run",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Current chasing-run number for this contact. Starts at 1 and is incremented by reactivate() on every TARGETED re-chase. Activities are stamped with this value at creation to distinguish the current run from previous ones (which stay in the DB, only hidden from view).",
                verbose_name="Sequence Run",
            ),
        ),
    ]
