# Generated by Django 5.1.14 on 2026-08-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_campaigns", "0016_channel_override_no_calls"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigncontact",
            name="channel_override",
            field=models.CharField(
                blank=True,
                choices=[("AUTO", "Auto"), ("NO_CALLS", "No calls")],
                default=None,
                help_text="Per-contact channel override; NULL = follow the campaign",
                max_length=20,
                null=True,
                verbose_name="Channel Override",
            ),
        ),
    ]
