# Generated by Django 5.1.14 on 2026-08-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_campaigns", "0017_campaigncontact_channel_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="activity_objective",
            field=models.TextField(
                blank=True,
                help_text="Optional free-text objective for the campaign. Propagated onto each generated OUTBOUND activity as its call to action.",
                null=True,
                verbose_name="Activity Objective",
            ),
        ),
    ]
