# Generated by Django 5.1.14 on 2026-08-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_campaigns", "0018_campaign_activity_objective"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigncontact",
            name="objective",
            field=models.TextField(
                blank=True,
                help_text="Per-run objective entered at enrollment for a TARGETED contact. Populates the generated activity call_to_action. Reset on reactivate() — jetable per chasing run.",
                null=True,
                verbose_name="Objective",
            ),
        ),
    ]
