# Generated by Django 5.1.14 on 2026-08-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_modules", "0001_initial"),
        ("module_campaigns", "0019_campaigncontact_objective"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="target_departments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional: OUTBOUND enrols only contacts in these departments",
                related_name="campaign_targets",
                to="core_modules.standarddepartment",
                verbose_name="Target Departments",
            ),
        ),
    ]
