# Generated by Django 5.1.14 on 2026-08-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_campaigns", "0020_campaign_target_departments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignobjective",
            name="objective_type",
            field=models.CharField(
                choices=[
                    ("MEETINGS", "Number of Meetings"),
                    ("DECISION_CYCLES", "Decision Cycles Opened"),
                    ("CONTACTS_REACHED", "Contacts Reached"),
                    ("PIPELINE_VALUE", "Pipeline Value"),
                    ("REVENUE_WON", "Won Value"),
                    ("NEW_LOGOS", "New Logos"),
                ],
                max_length=30,
                verbose_name="Objective Type",
            ),
        ),
    ]
