# Generated by Django 5.1.4 on 2025-01-27 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_account_budgets_and_more'),
        ('end_users', '0003_user_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('insight_type', models.CharField(choices=[('ACCOUNT', 'Account-Wide Insight'), ('ORG_UNIT', 'Department-Level Insight'), ('QUALIFICATION', 'Sales Qualification Insight')], max_length=20, verbose_name='Insight Type')),
                ('buying_process', models.JSONField(blank=True, null=True, verbose_name='Buying Process')),
                ('pain_points', models.JSONField(blank=True, null=True, verbose_name='Pain Points')),
                ('business_impact', models.JSONField(blank=True, null=True, verbose_name='Business Impact')),
                ('success_criteria', models.JSONField(blank=True, null=True, verbose_name='Success Criteria')),
                ('strategic_goals', models.JSONField(blank=True, null=True, verbose_name='Strategic Goals')),
                ('technology_stack', models.JSONField(blank=True, null=True, verbose_name='Technology Stack')),
                ('budgets', models.JSONField(blank=True, null=True, verbose_name='Budgets')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights_as_account', to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Sales Insight',
                'verbose_name_plural': 'Sales Insights',
                'db_table': 'sales_insights',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['account'], name='sales_insig_account_65541f_idx')],
            },
        ),
    ]
