# Generated by Django 5.1.4 on 2025-04-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_insight', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signal',
        ),
    ]
