# Generated by Django 5.1.4 on 2025-01-27 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_account_insights'),
        ('sales_insight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinsight',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.account', verbose_name='Account'),
        ),
    ]
