# Generated by Django 5.1.4 on 2025-03-01 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_product_detail', '0001_initial'),
        ('accounts', '0001_initial'),
        ('contacts', '__first__'),
        ('end_users', '0001_initial'),
        ('org_units', '0001_initial'),
        ('products', '0001_initial'),
        ('sales_insight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('client_id', models.UUIDField(db_index=True, editable=False, help_text='ID of the client company this record belongs to', verbose_name='Client ID')),
                ('category', models.CharField(choices=[('PROFILE', 'Profile Data'), ('GOALS', 'Business/Unit Goals'), ('PROCESS', 'Process'), ('QUALIFICATION', 'Qualification'), ('PROJECT', 'Project')], max_length=20, verbose_name='Signal Category')),
                ('entity_type', models.CharField(choices=[('ACCOUNT', 'Account'), ('ORG_UNIT', 'Organization Unit'), ('CONTACT', 'Contact'), ('ACCOUNT_PRODUCT', 'Account Product Detail')], max_length=20, verbose_name='Entity Type')),
                ('field_name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('value', models.JSONField(verbose_name='Signal Value')),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10, verbose_name='Confidence Level')),
                ('potential_value', models.IntegerField(default=0, help_text='Estimated revenue impact (0-100)', verbose_name='Revenue Potential')),
                ('urgency', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10, verbose_name='Urgency Level')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied'), ('DORMANT', 'Dormant')], default='PENDING', max_length=20, verbose_name='Signal Status')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data Source')),
                ('revisit_date', models.DateTimeField(blank=True, null=True, verbose_name='Revisit Date')),
                ('applied_date', models.DateTimeField(blank=True, null=True, verbose_name='Applied Date')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.account', verbose_name='Account')),
                ('account_product_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='account_product_detail.accountproductdetail', verbose_name='Account Product Detail')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_signals', to='end_users.user', verbose_name='Approved By')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='contacts.contact', verbose_name='Contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='end_users.user', verbose_name='Created By')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='org_units.accountorganizationunit', verbose_name='Organization Unit')),
                ('parent_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_signals', to='sales_insight.signal', verbose_name='Parent Signal')),
                ('product_alignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aligned_signals', to='products.product', verbose_name='Aligned Products')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to='end_users.user', verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Signal',
                'verbose_name_plural': 'Signals',
                'db_table': 'signals',
                'ordering': ['-urgency', '-potential_value', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['account'], name='signals_account_b97c77_idx'), models.Index(fields=['org_unit'], name='signals_org_uni_1698e6_idx'), models.Index(fields=['contact'], name='signals_contact_1c6d44_idx'), models.Index(fields=['account_product_detail'], name='signals_account_cc0d75_idx'), models.Index(fields=['revisit_date'], name='signals_revisit_ca2d8b_idx'), models.Index(fields=['applied_date'], name='signals_applied_5dcc6b_idx')],
            },
        ),
    ]
