# Generated by Django 5.1.4 on 2025-03-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_insight', '0002_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata for validations, history, and context', null=True, verbose_name='Metadata'),
        ),
    ]
