# Generated by Django 5.1.4 on 2025-03-06 08:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_product_detail', '0002_accountproductdetail_historical_data'),
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
        ('end_users', '0001_initial'),
        ('org_units', '0001_initial'),
        ('products', '0001_initial'),
        ('sales_insight', '0003_signal_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualificationchange',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='qualificationchange',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='qualificationchange',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ['-created_at', 'confirmation_count'], 'verbose_name': 'Signal', 'verbose_name_plural': 'Signals'},
        ),
        migrations.RemoveField(
            model_name='signal',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='potential_value',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='urgency',
        ),
        migrations.AddField(
            model_name='signal',
            name='confirmation_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='signal',
            name='last_confirmed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signal',
            name='merged_from_signals',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied'), ('MERGED', 'Merged')], default='PENDING', max_length=20, verbose_name='Signal Status'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['last_confirmed_at'], name='signals_last_co_1597fb_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['confirmation_count'], name='signals_confirm_2cb000_idx'),
        ),
        migrations.DeleteModel(
            name='QualificationChange',
        ),
    ]
