# Generated by Django 5.1.4 on 2025-03-06 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_insight', '0004_remove_qualificationchange_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signal',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='signal',
            name='signals_account_b97c77_idx',
        ),
        migrations.RemoveIndex(
            model_name='signal',
            name='signals_org_uni_1698e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='signal',
            name='signals_contact_1c6d44_idx',
        ),
        migrations.RemoveIndex(
            model_name='signal',
            name='signals_account_cc0d75_idx',
        ),
        migrations.RemoveIndex(
            model_name='signal',
            name='signals_revisit_ca2d8b_idx',
        ),
        migrations.RemoveIndex(
            model_name='signal',
            name='signals_applied_5dcc6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='signal',
            name='signals_last_co_1597fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='signal',
            name='signals_confirm_2cb000_idx',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='merged_from_signals',
        ),
        migrations.AddField(
            model_name='signal',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from_signals', to='sales_insight.signal', verbose_name='Merged Into Signal'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='confirmation_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Confirmation Count'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='last_confirmed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last Confirmed At'),
        ),
        migrations.AlterModelTable(
            name='signal',
            table=None,
        ),
    ]
