# Generated by Django 5.1.4 on 2025-03-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_insight', '0005_alter_signal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='confirmation_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Confirmation Count'),
        ),
    ]
